RfidResearchGroup/proxmark3

- install.sh
Under Ubuntu 18.04, the proxmark3 client throws an error that the canberra-gtk-module is missing; this makes that message go away.
(I'm not sure if it's a problem on Homebrew as well, because I don't have a Mac for testing.)
> Add libcanberra-gtk-module to install.sh

- CHANGELOG.md
- install.sh
Added Ubuntu 18.04 detection, which needs `libcanberra-gtk-module` to compile the code as mentioned in #6  :
```bash
if [[ $(cat /etc/issue | awk '{print $2}') = *"18.04"* ]]; then 
apt-get install libcanberra-gtk-module
fi
```
Also, improved compilation times using max number of processors available on each machine:
+ Linux: `make all -j$(nproc)`
+ macOS: `make -j$(sysctl -n hw.physicalcpu)`
> Modified install.sh

- client/cmdhfmf.c
Just like `hf mf chk`, when the 't' option is provided make fchk put the
found keys into emulator memory.
> Populate emulator keys from `hf mf fchk`

- armsrc/lfops.c
CmdEM410xdemod returns "EM TAG ID: 0000000000 - (00000_000_00000000)" without card because considers a negative numbers as true.
https://stackoverflow.com/questions/14646718/if-statement-integer
> lfops.c CmdEM410xdemod empty TAG ID fix.

- client/cmdlfem4x.c
Just a quick patch to make `lf em 410x_spoof` command to work again
> em41 - spoof fix

- client/default_iclass_keys.dic
Key from HID multiclassSE reader has been added
> Add key to default_iclass_keys.dic

- client/mifare/mad.h
Latest merge (hf mf* mad) didn't compile due to a missing header.
> Add missing header

- client/mifare/mad.c
Well, in my not-so-big town, public transport card have mad sector with broken checksum (or unlikely proxmark client have broken crc implementation, but for now i'm unable to determine that).
Beside of that, sector is perfectly fine, and have information that are consistent with the actual usage of memory in the card, so i just make some small changes in proxmark client code to read it anyway
My proposal is - just write warning about bad crc and don't stop mad decoding procedure
> Mifare mad - do not exit if checksum is shitty

- common/i2c.c
Running sc upgrade was failing if we didn't run other sc command first because some init was missing
> Add missing i2c init in sc upgrade

- client/cmdsmartcard.c
when proxmark3 client is called outside its dir (e.g. when using proxmark3.sh for upper dir), "sc brute" didn  find aidlist.json
> Look for aidlist.json in the client dir

- client/cmdanalyse.c
"analyse nuid" used to work fine when it was introduced but when the code was updated to replace the ComputeCrc14443 & UpdateCrc14443 by compute_crc & update_crc16, computation became wrong and selftest failed.
This patch fixes the issue.
I also added in a comment the ref used by iceman when he introduced "analyse nuid".
> analyse nuid: fix crc -> selftest ok now

- armsrc/iso14443a.c
- armsrc/iso14443a.h
- common/protocols.h
New feature to store data from reader to 'hf 14a sim' Ultralight/NTAG emulator memory
> Mifare Ultralight/NTAG simulation. Add WRITE and COMPATIBLE_WRITE support

- client/cmdhf15.c
Fix for:
```
cmdhf15.c: In function ‘CmdHF15Restore’:
cmdhf15.c:876:45: warning: ‘ u ’ directive output may be truncated writing 3 bytes into a region of size between 1 and 255 [-Wformat-truncation=]
snprintf(tmpCmd, sizeof(tmpCmd), "%s u %u %s", newCmdPrefix, i, hex);
^~~
cmdhf15.c:876:42: note: directive argument in the range [0, 255]
snprintf(tmpCmd, sizeof(tmpCmd), "%s u %u %s", newCmdPrefix, i, hex);
^~~~~~~~~~~~
cmdhf15.c:876:9: note: ‘snprintf’ output between 6 and 516 bytes into a destination of size 255
snprintf(tmpCmd, sizeof(tmpCmd), "%s u %u %s", newCmdPrefix, i, hex);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cmdhf15.c:799:25: warning: ‘strncat’ output may be truncated copying between 0 and 254 bytes from a string of length 999 …
```
> Fix sizes for GCC 8.2 string truncation warnings

- client/cmdlfhid.c
- client/cmdlfhid.h
- client/util.c
- client/util.h
As requested by @iceman1001 here https://github.com/iceman1001/proxmark3/pull/285, notes below copied for convenience.
I came across a bag full of HID tags using this format that I couldn't find documented anywhere. After some poking and prodding at the bits I worked out the format and figured I would contribute the addition. I added support to the demoudulator, tested reading, cloning, wiegand output, and simulation. I did not add support for this format to the brute forcer as it would require refactoring to support the OEM segment, and just hard coded a 0 into the OEM parameter added to `clacWiegand` inside the brute forcing code.
This format is backwards in that the parity logic is swapped, so I duplicated the existing function to do this. Plenty of head scratching to finally figure …
> Add 36bit HID format, extend calcWiegand() to include oem bits

- armsrc/mifaresim.c
Wrong reference to Uart was used. LogTrace() not save actual incoming sequence.
There was a last known me bug in this module :)
> BugFix.'mifaresim.c' used wrong Uart reference

- CHANGELOG.md
- armsrc/mifaresim.c
- client/cmdhfmf.c
- common/protocols.h
1. Bug. Tag type missing if 'u <uid>' option place at the end of command line 'hf mf sim...'
2. Bug. Wrong ATQA used for single/double/triple uid sizes
3. Add. Possible to extract 4/7 uid, sak, atqa from emulator memory to exactly simulate loaded tag dump - 'hf mf sim' without parameters
4. Add. Support RATS+DESELECT responses for mifare NXP 2K tags simulation.
> 'hf mf sim' bugs fix, RATS support, etc

- CHANGELOG.md
- armsrc/iso14443a.c
- armsrc/iso14443a.h
- armsrc/util.c
- armsrc/util.h
- client/cmdhfmf.c
- client/cmdhfmfu.c
- client/cmdhfmfu.h
- client/loclass/fileutils.c
- client/loclass/fileutils.h
- client/scripts/dumptoemul-mfu.lua
- include/mifare.h
1) New header format of dump files for Ultralight/NTAG. Added counters to header, removed PACK from header, because PACK and PWD for EV1 stores into dump.
2) Fix EV1/NTAG simulation.
> UL/NTAG new dump file format. Added counters support, simulation

- client/comms.c
Don't copy more bytes into pm3_capabilities as its size.
Fix: RfidResearchGroup/proxmark3#189
> client/comms.c: fix buffer overflow

- client/Makefile
Make sure we use libreadline from brew and not the default macOS shipped one.
Otherwise compilation fails for undefined rl_event_hook
> client/Makefile: use brew libreadline on macOS

- client/proxguiqt.cpp
- client/proxguiqt.h
Adds bindings for HOME and END to jump to the start or end of the graph.
Adds bindings for PGUP and PGDOWN to move a page left or right on the graph.
Sets the PageWidth variable (wasn't set before) to contain the number of samples on the current page. (Fixes shift+arrow pagination)
> Added paged moving to the plot GUI

- armsrc/iso14443a.c
1. Bugfix. EV1 COMPATIBLE_WRITE command contains two parts: receive command and receive data
2. Reordered some conditions. We need to check any data before checking commands in received buffer, because data can be same to unexpected command
3. Additional length checks in  received command
4. Added EV1 virtual card support from config page of emulator memory
5. Defines used for constants
----
6. PACK-response to EV1 PASSWORD verification no more as precompiled sequence, because PACK can be changed dynamically to config page
7. Setting up minimal pages count for emulating Ultralight and EV1/NTAG tags, if loaded eml-file not contains whole dump
> fix: 'hf 14a sim' ultralight COMPATIBLE_WRITE command,

- uart/uart_posix.c
Relevant man pages say that with our previous
code libc might return either. Glibc returns tcp but
bionic returns udp. So specify it explicitly
> Specify that we need TCP and not UDP connection

- client/cmdlfhitag.c
Not the best solution, but better than the weird things happening now if no/invalid argument is passed.
> Print help if unknown arg for hitag reader/writer

- .gitignore
May help for people launching manually afterwards. It will also help if people have more than one proxmark connected, as they will know which one was selected.
>  Gitignore more linux profile related files 

- client/cmdhf15.c
Based on the commands in Iceman's lua script, here is the command to set UID on ISO15693 Magic tags.
```
[usb] pm3 --> hf 15 reader
UID  : E0 11 11 11 11 11 11 11
TYPE : Emosyn-EM Microelectronics USA
[usb] pm3 --> hf 15 csetuid E022222222222222
[+] new UID | E0 22 22 22 22 22 22 22
Using backdoor Magic tag function
received 0 octets
received 0 octets
received 3 octets
00 78 F0
received 3 octets
00 78 F0
[+] old UID : E0 11 11 11 11 11 11 11
[+] new UID : E0 22 22 22 22 22 22 22
[usb] pm3 --> hf 15 reader
UID  : E0 22 22 22 22 22 22 22
TYPE : Transcore USA
[usb] pm3 -->
```
> Add 'hf 15 csetuid' command to set UID on ISO15693 Magic tags

- armsrc/hitag2.c
- client/cmdlfhitag.c
- include/hitag.h
**Tested and working.**
My only concern is the following write in crypto mode:
https://github.com/RfidResearchGroup/proxmark3/blob/cb453139813a7b1b5ff17e6bd66d3e80075ead35/armsrc/hitag2.c#L506-L511
Unless I'm missing something, this is useless since the write at the top of the method:
https://github.com/RfidResearchGroup/proxmark3/blob/cb453139813a7b1b5ff17e6bd66d3e80075ead35/armsrc/hitag2.c#L449-L453
will be called long before this one is reached.
For that reason I added only the top write in password mode.
> Add hitag2 write password auth

- armsrc/mifaresim.c
Removed hard coded check for anti-collision during selection of emulated Mifare Classic tag
> Fix. More flexible anti-collision frame check (hf_mf_sim)

- common/mbedtls/config.h
see #258 for more information.
before mbedtls :  
```
arm-none-eabi-size obj/aes.o
text	   data	    bss	    dec	    hex	filename
15080	      0	      0	  15080	   3ae8	obj/aes.o
```
after mbedtls : 
```
arm-none-eabi-size obj/aes.o
text	   data	    bss	    dec	    hex	filename
10355	      0	   8748	  19103	   4a9f	obj/aes.o
```
after this pr : 
```
arm-none-eabi-size obj/aes.o
text	   data	    bss	    dec	    hex	filename
11983	      0	      0	  11983	   2ecf	obj/aes.o
```
> FIX: Get a usable AES implementation again

- .travis.yml
This reduce the time to build on OSX by 50%, and has also better Linux builds. Shouldn't timeout anymore.
> Try to have a better travis

- armsrc/ticks.c
FIXes #301 and prevent a `-1`aka`UINT_MAX` delta.
> Off by one in GetTickCountDelta (FIXes #301)

- client/util.c
sysconf() is  part of IEEE Std 1003.1-1988 (POSIX.1).
Fortunately, it *is* available to OSX `>=10.5`.
At least on `~10.14`, the old unposix `sysctl` osx way was lost, at least in portable environments.
This fixes it, but will not be compatible with OSX > 10.4. 
So i'm sorry but here we loose compatibility with Macs olders than 2005. (🤣)
> FIXes # 174 and more (OSX > 10.4 num_Cpus) the good way

- CHANGELOG.md
- client/cmdlfhitag.c
> Rework hitag2 read/write help

- doc/cheatsheet.md
> Cheatsheet update - Added commands & fixed typos

- client/cmdhfmf.c
There is false assumption in autopwn code that function `detect_classic_prng()` returns only vaules 1 or 0 so its interpreted as boolean. So if there is no tag on the device - autopwn runs cracking procedure printing a LOTS of errors.
> autopwn: fix card detection

- tools/jtag_openocd/interface-raspberrypi2.cfg
Both interface-raspberrypi.cfg and interface-raspberrypi2.cfg gave conflicting instructions for the dd return value. This should clear that up.
> subtle change for clarity in comment

- CHANGELOG.md
- client/cmdlfem4x.c
The lf em 4x05_dump was missing the code to print the data for the dump.
It was only showing the "special purpose" block 2 - password.
Now shows all 16 blocks of data.
> lf em 4x05_dump - print output for each block read

- CHANGELOG.md
- armsrc/lfsampling.c
- client/cmdlf.c
- include/pm3_cmd.h
This will allow the lf sniff to skip over x samples to allow capture of larger signals (e.g. cloners)
With the unint_32 for the samples to skip, the s <value> will be reset to 0 if not supplied on the lf config command.  If needed to retain the last value set, we could use 0xffffffff as the "default" to mean don't change from last set value set (comment lines left in code).
> lf config s <samples to skip> option added

- client/luascripts/Legic_clone.lua
This PR fixes a couple minor `Legic_clone.lua` script typos.
> Fix Legic_clone.lua script typos

- client/cmdlfhid.c
Currently, the high bit for Kastle HID is omitted from the output, which results in an invalid clone ID when lf hid clone [id] is used. Displaying the high bit along with the rest of the ID would allow these ID cards to be cloned properly.
> Display high bit for Kastle HID to allow for lf hid clone

- CHANGELOG.md
Display high bit for detected Kastle HIDs to allow `lf hid clone [id]` to work properly
> Update CHANGELOG.md for Kastle HID high bit change

- client/cmdhfmfu.c
PACK wasn't included in the output dump due to incorrect check of ul_auth_select return value
> Fix pack in dump

- doc/clocks.md
Feel free to comment / fix  / complete.
I wrote what I understood so far.
Still I don't understand why we have both Ticks and CountUS set of functions using the same timers for what looks like similar purposes
> WIP Attempt to document clocks and timers

- client/cmdhffelica.c
- include/mifare.h
Adds three new FeliCa commands:
Request Specification Version: Gives the Card OS information.
Reset Mode: Sets the Auth Mode back to 00h.
Request System Code: Gives a list of all system codes.
Bug-fix:
Fix a segmentation fault in the raw command when no card is on the reader.
> Felica support: Add new commands

- CHANGELOG.md
- armsrc/hitagS.c
`lf hitag reader 02` on a hitag S tag showed only the first byte of every page:
#db# Authenticating using key:
#db# 00 00 00 00 00 00
#db# Page[ 0]: 00 00 00 5F
#db# Page[ 1]: 00 00 00 C9
#db# Page[ 2]: 00 00 00 48
#db# Page[ 3]: 00 00 00 4D
#db# Page[ 4]: 00 00 00 00
#db# Page[ 5]: 00 00 00 00
#db# Page[ 6]: 00 00 00 00
#db# Page[ 7]: 00 00 00 57
fixed in `ReadHitagS`, so reader command now shows all bytes.
... but I also suspect function `SimulateHitagSTag` to be involved...
Only other reader to verify I have is a RFIDler which does not yet want to talk with proxmark rdv4 :-/
Will give it some more tries...
> Fix hitagS reader output

- client/cmdhfmf.c
Corrected csave usage to show `o` flag for output file instead of `i`.
> Correct usage for 'hf mf csave'

- CHANGELOG.md
- client/cmdhflto.c
- client/cmdhflto.h
Test results: 
Write: 
`[usb] pm3 --> hf lto wrbl b 128 d0001020304050607080910111213141516171819202122232425262728293031`
`[+] BLK128: Write Success`
Verify:
`[usb] pm3 --> hf lto rdbl s 128 e 128`
`[+] BLK128: 0001020304050607080910111213141516171819202122232425262728293031`
Also checked `hf lto list` after the write command. Everything looks good.
> added write block command for LTO-CM

- CHANGELOG.md
- client/cmdhflto.c
- client/cmdhflto.h
Tested commands:
- No file name specified:  
`[usb] pm3 --> hf lto dump`
`[+] saved 8160  bytes to binary file XXXXXXXXXX.bin`
`[+] saved 255  blocks to text file XXXXXXXXXX.eml`
where XXXXXXXXXX = UID of the tag in hex.
- File name specified by f option: 
`[usb] pm3 --> hf lto dump f test`
`[+] saved 8160  bytes to binary file test.bin`
`[+] saved 255  blocks to text file test.eml`
> added hf lto dump

- client/fileutils.c
Before this patch:
```
[usb] pm3 --> hf iclass chk f client/dictionaries/iclass_default_keys.dic
[+] loaded  0 keys from dictionary file client/dictionaries/iclass_default_keys.dic
[usb] pm3 -->
```
After this patch:
```
[usb] pm3 --> hf iclass chk f client/dictionaries/iclass_default_keys.dic
[+] loaded  7 keys from dictionary file client/dictionaries/iclass_default_keys.dic
[+] Reading tag CSN
(further communication continues)
```
It looks like the regression came from #484; it was fixed in 94eb741a4 for `loadFileDICTIONARYEx`, but not `loadFileDICTIONARY_safe`.
> fix: logic inversion in loadFileDICTIONARY_safe use of CheckStringIsHEXValue

- armsrc/Standalone/Makefile.hal
- armsrc/Standalone/Makefile.inc
- armsrc/Standalone/hf_14asniff.c
This standalone module sniffs ISO14a packets and writes it to flash as `hf_14asniff.trc`.
It is based on `HF_BOG`, but that only logs ULC/NTAG/ULEV1 auth; where as I'd like to get complete traces.
Because this module only logs the traces to flash and doesn't do anything special with it, it just calls out to `SniffIso14443a()`.
Documentation is included at the start of the file (similar to other modes).
> feature: standalone sniff iso14a to flash (HF_14ASNIFF)

- client/cmdsmartcard.c
A small change that just follows the redirect on the page as it was apparently moved.
> Fixed the url for smartcard ATR lookup

- CHANGELOG.md
- client/cmdhflto.c
- client/cmdhflto.h
Fix filename for `hf lto dump`.
Before
~~~
[usb] pm3 --> hf lto dump
[+] saved 8160  bytes to binary file xxxxxxxxxx.bin
[+] saved 255  blocks to text file xxxxxxxxxx.eml
~~~
After
~~~
[usb] pm3 --> hf lto dump
[+] saved 8160  bytes to binary file hf_lto_xxxxxxxxxx.bin
[+] saved 255  blocks to text file hf_lto_xxxxxxxxxx.eml
~~~
where xxxxxxxxxx is a UID.
***
Add `hf lto restore`.
Dump data from tag.A
~~~
[usb] pm3 --> hf lto dump
[+] saved 8160  bytes to binary file hf_lto_xxxxxxxxxx.bin
[+] saved 255  blocks to text file hf_lto_xxxxxxxxxx.eml
~~~
Then, restore this file to different tag.B
~~~
[usb] pm3 --> hf lto restore f hf_lto_xxxxxxxxxx.bin
~~~
Then, dump data from tag.B
~~~
[usb] pm3 --> hf lto dump
[+] saved 8160  bytes to binary file hf_lto_yyyyyyyyyy.bin
[+] saved 255  blocks to …
> added `hf lto restore` and fix filename for dump

- armsrc/hitagS.c
1. hitagS read would stop after 2 pages when read with challenge or key.
2. additional to print failed challenges, print succeeded challenges in a format to easier use/grep with hitagcrack functions.
> hitagS print whole memory + print succeeded challenges

- tools/analyzesize.py
Python2.7 doc for `sys` module states that "Most systems require [the
exit code] to be in the range 0-127, and produce undefined results
otherwise".
https://docs.python.org/2/library/sys.html#sys.exit
Currently, modern Linux-based systems will exit with code 255, while
msys2-based systems such as Proxspace will exit with code 127.
Instead, explicitly exit with non-zero exit code of 2.
Encountered while testing #561 on Proxspace.
> Remove potentially undefined exit behaviour from analyzesize tool

- client/gen_pm3mfsim_script.sh
- covbuild.sh
- covconfig.sh
- covsubmit.sh
- pm3
- pm3-flash
- pm3-flash-all
- pm3-flash-bootrom
- pm3-flash-fullimage
- pm3test.sh
- tools/analyzesize.py
- tools/findbits.py
- tools/findbits_test.py
- tools/hitag2crack/crack2/runtest.sh
- tools/jtag_openocd/openocd_flash_dump.sh
- tools/jtag_openocd/openocd_flash_recovery.sh
- tools/jtag_openocd/openocd_interactive.sh
- tools/mkversion.pl
- tools/pm3_amii_bin2eml.pl
- tools/pm3_cs8.pl
- tools/pm3_eml2lower.sh
- tools/pm3_eml2mfd.py
- tools/pm3_eml2upper.sh
- tools/pm3_eml_mfd_test.py
- tools/pm3_mfd2eml.py
- tools/rfidtest.pl
- tools/xorcheck.py
Use the `env` command in shebangs to find the correct interpreter instead of hard-coding paths.
Fixes #560
> Use /usr/bin/env in shebangs

- tools/pm3_eml2mfd.py
- tools/pm3_eml_mfd_test.py
- tools/pm3_mfd2eml.py
Works towards #564 
Need someone to check my bytes<->string stuff is okay in python3, to make sure I'm not testing _nothing_ here.
> convert python2 mfd2eml and eml2mfd scripts to python3

- client/cmdhfmfhard.c
Why not just free after key found or not found?
> fix: #520 - free mutex after work is done

- client/cmdlfparadox.c
Hi guys I was playing with a Paradox tag and saw the following:
```
[usb] pm3 --> lf paradox clone
clone a Paradox tag to a T55x7 tag.
Usage: lf paradox clone [h] [b <raw hex>]
Options:
h               : this help
b <raw hex>     : raw hex data. 12 bytes max
Examples:
lf paradox clone 0f55555695596a6a9999a59a
```
In the Examples, I think the correct command is:
```
lf paradox clone b 0f55555695596a6a9999a59a
```
Otherwise shows the help over and over. Basically, just a missing `b`.
> Missing b on Example

- CHANGELOG.md
- armsrc/hitagS.c
I'm trying to get hitag S simulation to work.
Only partial success :-( and now stuck.
UID is D4 8E 09 8E ;   D4: 11010100 ; advanced mode 3 bits SOF
triggering for now with another proxmark by: lf cmdread d 50 z 116 o 166 c 011001
(but also via: lf hitag read 01)
I have a real tag with this id also to compare.
Any hints where I can influence 1+2 are appreciated...
Tag simulation sending UID:
1. In the beginning the first half period is too long, and one period is missing
I can add the period in hitag_send_frame as a workaround by inserting at the beginning:
```
AT91C_BASE_TC0->TC_CCR = AT91C_TC_SWTRG;
// AC coding -_
HIGH(GPIO_SSC_DOUT);
while (AT91C_BASE_TC0->TC_CV < T0 * 16) {};
LOW(GPIO_SSC_DOUT);
while (AT91C_BASE_TC0->TC_CV < T0 * 32) {};
```
but it does not solve the length of the …
> hitagS fix sim + write

- client/cmdlfkeri.c
As well as the original 
lf keri clone <internal cardid> 
it now supports
lf keri clone type ms fc 7 cardid 35423
Note: each command line option is based on the first letter (e.g. t for type, m for ms, f for fc etc)
so supports both readable and short version.
I have left the original command line options in tact, as such left the original help line as well.
let me know if I have missed something.
> Keri ms clone support with fc and cardid

- client/dictionaries/mfc_default_keys.dic
Works with any Bosch Solution 6000 PR11xB reader.
> Bosch Solution 6000 Key Sector 0 Key A&B

- Makefile
recode is missing on macOS by default.
grep on macOS is BSD grep by default.
> Makefile: target checks for macOS

- client/cmdhf14a.c
These changes attempt to improve the hf 14a info card detection to give better possible card recommendations and is based on the NXP AN10833 Rev 3.6 MIFARE Type Identification. It was tested with more than 20 cards (desfire ev1/mifare classic/mifare plus/ultralight c/jcop 4). It does now also contain a uid table for some 14443-a cards to improve detection.
> Improve 14443-a info

- client/cmdhfmfdes.c
This fixes a problem that before select appid, DropField has to be called to allow select appid being called more than one time, otherwise a timeout will occur.
> Fix issue #646

- client/cmdhflegic.c
Check was off-by-one so that the last byte was not writable.
> hf legic wrbl: fix Out-of-bounds check

- CHANGELOG.md
- armsrc/desfire.h
- client/cmdhflist.c
- client/cmdhfmfdes.c
- include/protocols.h
If a Mifare Desfire card supports the GetDFNames command, it will print out the 
corresponding DF name for the app id.
```
[con] pm3 --> hf mfdes enum          
[=] -- Mifare DESFire Enumerate applications --------------------          
[=] -------------------------------------------------------------          
[+]  Tag report 2 applications          
[+] --- AMK - Application Master Key settings           
[+]   AID : 00 83 80           
[+]   -  DF 00 83  Name : OWOK light           
[+]   AID Key settings           : 0b          
[+]   Max number of keys in AID  : 142          
[=] -------------------------------------------------------------          
[+]   Changekey Access rights          
[+]   -- AMK authentication is necessary to change any key (default)          
[+]    [0x08] …
```
> Mifare Desfire DF Name display support and hf mfdes enum output improvement

- CHANGELOG.md
- client/luascripts/legic.lua
Fixed/changed things:
* added info that virtual tag is always MIM1024
* changed reading files to read binary files (as written by 'hf legic dump')
* changed extension for writing files (*.bin and *.eml) to be on par with 'hf legic dump'
* CRC was calculated wrong when data was not padded with 0 for one char hex strings
* readTag (rt) can now be called multiple times without using the wrong filename
* tag length was calculated wrong as segment header length field includes the header itself
* bytes are XORed before writing them to a tag
* default name for file contains now the tag id
> legic.lua: updated to work again

- client/cmdhfmfdes.c
Make clang happy and fix several
error: expression which evaluates to zero treated as a null pointer constant of type 'uint8_t *' (aka 'unsigned char *')
[-Werror,-Wnon-literal-null-conversion]
and
cmdhfmfdes.c:732:31: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
Fixes RfidResearchGroup/proxmark3#659
> cmdhfmfdes: fix clang warnings

- client/cmdhfmfdes.c
Fixes:  RfidResearchGroup/proxmark3#676
> cmdhfmfdes: Fix clang tautological-pointer-compare warning

- CHANGELOG.md
- client/cmdhfmfdes.c
So now we can read, create, change, clear and write files in plaintext mode for
mifare desfire cards. CMAC + Enciphered Mode has to be implemented, as well as detection
for those modes (and error handling of course). Additional fixes for 'hf mfdes enum" as file sizes and infos were displayed incorrectly.
> Mifare Desfire functionality update (Read/Write/Clear files) and fixes

- client/CMakeLists.txt
This is like we find qt in the Wireshark project.
Tested it with macOS. Not tested with Linux, WSL etc.
This is just a suggestion
> cmake: fix qt handling for macos

- client/CMakeLists.txt
I guess it is ugly and not how it should be made with cmake but it works.
> cmake macOS: use brew installed readline

- client/src/cmdhfmfu.c
> Fix uint8 vs uint32 interval number for tearoff experiment

- CHANGELOG.md
- armsrc/Standalone/Makefile.hal
- armsrc/Standalone/Makefile.inc
- armsrc/Standalone/hf_msdsal.c
- armsrc/iso14443a.c
- armsrc/iso14443a.h
- doc/md/Use_of_Proxmark/4_Advanced-compilation-parameters.md
People will be able to read 14a cards(Visa payment cards) and emulated them as Visa MSD card; not only the UIDs but the complete APDU communication.
Reading or emulating ISO-14443A technology is not limited to payment cards. This example was not only designed to make a replay attack, but to open new possibilities into the ISO-14443A technologies such as relay attacks in a near future with the Proxmark.
> New standalone mode: MSDSAL

- Makefile.defs
- client/src/proxendian.h
Only some OSes include endian.h from sys/types.h, not Termux, so let's include endian.h directly.
Moreover the past logic defined BYTE_ORDER to an undef macro, so BYTE_ORDER was not undef but def to 0
and BYTE_ORDER != LITTLE_ENDIAN && BYTE_ORDER != BIG_ENDIAN was always false as (0!=0 && 0!=0)
> Fix 2 issues in proxendian.h, see details:

- client/src/proxendian.h
referencing issue #730 / PR #731 
platform check is needed if bypassing <sys/types.h> on os x.
include <machine/endian.h> instead of <endian.h> to avoid the error below.
```
In file included from src/flash.c:20:
./src/proxendian.h:20:11: fatal error: 'endian.h' file not found
^~~~~~~~~~
1 error generated.
```
> include machine/endian.h for os x

- .gitignore
My git client goes insane during compilation seeing new `*.tmp` files popping up and disappearing. I think it doesn't hurt anything to add it to `.gitignore`
> add *.tmp to .gitignore

- client/dictionaries/mfc_default_keys.dic
Found another CharlieCard key, so I figured I'd contribute. Found using the mf hardnested attack. Was originally [here](https://github.com/iceman1001/proxmark3/pull/299) before I realized this dictionary existed.
> Additional CharlieCard Key

- CHANGELOG.md
- common/lfdemod.c
Fixed the following problem:
`lf search´ with an em4x50 tag placed on the device may result in `no known tags found´ and `lf em 4x50_read´ shows parity errors. The problem only occurs if the first bit of an em4x50 word is `0´. If it’s `1´ everything works as expected.
Reason: When performing the raw Manchester decoding in function `cleanAskRawDemod(…)´ the first transition of the signal is not evaluated due to the function call `getNextHigh(…)´. 
I tested the modification against the v4.9237 release by comparing the demodulation results with the available traces in the proxmark `traces´ directory. Doublecheck has been done with numerous available lf cards (em4x50, em41x, em42x, hid, …).
So far I couldn’t observe any differences…
> Fix em4x50

- tools/hitag2crack/crack5/ht2crack5.c
Thank you for including the hitag2hell attack code in the project. I noticed that the version of the code published during the WOOT proceedings was not generated using the very latest version of the memoization algorithm. The fixes in this PR make the CPU implementation about 10% faster in practice according to my benchmark. The published GPU version is not affected by this oversight.
Please let me know if you have plans to develop this implementation further, for example to add support for smaller or larger vector machines as was done for the crypto1 hardnested attack. I would like to point out in advance that such a modification would work better when the vector size is taken into account in the cracker code itself, because the work per layer is distributed differently as a consequence …
> Little optimization for hitag2hell attack

- CHANGELOG.md
- armsrc/Makefile
- armsrc/appmain.c
- armsrc/em4x50.c
- armsrc/em4x50.h
- client/CMakeLists.txt
- client/Makefile
- client/src/cmdlfem4x.c
- client/src/cmdlfem4x50.c
- client/src/cmdlfem4x50.h
- common_arm/Makefile.hal
- include/em4x50.h
- include/pm3_cmd.h
Added lf functions for EM4x50:
1. 4x50_info (displays all available info of EM4x50 tag)
2. 4x50_write (writes a single word to a specified address of EM4x50 tag)
3. 4x50_write_password (changes password of EM4x50 tag)
Decoding is done on the fly on device side (by directly interpreting pulse lengths, no GraphBuffer)
- no memory limitations (a tag with 33 words is fully readable)
- can be used in standalone mode
Functions currently only work for Opt64 data rate because I don't have any Opt32 EM4x50 tags. 
Implementation is heavily based on EM4450 datasheet and EM4150 application note (AppNote 406) with ideas from hitag2 code.
>  EM4x50 missing functions 4x50_info, 4x50_ write, 4x50_write_password

- client/src/cmdhfmfu.c
I have new russian Mikron Ultralight tag.
Dump command compleates with error, but dump file is created.
But i got an error while trying to read/write blocks, beacuse we think that card have only 0 block.
I assume that I need to add version detection to hf_mfu command =)
```
[usb] pm3 --> hf mfu dump
TYPE: Unknown 000000
[+] Reading tag memory...
[!] Authentication Failed UL-EV1/NTAG
[=] MFU dump file information
[=] -------------------------------------------------------------
[=]       Version | 00 34 21 01 01 00 0E 03
[=]         TBD 0 | 00 00
[=]         TBD 1 | 00
[=]     Signature | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[=]     Counter 0 | 00 00 00
[=]     Tearing 0 | 00
[=]     Counter 1 | 00 00 00
[=]     Tearing 1 | 00
[=] …
```
> Add support for new "Mikron JSC Russia" UL tag.

- client/src/cmdlfhitag.c
Added back usage menu as default option for for hitag reader and writer commands.
> Show usage menu for invalid/missing hitag commands

- README.md
- armsrc/appmain.c
- armsrc/em4x50.c
- armsrc/em4x50.h
- client/src/cmdlfem4x.c
- client/src/cmdlfem4x50.c
- client/src/cmdlfem4x50.h
- include/em4x50.h
- include/pm3_cmd.h
Added new read function "sread" for EM4x50 (device side): 
- If no option is given „em4x50_sread“ carries out a „standard read“, i.e. the data transmitted by tag voluntarily is catched and decoded.
- If a dedicated address is given (option a) „em4x50_sread“ carries out a „selective read“, i.e. data stored at this address is requested and decoded.
> EM4x50 function "sread" (standard/selective read)

- client/src/cmdlfparadox.c
Wrong offset leads to wrong hi2, hi and lo values.
> fix a bug in demodParadox()

- armsrc/appmain.c
- armsrc/em4x50.c
- armsrc/em4x50.h
- client/src/cmdlfem4x.c
- client/src/cmdlfem4x50.c
- client/src/cmdlfem4x50.h
- include/pm3_cmd.h
Added function "4x50_wipe" to clear an EM4x50 tag, i.e. fill/overwrite everything with "0" (including password);
UID and serial can not be changed!
> added 4x50_wipe

- client/gen_pm3mfsim_script.sh
The script for generating a MiFare Classic emulation script (located at `client/gen_pm3mfsim_script.sh`) was missing a parameter in the script generation process. This pull request adds the missing parameter.
> Fixed gen_pm3mfsim_script.sh

- doc/cheatsheet.md
- doc/commands.md
- doc/md/Installation_Instructions/Troubleshooting.md
- doc/md/Use_of_Proxmark/2_Configuration-and-Verification.md
The documentation was refering to the command related to Smart Card as `sc` while it is instead the `smart` command.
Entering `sc` in the proxmark3 client runs the `script` command.
```
[usb] pm3 --> sc
help             Usage info
list             List available scripts
run              <name> -- execute a script
[usb] pm3 --> script
help             Usage info
list             List available scripts
run              <name> -- execute a script
[usb] pm3 --> smart
help             This help
list             List ISO 7816 history
info             Tag information
reader           Act like an IS07816 reader
raw              Send raw hex data to tag
upgrade          Upgrade sim module firmware
setclock         Set clock speed
brute            Bruteforce SFI
```
```
[usb] pm3 --> help
-------- …
```
> Documentation: changed the `sc` command to `smart`

- doc/md/Installation_Instructions/Windows-Installation-Instructions.md
WSL 2 currently does not support USB and Serial.
Although you can get around with usbip-win; it requires a reconfigured kernel to be compiled.
> Redefine the WSL docs, as WSL 2 is available now

- client/src/proxmark3.c
The registry key at `HKEY_CURRENT_USER\Console\VirtualTerminalLevel` sets the global default, but calling the SetConsoleMode API with the `ENABLE_VIRTUAL_TERMINAL_PROCESSING (0x0400)` flag will enable ansi color support, regardless of the global default.
Tested on Windows 10 2004 and Windows 7. On Windows versions prior to Windows 10 Anniversary Update SetConsoleMode will fail and ansi color support is turned off.
> Registry entries are not needed when calling SetConsoleMode

- armsrc/Standalone/Makefile.hal
- armsrc/Standalone/Makefile.inc
- armsrc/Standalone/hf_aveful.c
- armsrc/Standalone/hf_aveul.c
This PR adds `hf_aveful`, which is a standalone mode that aims to read and simulate Mifare Ultralights (and Ultralight clones) on the go, with the process for reading a card taking less than a second. This doesn't include EV1, C etc.
C is not really a language I use a lot, so there may be potential improvements that can be done to a bunch of the code. Input welcome :)
Right now I am only accounting for Ultralights/clones with 16 blocks/pages, though I've supplied `define` options, so users that want to modify the code to work with other stuff (My-d move, my-d NFC, and Mifare Ultralight Nanos etc) can easily do so.
If anyone's interested in using this but aren't using master due to MERGEHELL: I've confirmed that the code works fine on both master and the latest stable release at the time …
> Add standalone mode hf_aveful: Mifare ultralight read/simulation

- CHANGELOG.md
- armsrc/appmain.c
- armsrc/mifarecmd.c
- armsrc/mifarecmd.h
- client/src/cmdhfmf.c
- client/src/mifare/mifarehost.c
- client/src/mifare/mifarehost.h
- include/pm3_cmd.h
There are three operations for magic gen3 cards:
- changing UID of card without changes of manufacturer block
- full overwrite manufacturer block
- locking further UID changes
> Magic gen 3 cards support

- client/src/cmdhfmfu.c
As discussed on Discord, the code adding pack (`memcpy(data + (pages * 4) - 4, get_pack, sizeof(get_pack));`) to the last page ends up causing dumps that (incorrectly) have 0x00 0x00 as first 2 bytes of the last page on dump, which is incorrect:
This PR adds my-d move and my-d move leans to the lists of card types where this behavior is not applied, which in turn results in proper dumps.
I don't have a my-d or my-d NFC to test with (and I cannot seem to find their datasheets), so I chose to not exclude them. Let me know if you need any changes.
> Fix last block of dumps on my-d move/move lean

- armsrc/appmain.c
- armsrc/mifarecmd.c
- armsrc/mifarecmd.h
- armsrc/mifareutil.c
- armsrc/mifareutil.h
- client/src/cmdhfmfu.c
- include/pm3_cmd.h
This PR causes `hf mfu wrbl` to do a compatibility write (0xA0) instead of a regular write (0xA2) when given 16 bytes instead of 4.
I'm not really experienced with C, so advice is welcome on how I can improve things like the way I set `datalen`, the nested ifs for the two different data types or perhaps not having the if for `SendCommandMIX` that way. I can also merge `CMD_HF_MIFAREU_WRITEBL` and `CMD_HF_MIFAREU_WRITEBL_COMPAT` etc if needed.
> Introduce compatible write support to hf mfu wrbl

- client/src/cmdhfmf.c
Continuing based on https://github.com/RfidResearchGroup/proxmark3/commit/aa756aa493b73f5bcc2c75fbc3239cd83346b3a2
With this change I am able to `autopwn` cards with hard PRNG once again
> hf mf autopwn: fix static nonce detection

- doc/md/Installation_Instructions/Windows-Installation-Instructions.md
ProxSpace can not be cloned, as this causes errors during the installation.
runme.bat does no longer exist.
> Corrected ProxSpace installation.

- appveyor.yml
Running ProxSpace and WSL installation in parallel saves about 6 minutes of appveyor runtime.
Shall I add a separate job for WSL compilation as well? This would save about 8 minutes of appveyor runtime. I would start the WSL compilation job in the background and would start printing its output once the ProxSpace compilation job is finished.
> Appveyor run WSL installation in parallel

- client/src/cmdhfst.c
This adds the ability to disable/enable read and write protection on the ST25TA series of tags with a known write password
> add ST25TA ndef protection logic

- client/src/cmdhfst.c
This commit adds the ability to change both read and write passwords on the ST25TA series of tags with a known write password
> add ST25TA password change logic

- armsrc/Standalone/hf_aveful.c
This PR:
- Adds support to dynamically determine block size of supported cards (based on cmdhfmfu.c)
- Adds explicit support for Ultralight, Ultralight EV1, Infineon my-d Move.
- Adds support to dynamically form the emulation metadata to properly emulate all parts of the card (that rest of pm3 can emulate, that is :) )
- Fixes a styling issue `(state == 2)` -> `(state == STATE_EMUL)`
- Fixes emulation mode (2 -> 7)
---
Huge shoutouts to @linuxgemini for shipping me test cards of official ultralight and ultralight EV1.
---
Note: One of the official ultralights sget detected improperly as NTAG215s by taginfo when used with this, but that also happens with regular eload and sim, so I don't think that's a bug with this.
> hf_aveful: Add Ultralight EV1 support, clean code, dynamically determine block size

- client/src/cmdhf14b.c
I found out that if I use the command "hf 14b dump" without any parameters instead of getting the help like other commands it tries to dump to file. I corrected this behavior so that calling the command without parameter the help will be shown.
I fixed also a couple of typo in the help itself.
> 'hf 14b dump' without params now calls help and corrected a typo

- appveyor.yml
ErrorAction will remove the error from the log and store it in a variable. ErrorAction Stop is not needed anyways.
> Removed ErrorAction

- client/deps/cliparser/cliparser.c
- client/src/cmdhfmfdes.c
This PR changes the CLIParamHexToBuf/CLIParamStrToBuf's temporary buffer from 256 bytes to 512 bytes, allowing hex strings representing up to 256 bytes instead of 128 bytes. It also updates the help text to help the user.
As a result, this PR fixes #977.
> Allow writes up to 256 bytes with mfdes writedata

- client/src/cmdlfhid.c
- doc/cheatsheet.md
- traces/lf_ATA5577.txt
I had to rework the bit shift stuff for `sim` and `clone` to use the uint8_t bytes instead of parsing the char Cmd characters individually with sscanf(), I couldn't find an elegant way to do it that maintained readability.
> lf hid clone, sim, brute, watch - now use cliparser

- appveyor.yml
Using the Appveyor cache to speed up the build process. Successful builds will take about the same time (WSL updating takes time), but builds that fail on ProxSpace will result in an earlier Appveyor abortion.
Fixed some small bugs as well.
> Appveyor use build cache for ProxSace packages

- pm3
The WSL distribution of Debian uses mawk instead of gawk by default, which does not support matching into an array as it is currently being done for extracting the COM port from the device name.
This commit replaces awk by sed, which also simplifies the building of /dev/ttySx paths.
> Replace awk with sed for WSL

- client/src/cmdhffido.c
both cmd_hf_fido_list and cmd_hf_fido_info were stepping on each other
> fix fido2 list/info

- Makefile.defs
bypass [recently added](https://github.com/RfidResearchGroup/proxmark3/commit/daabdf2e31cde2f8f91bb5e10452f05eb08bbdbc#diff-92cf8d6e0946797b698d8a09b83de4bc01ba6d247de0c77bd724af970edca955R71) `-Wno-stringop-overflow` and `stringop-overflow=` flags when clang is detected.
> skip stringop-overflow warning flags if clang is detected

- client/dictionaries/mfc_default_keys.dic
One line was commented with a wrong marker (`,` instead of `#`).
> Fixed comment in MIFARE Classic dictionary.

- client/src/cmdhfmfdes.c
- client/src/mifare/desfire_crypto.c
- client/src/mifare/desfire_crypto.h
- include/mifare.h
This adds two new options to `hf mfdes auth`
```
-d, --kdf <kdf>                Key Derivation Function (KDF) (0=None, 1=AN10922)
-i, --kdfi <kdfi>              KDF input (HEX 1-31 bytes)
```
By specifying `-d 1` and some kdf data `-i 00112233`, the key will be
diversified using AN10922.
> Add initial suport for MIFARE Key Diversification (AN10922)

- CHANGELOG.md
- client/resources/aid_desfire.json
- client/src/cmdhfmfdes.c
- common/generator.c
- common/generator.h
- include/mifare.h
Both `hf mfdes auth` and `hf mfdes chk` now support Key Diversification for AN10922 and as special treat, Gallagher issued cards.
For `hf mfdes auth`:
```
-d, --kdf <kdf>                Key Derivation Function (KDF) (0=None, 1=AN10922, 2=Gallagher)
-i, --kdfi <kdfi>              KDF input (HEX 1-31 bytes)
```
And for `hf mfdes chk`:
```
-f, --kdf <kdf>                Key Derivation Function (KDF) (0=None, 1=AN10922, Gallagher)
-i, --kdfi <kdfi>              KDF input (HEX 1-31 bytes)
```
> Please note the `-f` option for `chk` since `-d` is used to specify the dictionary input
Examples:
- `hf mfdes auth -a 2081f4 -m 3 -t 4 -d 2 -n 2 -k 00112233445566778899aabbccddeeff`
Will diversify the key for key `2` on AID `2081F4` for Gallagher issued cards
- `hf mfdes chk -f 1 -i 00112233 -d …
> Add Gallagher key checking/KDF on MIFARE Desfire

- CHANGELOG.md
- armsrc/Standalone/Makefile.hal
- armsrc/Standalone/Makefile.inc
- armsrc/Standalone/hf_tcprst.c
- armsrc/iso14443a.c
This standalone implements four different modes: reading, simulating, dumping, & emulating.
The initial mode is reading with LEDs A & D. 
In this mode, the Proxmark is looking for an ST25TA card like those used by the IKEA Rothult,
it will act as reader, and store the UID for simulation.
If the Proxmark gets an ST25TA UID, it will change to simulation mode (LEDs A & C) automatically.
During this mode the Proxmark will pretend to be the IKEA Rothult ST25TA master key, upon presentation
to an IKEA Rothult the Proxmark will steal the 16 byte Read Protection key used to authenticate to the card.
Once it gets the key, it will switch to dump mode (LEDs C & D) automatically. During this mode the Proxmark
will act as a reader once again, but now we know the Read Protection key to authenticate to …
> Create hf_tcprst standalone mode - IKEA Rothult

- client/src/cmdtrace.c
Noticed this earlier while debugging my standalone
> Fix missing hyphens on command examples

- client/src/cmdhfwaveshare.c
The 2.7-inch e-ink module's canvas is actually in portrait, trying to display a 276-wide by 176-tall bmp yields an image that's glitched in the way you'd expect for a canvas that's sideways.
Additionally I have tried one of the 1.54" 200x200 screens, and it seems to work perfectly (including tri-color).
> waveshare: fix dimensions of 2.7" screen, test 1.54" screen

- armsrc/mifarecmd.c
- client/src/mifare/mifarehost.c
This PR fixes the issue where hf mf csetuid always displays an old UID of 00 00 00 00.
Before:
(Ignore the print debugging)
After:
> Fix old UID display on hf mf csetuid

- .vscode/launch.json
- .vscode/tasks.json
**To get Client debugging working on ProxSpace**
1.	Have w working ProxSpace environment for Proxmark compilation
2.	Install Visual Studio Code
3.	Within ProxSpace run `git clone https://github.com/RfidResearchGroup/proxmark3.git`
**Your proxmark3 folder has to be in proxspace/pm3/ and cannot be in another directory, however the name of the proxmark3 does not matter.**
4.	Open your proxmark3 folder in Visual Studio Code
5.	Open .vscode/launch.json and change `"args": ["COM5"]` to your com port
6.	Select the “(gdb) Build & Launch” configuration Launch
**To get Client debugging working on WSL**
1.	Have a working WSL environment for Proxmark compilation
2.	Install Visual Studio Code
3.	Install the Visual Studio Code [Remote – WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode- …
> Visual Studio Code client debugging on Windows

- armsrc/iclass.c
- client/src/cmdhficlass.c
- doc/cheatsheet.md
hf iclass dump, restore, wrbl, & rdbl have been cliparserized.  Start block and end block commands now use `--first` and `--last` arguments and expect integers instead of 1 byte hex.  Blocks are now printed with decimal representation to match.
A new key index argument has been added when referencing keys in memory.
> hf iclass dump, restore, rdbl, wrbl cliparserization and argument normalization

- client/src/cmdhflto.c
- doc/cliparser_todo.md
The `hf lto` commands are now cliparserized and tested
> hf lto dump, restore, info, rdbl, wrbl - now use cliparser

- CHANGELOG.md
- armsrc/Standalone/hf_aveful.c
- armsrc/Standalone/hf_young.c
- armsrc/appmain.c
- armsrc/iso14443a.c
- armsrc/iso14443a.h
- client/src/cmdhf14a.c
- client/src/cmdhfmfu.c
Added `hf mfu sim t 7 n <numreads>` to allow the ultralight emulation to exit after `<numreads>` blocks. The approach was similar to the one that had been implemented for mifare classic tags.
> MFU emulation now supports automatic exit after <num> blocks read.

- client/src/proxgui.cpp
This PR shows this warning on macOS:
and this warning on non-MacOS (Linux, WSL etc):
if gui is not available (checked elsewhere in code by looking at DISPLAY environment variable for non-Windows. It's always available on Windows.).
> gui: Show a warning if user does not have GUI support

- armsrc/Makefile
- armsrc/appmain.c
- armsrc/em4x70.c
- armsrc/em4x70.h
- client/CMakeLists.txt
- client/Makefile
- client/src/cmdlf.c
- client/src/cmdlfem.c
- client/src/cmdlfem410x.c
- client/src/cmdlfem4x70.c
- client/src/cmdlfem4x70.h
- client/src/cmdparser.c
- client/src/cmdparser.h
- common_arm/Makefile.hal
- doc/commands.md
- include/em4x70.h
- include/pm3_cmd.h
Initially, I only have an em4170 variant used for car transponders.
Also known as the ID48 and possibly Magic II.
This first feature is to read the tag id and user memory 1 and 2.
> Initial commit for em4x70 support.

- include/protocols.h
- tools/mf_nonce_brute/protocol.h
The increment and decrement commands have their values mixed up - decrement is 0xC0 and increment is 0xC1. This is stated correctly in the comment of `include/protocols.h`, but there seems to have been a mistake when setting the constants. Although these constants are used in a few places, the only place it appears that this mix-up has an effect is in command annotations:
> Fix mistaken MIFARE increment and decrement constants

- CHANGELOG.md
- client/src/cmddata.c
- common/lfdemod.c
fix: `data rawdemod` parsing bug that prevented selection of psk2 modulation
Also rawdemod for psk was ignoring user-defined clock values (autodetection always took precedence).
> Rawdemod parsing fixes

- armsrc/appmain.c
- armsrc/em4x70.c
- armsrc/em4x70.h
- client/src/cmdlfem4x70.c
- client/src/cmdlfem4x70.h
- include/em4x70.h
- include/pm3_cmd.h
Support for unlocking a tag by providing the pin.
I had to rename the parity command-line switches, as I think 'p' makes more sense for the password/pin to unlock the tag.
> EM4x70 Unlock support

- client/src/cmdhf14a.c
- doc/commands.md
* Renamed to apdufind. Fuzzing is something different than this simple enumeration.
* Removed Le as parameter. This is just the maximum response bytes expected. Not much to find here with this simple tool.
* Sweep through all values, even if a start value was given (don't stop at 0).
* Changed sweep oder to INS->P1->P2->CLA. This way instructions are more quickly found.
* Show response data, if there are any (hex & ascii).
* Retry command with Le = 0x0100 (extended length APDU) if there was a length error return code.
* Improved the output with general information.
* Fixed bug: It's now possible to run the command without parameters.
> Reworked hf 14a apdufuzz (now apdufind).

- client/CMakeLists.txt
- client/Makefile
- client/src/cmdhf.c
- client/src/cmdhf14b.c
- client/src/cmdhf14b.h
- client/src/cmdhfemrtd.c
- client/src/cmdhfemrtd.h
This PR adds basic support for reading Electronic Machine Readable Travel Documents (ePassports, eIDs, Electronic Driver's Licenses etc, [anything with this logo](https://upload.wikimedia.org/wikipedia/commons/f/fb/EPassport_logo.svg)) and dumping them into files, with a command called `hf emrtd dump`.
These files can then be viewed either manually, or by using something like rfidiot's mrpkey (`python2 mrpkey.py -n /tmp/itsworkingquestionmark` etc).
The code currently supports Basic Access Control (BAC) which derives a key based on certain data in MRZ. Most if not all modern passports require BAC to read data from them. You will therefore need to supply your document number with `-n`, your date of birth in YYMMDD format with `-d` and your document's expiry date with `-e`. A feature to …
> eMRTD support 1/?

- armsrc/em4x70.c
Update receive function with the expected number of bits to receive.
Do not bother checking invalid pulse lengths in the receive function, we just need to return anyway.
> em4x70: Update receive function with expected bits to receive.

- armsrc/appmain.c
- armsrc/em4x70.c
- armsrc/em4x70.h
- client/src/cmdlfem4x70.c
- client/src/cmdlfem4x70.h
- include/em4x70.h
- include/pm3_cmd.h
Single function to write all 12 bytes of the crypt key.
Added real values in writekey/auth help text so people with blank tags can write a test key and test authentication.
> em4x70: Add write key convenience function. 

- client/src/cmdhf14b.c
- client/src/cmdhfemrtd.c
- client/src/cmdhfemrtd.h
This PR adds a basic `hf emrtd info` command that spits out some of the data from EF_DG1. I do plan on reading and printing data from other files in the future too, and maybe even eventually adding a GUI.
It also includes a fix to automatically pad document numbers by iceman, alongside some other small fixes.
---
This PR currently has the following features implemented (checklist is based on what I feel like would mean a feature complete implementation):
However, many of those changes are planned to be added in different PRs, and this specific PR is likely not going to get any further feature changes.
> eMRTD support 2/?

- client/src/preferences.c
As PR title says, the intended behavior, as discussed on discord, is for them to be on by default, but this wasn't the case on the code, so I fixed it.
> Show hints by default

- client/src/cmdhfemrtd.c
This PR adds support for dumping additional files from the card when doing `hf emrtd dump`, specifically:
- EF_DG2: Passport Image
- EF_DG5: Passport Image
- EF_SOD: PKCS#7 certificate
---
This PR currently has the following features implemented (checklist is based on what I feel like would mean a feature complete implementation):
However, many of those changes are planned to be added in different PRs, and this specific PR is likely not going to get any further feature changes.
> eMRTD support 3/?

- client/src/cmdhfemrtd.c
This PR adds EF_DG11 parsing to `hf emrtd info`, and fancy headers for files (with color, as the iceman tax):
The compat chart looks like this for EF_DG11:
I've also quickly gone over the code to make it possibly easier to read dumps from files. Wanted to push this out ASAP as doegox expressed interest in looking into that (and as I wanted to avoid merge conflicts), so this PR comes without any coverity fixes.
---
For more info on this PR series, see #1117
> hf emrtd info: EF_DG11 parsing + Rework to make it easier to write support to read external files

- client/src/cmdhfemrtd.c
This PR adds EF_DG12 parsing to `hf emrtd info`, and fixes coverity issues.
---
For more info on this PR series, see #1117
> hf emrtd info: EF_DG12 support + coverity fixes

- client/src/cmdhfemrtd.c
Fixes for several eMRTD related issues doegox pointed out, alongside some stuff I wanted to fix myself.
- JP2 images are now given the extension .jp2.
- EF_DG7 is now dumped.
- EF_DG11 now accounts for the inclusion of non-localized legal name (like on Hungarian passports).
- EF_DG11/EF_DG12 now accounts for binary full dates on Date of Issue and Date of Birth (like on Hungarian and French passports, and unlike Turkish ones).
- Names now have padding ("<") replaced with space (" "). I previously didn't notice this as I have one single first name.
> Various hf emrtd info fixes

- client/src/cmdhfemrtd.c
- Account for undocumented 5F85 tag on belgian passports
- Ignore tags with data len of 0 when parsing, as some belgian passports do that
---
More info at #1117
> Various eMRTD quirk fixes

- client/src/cmdlfem4x50.c
- changed reading of "uid" to "serial" in function detect_4x50_block since output is always „serial"
- lf em 4x50 info: complete data is displayed only via additional verbose option (-v)
> 4x50 serial

- client/src/cmdhfepa.c
- doc/cliparser_todo.txt
- doc/commands.md
hf epa commands now use cliparser.   Also `make style` for commands.md changes (includes some formatting and missing eMRTD  commands)
> hf epa - now use cliparser

- client/src/ui.c
(As seen on https://man7.org/linux/man-pages/man3/readline.3.html, stdio.h is supposed to be imported before readline.h.)
[Fixes CI](https://ci.appveyor.com/project/RfidResearchGroup/proxmark3/builds/36979009) and build issues that are faced after commit https://github.com/RfidResearchGroup/proxmark3/commit/7bc3067fa4ea05d176353314ee0d8f11b68fda33:
> ui: Load readline after stdio.h

- client/luascripts/hf_legic.lua
Lua's os.tmpname() doesn't work in MinGW, but since we need a random filename and not a file handle we can't make use of other functions that might work.  This just generates some pseudorandom uppercase/lowercase letters to append to the filename to make it random, as it will be immediately deleted after loading.
> hf_legic Lua - change method for temp file naming

- client/src/cmdhf14a.c
- doc/commands.md
(This helps if a tag might be locked permanently with a certain instruction. You can just skip it.)
> apdufind: added option to skip instrcutions.

- client/src/cmdhfemrtd.c
This PR splits EF_SOD into a new section and accounts for further cases such as file not being in EF_SOD, file being in EF_SOD but not actually being read.
This should conclude hash verifications for EF_SOD, hopefully... just need to do cert verifs one day.
> eMRTD info: Split EF_SOD into a new section, add further case handling

- client/src/cmdhfemrtd.c
- client/src/cmdhfemrtd.h
This PR adds support to supplying a path to dump stuff to. The directory needs to exist beforehand.
---
Poking #1117 as this was on checklist
> eMRTD dump: Allow specifying a custom dump directory

- client/src/cmdlfem410x.c
argument didn't match help text, user in discord pointed it out
> lf em 410x - textual

- client/src/cmdhf14a.c
- client/src/cmdhfemrtd.c
Hi,
proxmark does not compile on osx.
This PR solves the following issues:
```
[-] CC src/cmdhf14a.c
src/cmdhf14a.c:2222:34: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
uint64_t all_sw[256][256] = {0};
^
{}
1 error generated.
```
and 
```
[-] CC src/cmdhfemrtd.c
src/cmdhfemrtd.c:1780:39: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
uint8_t dg_hashes_sod[17][64] = { 0x00 };
^~~~
{   }
src/cmdhfemrtd.c:1781:40: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
uint8_t dg_hashes_calc[17][64] = { 0x00 };
^~~~
{   }
src/cmdhfemrtd.c:1859:39: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
uint8_t dg_hashes_sod[17][64] = { 0x00 };
^~~~
{   } …
```
> Fixed build errors on osx

- client/Makefile
Jansson libs/include dirs were taking preference over the included Lua files, causing system Lua files to interfere with expected includes and fail compilation on macOS if a locally incompatible Lua was available
> Reorder Lua libs/includes to compile on macOS

- CHANGELOG.md
- Makefile.defs
- client/CMakeLists.txt
- client/Makefile
- doc/md/Installation_Instructions/Mac-OS-X-Homebrew-Installation-Instructions.md
This PR adds support for compiling proxmark3 on Apple Silicon.  Homebrew has changed prefixes for certain dependencies and I've updated the doc to include information about Rosetta 2 which is needed for `arm-none-eabi-gcc`
> Add support for Apple Silicon (M1)

- armsrc/mifarecmd.c
This PR has two different, unrelated patches:
- First it fixes the nonce acquisition for MFC tags. Previously, the counter "i" was being incremented by the "continue" in case of errors, which resulted in empty, zeroed nonces being sent to the host.
- Second it replaces the error messages on the AcquireEncryptedNonces method so it's more clear which one is being called when an error pops up on the console.
> Nonce acquisition improvements

- client/src/ui.c
A very small bug that Address Sanitizer caught. This check inside the inner loop was using the outer's index variable.
> Fix out of bounds read

- client/src/cmdhfemrtd.c
This fixes a bug with hf emrtd dump not dumping jpg/jp2s properly.
> emrtd: Fix EF_DG2 image dumping

- client/src/cmdhfemrtd.c
When thinking about my eMRTD implementation I realized that I check document form factor in a rather unreliable way, and that I could just check the size of MRZ instead.
So, this PR introduces that, and adds support for another type of document.
> emrtd: Calculate document form factor from MRZ length

- CHANGELOG.md
- armsrc/Standalone/Makefile.hal
- armsrc/Standalone/Makefile.inc
- armsrc/Standalone/lf_tharexde.c
- doc/md/Use_of_Proxmark/4_Advanced-compilation-parameters.md
Added standalone mode for EM4x50 (lf_tharexde).
It simulates EM4x50 dumps, reads words transmitted by EM4x50 tags in standard read mode and stores them in internal flash.
On entering stand-alone mode, this module will start simulating EM4x50 data. Data is read from eml dump file uploaded to flash. If reader sends password different from dump file password, it is saved in file lf_em4x50_passwords.log.
On switching to read mode by pressing pm3 button, module will start reading EM4x50 data. Each collected data set will be written/appended to logfile in flash (lf_em4x50_collect.log) as a text string.
RDV4 hardware (for flash and battery) is required.
> em4x50 standalone mode (lf_tharexde)

- client/src/cmdhfjooki.c
- Extended the parameter list of `hf jooki encode` command with `-y` for figurine type id and `-f` for figurine id.
- Made changes to command codes
> Minor changes to hf jooki command

- client/src/cmdhfemrtd.c
As discussed with @doegox in dms, this fixes crashes when debug prints are enabled
> emrtd: fix segfaults when debug print is enabled

- pm3
Many users use pm3-flash-all when coming from builds that are based on the official firmware, but that does result in the device not showing up. 
This addition checks if the PNPDeviceID has the Iceman suffix. It might not be the best check, but it should help inexperienced users.
> Prevent Windows users from soft bricking their devices

- client/src/mifare/mifare4.c
It seems that the wrong offset is used to get the error code in the `hf mfp auth` printout. I've also added a call to the `mfpGetErrorDescription` function to make it clear why the error is occuring, if known.
Before:
After:
> Fix mfpauth error printout

- pm3
This is to help with COM ports that are created from Bluetooth devices.
> Windows prioritise USB connections

- CHANGELOG.md
- client/src/cmdhflist.c
The MFDES annotation function currently checks for DESELECT and WTX the wrong way around.
> Fix swapped DESELECT and WTX annotations

- CHANGELOG.md
- client/src/cmdhflist.c
The ISO 14443a annotation marks any data starting with `C2` as the RESTORE command, though this first byte is shared with the DESELECT S-block. The MFDES annotation function calls the ISO 14443a annotation function before applying its own annotations, and as it does not check the size of the command before labelling it as RESTORE, any DESELECT command is labelled as RESTORE(224) (treating the first CRC byte as the block parameter). I have modified the ISO 14443a annotation function to perform size checking.
Before:
After:
> Fix RESTORE annotation

- CHANGELOG.md
- client/src/cmdhflist.c
The DESFire annotation function currently iterates over the first two INF bytes to try and identify the command being used. If the first byte has a match, though, the second iteration still occurs. Thus, if both the first and second INF bytes correspond to valid DESFire command bytes, it is the second byte which final annotation will correspond to.
Example:
```
Rdr |02  5a  c0  00 00  fc  15                                               |  ok | CREATE CYCLIC RECORD FILE
```
The C0 byte is annotated rather than 5A, since they are both valid command bytes.
Post-fix:
```
Rdr |02  5a  c0  00 00  fc  15                                               |  ok | SELECT APPLICATION
```
> Fix DESFire mis-annotation

- client/Makefile
brew updates QT to QT6 and versions QT5 which we need to link for pkgconfig
Leaving the old qt directory for backwards/forwards compatibility
> Fix Makefile for QT5 on macOS

- README.md
PiSwords was types as pisworks
> Fix a typo in the PiSwords branding

- client/src/cmdhfemrtd.c
This PR fixes two issues with the emrtd logic.
20ca241 fixes a small bug introduced in 2a9d064fd6fb53b1f628fc7d319b3fa9edda6382 on the `emrtd_get_asn1_data_length` function where file lengths on longer files were incorrectly determined and as such failed to read properly:
---
a20f3af fixes a small bug introduced in 501b31cf453596023cb0a79ebf133810f48eb473 on the `emrtd_mrz_determine_length` function where certain fields (such as Legal Name, Document Number, Optional elements) had the last character cropped off.
("old, working" is before 501b31cf453596023cb0a79ebf133810f48eb473, "old, broken" is after 501b31cf453596023cb0a79ebf133810f48eb473, "new" is this current fix)
I also ack that there was a bug in the logic in `emrtd_mrz_determine_length` before …
> emrtd: Fix file reading and parsing

- client/src/cmdlfem4x50.c
fixed useless 0 == 0 comparison when checking for valid em4x50 data in dump file;
eload and restore functions should work again
> em4x50: fixed bug in eload and restore

- client/src/cmdlfem4x50.c
added newline (cliparser 4x50 sim)
> missing newline in 4x50 sim help text

- armsrc/Standalone/lf_tharexde.c
control character at end of 4x50 eml dump file could lead to wrong interpretation of file size
> fixed upload of eml files in 4x50 standalone mode

- client/src/proxmark3.c
On Windows SetConsoleMode has to be called every time the client launches to enable color support. If SetConsoleMode succeed during the initial start, `"os.supports.colors": true` will be put in prefs. However, it is not guaranteed that SetConsoleMode succeeds at a later point resulting in the client trying to show colors, but the terminal not supporting those.
Therefor on Windows `os.supports.colors` has to be checked every time the client launches.
> check for Windows color support each time

- client/src/proxmark3.c
Under Windows when resizing the cmd the buffer size will change which disables the color support. Windows will put a `WINDOW_BUFFER_SIZE_EVENT` into the input buffer for applications to handle this behavior, unfortunately readline will filter those events. 
As I’m not able to detect when the buffer is resized, I have to check if color support is still enabled. I do this after readline returns and before any text is printed.
> Windows ansi color fix

- client/src/cmdhfmfu.c
- client/src/cmdhfmfu.h
Add support for NXP [NTAG 210μ](https://www.nxp.com/products/rfid-nfc/nfc-hf/ntag-for-tags-labels/ntag-210-micro-nfc-forum-type-2-tag-basic-ic:NT2L1001_NT2H1001)
> Add support for NTAG 210μ

- client/src/cmdhfcipurse.c
- doc/commands.json
- doc/commands.md
now not needs to enter them each time
> added default parameters for `hf cipurse`

- CHANGELOG.md
- Makefile.defs
- README.md
- client/Makefile
- doc/md/Installation_Instructions/Mac-OS-X-MacPorts-Installation-Instructions.md
currently requires symlinking python{version}(-embed).pc to python(embed).pc or python3(-embed).pc under /opt/local/lib/pkgconfig for python linking
> add experimental support for macs with macports installed

- client/src/cmdhffelica.c
Sony provide [list of FeliCa products](https://www.sony.net/Products/felica/business/tech-support/list.html) with corresponding `IC Type` values. 
This PR adds ability to show _Model name of IC chip_ from given list into `hf felica info` command.
PS: Apparently there are more _IC Types_ out there then they are in this public list (e.g. in #442 somebody mentioned Suica (FeliCa standard (?) ) with type `0x0B` and some more are also in [nfcpy](https://github.com/nfcpy/nfcpy/blob/af5b13392f74a754fe4fa60f12463b7c392ffe8e/src/nfc/tag/tt3_sony.py#L60) code base). I did not include them because I am not sure about reliability of those informations. Or should I?
> Add FeliCa model name to felica info command

- client/src/mifare/desfirecore.c
Previous implementation didn't work for cards with single DF app.
> Fix DESfire DF search and assignment to AID

- client/src/cmdhfmfu.c
#1426 
it works now!
```
[usb] pm3 --> hf mfu dump -k bc77b6ed
[+] TYPE: NTAG 213 144bytes (NT2H1311G0DU)  
[+] Reading tag memory...
[=] Start to read from page 0. Total: 45 KeyType: 2
[#] UsePwd
[=] MFU dump file information
[=] -------------------------------------------------------------
[=]       Version | 00 53 04 02 01 00 0F 03 
[=]         TBD 0 | 00 00 
[=]         TBD 1 | 00 
[=]     Signature | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[=]     Counter 0 | 00 00 00 
[=]     Tearing 0 | 00 
[=]     Counter 1 | 00 00 00 
[=]     Tearing 1 | 00 
[=]     Counter 2 | 00 00 00 
[=]     Tearing 2 | 00 
[=] Max data page | 43 (176 bytes)
[=]   Header size | 56
[=] -------------------------------------------------------------
[=] …
```
> bugfix: hf mfu dump not working

- armsrc/Standalone/hf_14asniff.c
- client/src/cmdflashmemspiffs.c
```
[usb] pm3 --> mem spiff dump -s hf_14asniff.trace -d hf_14asniff.bin
[=] downloading 1390 bytes from `hf_14asniff.trace` (spiffs)
[+] saved 1390 bytes to binary file hf_14asniff-5.bin
[usb] pm3 --> mem spiff dump -s hf_14asniff.trace -d hf_14asniffwefawe
[=] downloading 1390 bytes from `hf_14asniff.trace` (spiffs)
[+] saved 1390 bytes to binary file hf_14asniffwefawe.bin
[usb] pm3 --> mem spiff dump -s hf_14asniff.trace -d hf_14asniffwefawe
[=] downloading 1390 bytes from `hf_14asniff.trace` (spiffs)
[+] saved 1390 bytes to binary file hf_14asniffwefawe-1.bin
[usb] pm3 --> mem spiff dump -s hf_14asniff.trace -d hf_14asniff.bin1
[=] downloading 1390 bytes from `hf_14asniff.trace` (spiffs)
[+] saved 1390 bytes to binary file hf_14asniff.bin1
[usb] pm3 --> mem spiff dump -s …
```
> fix naming convertion messes up

- client/src/cmdtrace.c
Fixes  #1467 
Setting g_trace to NULL after free
to fix double free error
Before:
```
[fpc] pm3 --> hf 14a sniff
[#] Starting to sniff. Press PM3 Button to stop.
[fpc] pm3 --> trace list -t 14a
[=] downloading tracelog data from device
[=] Waiting for a response from the Proxmark3...
[=] You can cancel this operation by pressing the pm3 button
[-] ⛔ Timed out while trying to download data from device
[!] ⚠️  timeout while waiting for reply.
[+] Recorded activity (trace len = 0 bytes)
[fpc] pm3 --> 
[fpc] pm3 --> 
[fpc] pm3 --> trace list -t 14a
=================================================================
==30448==ERROR: AddressSanitizer: attempting double-free on 0x615000031400 in thread T4 (WorkerThread):
#0 0x7f0380ae68f7 in __interceptor_free …
```
> Fix double free error #1467

- armsrc/iso14443a.c
two 14a card
execute `hf 14a info`
```
[usb] pm3 --> hf 14a info
[#] Multiple tags detected. Collision after Bit 1
[#] BCC0 incorrect, got 0x00, expected 0xdf
[#] Aborting
```
in fact, the bcc is correct
```
[usb] pm3 --> trace list -t 14a
[=] downloading tracelog data from device
[+] Recorded activity (trace len = 72 bytes)
[=] start = start of start frame end = end of frame. src = source of transfer
[=] ISO14443A - all times are in carrier periods (1/13.56MHz)
Start |        End | Src | Data (! denotes parity error)                                           | CRC | Annotation
------------+------------+-----+-------------------------------------------------------------------------+-----+--------------------
0 |        992 | Rdr |52(7) …
```
> fix bcc incorrect

- client/src/nfc/ndef.c
```
[usb] pm3 --> nfc decode -d DA2010016170706C69636174696F6E2F766E642E626C7565746F6F74682E65702E6F6F62301000649201B96DFB0709466C65782032
[=] --- NDEF parsing ----------------
[=] Trying to parse NDEF records w/o NDEF header
[+] Record 1
[=] -----------------------------------------------------
[=] Header info
[+]   1 ....... Message begin
[+]    1 ...... Message end
[+]     0 ..... Chunk flag
[+]      1 .... Short record bit
[+]       1 ... ID Len present
[+] 
[+]  Header length...... 4
[+]  Type length........ 32
[+]  Payload length..... 16
[+]  ID length.......... 1
[+]  Record length...... 53
[+]  Type name format... [ 0x02 ] MIME Media Record
[=] 
[=] Payload info
[=] Type data
[=]     00: 61 70 70 6C 69 63 61 74 69 6F 6E 2F 76 6E 64 2E | application/vnd.
[=]     10: 62 6C 75 65 74 …
```
> fix dynamic-stack-buffer-overflow

- CHANGELOG.md
- client/src/cmdlfpac.c
The parity bit needs to be discarded when calculating the final
checksum byte value of PAC/Stanley card IDs. Verified by scanning
a tag which is now correctly identified.
> Fix PAC/Stanley checksum calculation

- pm3
There is a bug in the current pm3 script that will not prioritise USB connections. It has to do with skipping the usb part if there was a bt port detected. 
@Iceman1001 did add the comment `Need to look for this first, the call to Win32_serialport "crashes" then native bt serial port. Don't ask why.`. Since then, there where some changes to the queries and I can not replicate that issue. 
Thanks to @craftbyte for bringing this issue to my attention and help me fix it.
> Windows: fixed usb prioritization

- CHANGELOG.md
- armsrc/lfops.c
Fixed the issue where SimulateTagLowFrequencyEx in some cases was controlling the LEDs even if ledcontrol argument was set to false.
> Fixed ledcontrol in SimulateTagLowFrequencyEx

- armsrc/felica.c
the sync bytes should not be included in the crc calculation
(and the crc bytes should be placed at the end of the response buffers)
> armsrc/felica: fix crc offsets in felica_sim_lite

- armsrc/Standalone/hf_craftbyte.c
Hello,
As commented:
https://github.com/RfidResearchGroup/proxmark3/issues/1543
I fixed emulation card type in hf_craftbyte.c . The original code  isn't checking the tag type when the UID is emulated.
Regards.
> fix hf_craftbyte.c emulation card types

- CHANGELOG.md
- client/CMakeLists.txt
- client/Makefile
- client/src/cmdhf.c
- client/src/cmdhfksx6924.c
- client/src/cmdhfksx6924.h
- client/src/ksx6924/ksx6924core.c
- client/src/ksx6924/ksx6924core.h
The original code is from micolous. (https://github.com/micolous) - Thank you!
It has been slightly modified to work in the current proxmark3.
South Korea's T-money card balance inquiry and basic information inquiry will work.
Below are the test results:
[usb] pm3 --> hf ksx6924 balance
[+] Current balance: 48050 won/cents
[usb] pm3 --> hf ksx6924 info
cardType .............................. 00 (Pre-paid)
alg (encryption algorithm) ............ 10 (3DES)
vk (keyset version) ................... 01
idCenter (issuer ID) .................. 08 (Korea Smart Card Corporation)
csn (card number) ..................... 1019************ --> masked
idtr (card usage authentication ID) ... 5343***** --> masked
issueDate ............................. 2019-12-10
expiryDate ............................ …
> For testing KS X 6924 (South Korea's T-money card)

- doc/md/Installation_Instructions/Linux-Installation-Instructions.md
`pacman -Sy` can result in partial upgrades and system damage if the user doesn't understand what it entails and never finishes the upgrade.
See: https://bbs.archlinux.org/viewtopic.php?id=241092
> Use pacman -Syu instead of pacman -Sy

- CHANGELOG.md
- client/src/cmdhfmfdes.c
MIFARE DESFire cards can be configured with `CMK required for create/delete : NO`, allowing anyone to create an application without key knowledge. However, the `hf mfdes createapp` expects a key for all operations. This patch adds support for `--no-auth` to skip authentication.
```
[usb] pm3 --> hf mfdes createapp --aid 000003 -v --no-auth --dstalgo AES
[=] Key num: 0 Key algo: des Key[8]: 00 00 00 00 00 00 00 00
[=] Secure channel: n/a Command set: niso Communication mode: mac
[=] Anticollision ok
[=] ---------------------------
[=] Creating Application using:
[=] AID          0x000003
[=] Key Set 1    0x0F
[=] Key Set 2    0x8E
[=] ISO file ID  disabled
[+] Application level rights:
[+] -- AMK authentication is necessary to change any key (default)
[+] [1...] AMK Configuration …
```
> Add --no-auth support for hf mfdes createapp

- client/include/pm3.h
- client/src/cmdmain.c
- client/src/cmdmain.h
- client/src/comms.c
- client/src/comms.h
- client/src/pm3.c
If these are `const char` it makes it every so slightly easier when playing around with Swift integration.  I'm sure Swift integration shouldn't be one the strong motivations in the project, but if it doesn't hurt anything, I figure why not?
> Be more CONSTant with the parameters we will not modify

- client/src/wiegand_formats.c
Adds from comment for PCSC 37Bit to match the other comments format. Adds uniformity to comments
> Add from comment

- client/src/util.c
Already included in a `#ifndef _WIN32` on L51
> remove redundant include

- .github/workflows/macos.yml
- tools/mfd_aes_brute/Makefile
- tools/mfd_aes_brute/mfd_aes_brute.c
unistd.h in macos has this snippet:
```c
#if __DARWIN_C_LEVEL >= __DARWIN_C_FULL
#define _SC_NPROCESSORS_CONF            57
#define _SC_NPROCESSORS_ONLN            58
#endif /* __DARWIN_C_LEVEL >= __DARWIN_C_FULL */
```
`__DARWIN_C_FULL` is `900000L`.
If `__POSIX_C_SOURCE` gets defined without `__DARWIN_C_SOURCE` being defined, `__DARWIN_C_LEVEL` will be assigned to `__DARWIN_C_ANSI`, which is `010000L`.
Thus this definition will remove `_SC_NPROCESSORS_CONF`.
If we don't define `__POSIX_C_SOURCE`, `__DARWIN_C_LEVEL` will be equal to `__DARWIN_C_FULL`, and `_SC_NPROCESSORS_CONF` will be available.
This commit also includes homebrew and macports prefix definitions for mfd_aes_brute.
Signed-off-by: İlteriş Yağıztegin Eroğlu <ilteris@asenkron.com.tr>
> fix macos builds by not defining _POSIX_C_SOURCE in mfd_aes_brute.c if macos

- client/src/util_darwin.m
Another tweak on the road to swift support.  When compiling with xcodebuilt or swift, the `__has_feature(objc_arc)` being enabled cause it to throw errors with the `retain` and `release`.  ARC (automatic reference counting) makes them unnecessary.
> ARC support for AppNap toggle

- CHANGELOG.md
- client/luascripts/hf_mf_uidbruteforce.lua
- Better interpretation of 4 or 7 bytes UID in UID bruteforcer
- Add Mifare Classic 4K in UID bruteforcer
- Fix help menu in UID bruteforcer
> Enhance hf mf uidbruteforces (UID length, HF MF 4K, help)

- client/src/cmdhfmfdes.c
Was tempted to make a `major` mask with 0x0f == 1,2,3,... but...
> Fix support for more Mifare Desfire EV2 cards

- doc/termux_notes.md
Remove "tested setups". This seems extraneous, it should work on almost all recent Android hw+sw
Direct users to F-Droid for Termux
Use correct directory after cloning
> Update instructions for Termux

- armsrc/Standalone/Makefile.hal
- armsrc/Standalone/hf_15sniff.c
Make HF_15SNIFF standalone mode compatible with old PM3 (without flashmem)
> Make HF_15SNIFF standalone mode compatible with old PM3 (without flashmem)

- CHANGELOG.md
- client/luascripts/hf_14a_i2crevive.lua
added to changelog and changed the name of hf_i2c_recovery to hf_14a_i2crevive to denote its a 14a script :)
> Update changelog & rename hf_i2c_recovery.lua

- CHANGELOG.md
- tools/mkversion.sh
This avoids inconsistencies as can be seen between macOS and Windows platforms in how they hash the sources for the firmware mismatch checks.
Fixes done here:
- Use `sort` command to ensure filenames are sorted (not every OS sorts the files the same)
- Use `-t` argument to `sha256sum` to force hashing files in text mode, some OS (Windows) hash the .c and .h as by mistake by default
FWIW, this new hashing seems to produce the same hashes on macOS (and likely Linux), therefor I assume Windows is the odd one out here
> Sort filenames before hashing and force hashing in text mode

- CHANGELOG.md
- tools/mfd_aes_brute/Makefile
`mfd_aes_brute` was throwing a compilation error first because of using `-march=native` which does not exist on M1 Macs (yet), so I swapped that over to `-mcpu=native` conditionally.
Secondly, it did not have a method for checking AES-NI state on those machines either (the fallback being Linux only).
For now hardcoded to false, as M1 CPUs do not support AES-NI (and the check function was only used for display purposes in the first place)
> Fix compilation on M1 Macs

- CHANGELOG.md
- client/deps/hardnested/hardnested_bf_core.c
ARMv8 always ships with NEON capabilities supporting 128-bit operations.
This gives ~ +50% speedup on hardnested on Apple M1
> Minimal change to utilize ARM NEON capabilities

- client/src/comms.c
E.g. before this fix, iso15 (and others using the same way from ARM to client) raw commands expecting results but with no answer from the tag where showing the previously received commands instead of : "[!] /!\ command failed".
BEFORE:
[usb] pm3 --> hf 15 raw -c -d 260100
[+] received 12 octets
[+] 00 02 05 43 20 0B 66 24 16 E0 6C 56 
[usb] pm3 --> hf 15 raw -c -d 010203 # invalid command (tag is not answering)
[+] received 12 octets
[+] 00 02 05 43 20 0B 66 24 16 E0 6C 56
AFTER:
[usb] pm3 --> hf 15 raw -c -d 260100
[+] received 12 octets
[+] 00 02 05 43 20 0B 66 24 16 E0 6C 56 
[usb] pm3 --> hf 15 raw -c -d 010203 # invalid command (tag is not answering)
[!] ⚠️  command failed
> Fix USB communications when receiving empty frames

- CHANGELOG.md
- client/src/cmdlf.c
When executing "lf config --reset", the averaging will be 0 rather than 1(default).
This is because the config.averaging is set to 1 at first.(line 621)
Then this argument is overwritten unconditionally by
"config.averaging = (avg == 1);"(line 634)
> Fix a bug in "lf config"

- README.md
- doc/ndef_type4a.md
This is a starting document to store ndef type4a notes.
It is hoped that others will add and build on this.
Initial contents is focused on setting up the NDEF type 4a records on a desfire ev1 (or later) card.
> Ndef notes

- client/src/util.c
Tested with previously broken `data diff` command. Working now.
> Fix wrong length calcuation in *_to_buffer utilities

- armsrc/iso14443a.c
Replaced RF reset with an s-block deselect as suggested [in previous pr](https://github.com/RfidResearchGroup/proxmark3/pull/1696).
> Update to 'hf 14a reader --ecp'

- CHANGELOG.md
- client/src/cmdlft55xx.c
the most confusing command. 
OR read with a password
OR write without
it has the same length 38 bits
if the token is with a password - all is OK, 
if not - read command with a password will lead to writing the shifted password to the memory and:
**IF the most bit of the data (the password from the read command) is `1` ----> IT LEADS TO LOCK this block of the memory**
> decode password in case of the read/write comand

- CHANGELOG.md
- client/src/cmdhfgallagher.c
- common/generator.c
Adds a new `hf gallagher decode` command that decodes the Gallagher credential block.
Also tweaked the output format where the region code is shown to display it as an uppercase letter A-P in addition to the existing numeric display as this is how the region code is formatted in Gallagher software.
Finally there is a super simple one like fix to the Gallagher KDF algorithm to allow it to correctly generate diversified keys for the card master key -> The CSN was incorrectly being included in the KDF input when it shouldn't have been as per https://github.com/megabug/gallagher-research/blob/master/formats/card-specific/mifare-desfire.md#card-application as well as my own testing with Gallagher encoded cards.
> Add hf gallagher decode command and other minor Gallagher tweaks

- client/src/cmdhficlass.c
Fixes some bugs in the SIO detection and printing. Initially noticed when astyle reformatted some of the code I noticed the use of substr() on binary data containing 0x00's which substr will stop on, as well as incorrectly assuming the return of byte_substr will be 0 instead of -1 on a failed match, added some bounds checking, and simplified some of the code to reduce duplication.
The practical differences between the new and old code is the old code is more prone to false positives (matching on a single 0x05 character instead of the full 0x05, 0x00, 0x05, 0x00 sequence to identify SIO), as well as some potential undefined behaviour if sufficiently short dump files were loaded (I notice json files seem to allocate a fixed size buffer so these wouldn't have been too bad, but other formats …
> Fix some bugs in the iClass SIO detection and printing

- CHANGELOG.md
- client/src/cmdhficlass.c
Fixed incorrect card config bit being checked for iClass key access flag. Fixes `hf iclass view` and `hf iclass info` command output. The bit now matches what the PicoPass datasheet describes, as well as matching practical experience testing iClass cards in the wild.
Split from #1724
> Fixed incorrect card config bit being checked for iClass key access flag

- CHANGELOG.md
- client/src/cmdhficlass.c
- client/src/cmdhflist.c
Changed `hf iclass list` to display matched keys on the CHECK command rather than the card response
This is useful as it shows what key a reader attempted to use with a card even if the card rejected the key. To make it more apparent when the CHECK command was successful though it now shows `CHECK SUCCESS` in green when the card responds to the CHECK command, and the key is not printed in green anymore since we don't know at that point if the key actually worked or not.
Also made `hf iclass list` key check lookup using the elite algorithm too
The display currently doesn't show any different output for elite vs standard kdf since there's fairly limited room, but I'd expect people would know what sort of keys they've loaded in, and worse case could double check with `hf iclass chk`
Split …
> Changed `hf iclass list` to display matched keys on the CHECK command

- CHANGELOG.md
- client/src/cmdhficlass.c
- client/src/cmdhficlass.h
- client/src/preferences.c
- client/src/ui.h
iClass dump views (ie, `hf iclass view`) now suppress repeated blocks, similar to how hexdump works. It will only suppress blocks in the application area, and will never suppress detected iclass credential blocks. For example a dump that has blocks 17-236 all containing just FF's:
```
<blocks 16 and prior output unchanged>
[=]  17/0x11 | FF FF FF FF FF FF FF FF | ........ |   | User
[=] *
[=] 236/0xEC | FF FF FF FF FF FF FF FF | ........ |   | User
```
Needless to say this is quite handy when dealing with complete card dumps when the AA2 area is blank.
Split from #1724
> Changed `hf iclass view` to suppress consecutive blocks with repeated contents

- CHANGELOG.md
- client/src/cmdhflist.c
Parameters like appId, fileNo, etc are now shown in the `hf mfdes list` annotation column where available (and where I knew the details). Previously only keyNo on AUTH commands were shown.
> Added more details to the annotations of `hf mfdes list` output

- client/luascripts/hf_mfu_amiibo_sim.lua
Works well enough on my Nintendo Switch!
This is a second attempt at https://github.com/RfidResearchGroup/proxmark3/pull/1732
> add hf_mfu_amiibo_sim to simulate Amiibo binary dumps

- Makefile.defs
- client/Makefile
I noticed that Qt5 and Python pkg-config detection was not working when running `brew install proxmark3 --HEAD --with-generic` on my MacOS Ventura system.
If I built without homebrew then my system's Qt5 and Python3.9 were detected fine.
Here are a couple of fixes to get the brew recipe working.
1. It looks like HOMEBREW_PREFIX is set by the `brew` recipe, so we can set proxmark3's internal BREW_PREFIX from that instead. 
2. Change PKG_CONFIG_PATH a concatenated list of paths to include Qt, and the main homebrew pkgconfig path in `$(HOMEBREW_PREFIX)/lib/pkgconfig`
3. Use `PKG_CONFIG_ENV` when outputting the Python version
Depends on https://github.com/RfidResearchGroup/homebrew-proxmark3/pull/35
Before:
```
===================================================================
Version info: …
```
> fix homebrew dependency detection

- client/Makefile
On MacOS Ventura, if I build proxmark3 locally then the client Makefile has a hard time finding the Qt version.  It assumes `qmake` is in the path, which seems to be only the case when running from the brew recipe.
Since there's already code to determine the paths of `uic` and `moc`, then let's just throw `qmake` into there as well!
Before:
```
===================================================================
Version info:      Iceman/master/v4.14831-842-g6fb4723cd
Client platform:   Darwin
GUI support:       QT5 found, enabled ()
native BT support: skipped
Jansson library:   system library found
Lua library:       system library not found, using local library
Python3 library:   Python3 v3.9 found, enabled
Readline library:  enabled
Whereami library:  system library not found, using …
```
> determine qmake path similar to uic/moc

- client/src/cmdhfemrtd.c
- client/src/cmdhfemrtd.h
- client/src/proxgui.cpp
- client/src/proxgui.h
- client/src/proxguiqt.cpp
- client/src/proxguiqt.h
I was playing around with my Canadian passport and `hf emrtd info`.  I noticed there was Qt code to show pictures, but the code path wasn't being taken.
Here I add a `-i` / `--images` parameter to ignore the `fast` flag in the `dg_table`.
Qt's QImageReader is fairly smart so it'll know if any image is unsupported and constructs a null QImage if the data is an unknown format.  In my case, JP2 is supported, so the code to short-circuit the picture viewer is removed.
The temporary file creation/sleep code is also removed in favour of loading the image straight from the buffers passed to `emrtd_print_ef_dg2_info` and `emrtd_print_ef_dg5_info`.
> add -i to hf emrtd info

- client/luascripts/hf_mfu_amiibo_restore.lua
Learning the code every day :smile:
The previous code worked when building and running out of the source directory, but failed when brew installed.
> use core.search_file when searching for amiibo resources

- client/src/cmdhftexkom.c
I builded latest commit for termux, but I got an 
```
ld: error: undefined symbol: TexcomTK17Get2Bits
>>> referenced by cmdhftexkom.c:354 (src/cmdhftexkom.c:354)
>>>               obj/cmdhftexkom.o:(TexcomTK17Decode)
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```
so I fixed
> Fix undefined symbol when build with clang

- common/generator.c
Admin Cards (also called Reader Config Cards in some places) use slightly different KDF rules.
Verified functionality against a real system.
> Fix gallagher KDF generation for Admin Cards aka Reader Config Cards

- doc/md/Installation_Instructions/Mac-OS-X-Homebrew-Installation-Instructions.md
Add a note for macOS Ventura users on how to install with Xcode 14.0, notably that you need to rename Xcode-beta.app to Xcode.app in order for installation to succeed.
Installation succeeded on macOS Ventura Beta 4 using method described.
> Add installation guide for macOS Ventura Beta users

- client/resources/aidlist.json
- client/src/cmdhflist.c
This PR includes 2 commits:
1) Improve annotations:
ECP2 payload can have varying length, if it didn't match the frame was not annotated, this is fixed now.
Reader type is now added to annotation if it is known.
2) Add AIDs used by mobile-first applets:
Note that some of them might not appear when testing via `hf 14a info --aidsearch`  because the device bails-out after a dozen of failed SELECTs. I've decided to add them for public knowledge nonetheless.
> Improve ECP annotation, add mobile AIDs

- Makefile.defs
- Makefile.host
- client/Makefile
All the uses of LD actually wanted g++, so just use CXX and remove an
unused LD define
Closes: https://github.com/pentoo/pentoo-overlay/issues/1259
Fixes: https://github.com/RfidResearchGroup/proxmark3/pull/1758
> do not use LD if you aren't using ld

- CHANGELOG.md
- armsrc/appmain.c
- armsrc/flashmem.c
- armsrc/spiffs.c
- armsrc/spiffs.h
- client/src/comms.c
- added spiffs check after flase wipe to force it to update its status
- added spiffs write and append to write in 8192 byte chunks to allow spiffs space to be freed in time.
- fixed spiffs dump to correctly handle issues if it could not allocate bugbuff space.
> Prep spiffs for bigger data files

- README.md
User (Genoff) spotted the discord link doesnt work anymore, added a new invite link: https://discord.gg/xEvexdKmpF
Signed-off-by: Andrew MacPherson <andrew@andrewmohawk.com>
> Updated discord invite link

- client/dictionaries/t55xx_default_pwds.dic
Removed 1 whitespace, grouped some keys, uppercased keys and moved line comments to above the keys. Duplicate checked after and all is good, just another little spring clean (wasn't much I'll admit that)
> Clean up of t55xx_default_pwds

- CHANGELOG.md
- client/src/cmdhf14b.c
- client/src/cmdhf14b.h
`print_sr_dump()` assumes uid is at begining of dump. This is not true for SRT512 tags (the uid is not stored anywhere in the data, it is obtained b sending `Get_UID()` to the chip), and this PR is an attempt to fix this.  
The UID is used to guess the chip type, and interpret the system block. A wong guess of the chip ID results in an inaccurate display of which blocks are write protected.
This fix adds and `uid` parameter to `print_sr_blocks()`, and provides it to the call if we are dumping a tag. If we are reading a dump file, it attempts to extract the uid from the file name, assuming uid has a len of 8 bytes, and the file has the standard format of `hf-14b-xxxxx.*`
This works for my limited test case (one SRT512 tag). If extracting the uid from the data works for some cases then this …
> print_sr_blocks(): don't assume uid is at begining of dump

- client/src/cmdhfmf.c
In configurations where keyA is unknown but ACLs are configured to allow all blocks to be read by keyB the command `hf mf dump` was failing. This commit attempts to fix this behavior by trying keyA first and swapping for keyB if half of the allowed tries failed.
> Modified logic to also try key B on MF cards.

- client/src/cmdhfmf.c
- client/src/mifare/mad.c
- client/src/mifare/mifare4.c
Parts of the code returned positive values for error codes, which could result in the client exiting (return value 2).
> Fix prolematic return codes in mifare.

- client/src/cmdhf14a.c
- client/src/cmdhfmfu.c
`hf mfu sim -t 7` or `hf 14a sim -t 7`  without any other option was stopping after 7 reads, the proposed fix coreects that.
Also added a hint in the help text for Mifare Ultralight EV1 to type 7.
> Hf 14a sim : fix parsing error and add hint for ultralight EV1

- CHANGELOG.md
- client/src/cmdhfmf.c
- client/src/cmdhfmfu.c
- client/src/pm3line_vocabulory.h
- doc/commands.json
- doc/commands.md
Adds `hf mfu esave` command, to dump emulator memory into a mfu dump file.
Also changes `hf mfu eview` so that by default only the pages corresponding to the card size are shown.
> Add hf mfu esave

- CHANGELOG.md
- armsrc/mifarecmd.c
- client/luascripts/hf_mf_ultimatecard.lua
- client/src/mifare/mifarehost.c
- doc/magic_cards_notes.md
- include/protocols.h
Adds identification of magic gen4 GTU cards, using the dump configuration command. Card will only be detected if the password is default (00000000).
Added symbolic names for magic gen4 gtu protocol in `protocols.h` and changed src to use them.
Also changed the mifare classic wipe function in `hf_mf_ultimatecard.lua`  to erase the whole 4K memory and add all sector trailers.
> Add Magic Gen4 GTU detection

- doc/termux_notes.md
- Updated requirements list to use links and ensure Bluetooth only requirements are clearly marked
- Update links to Termux to point to F-Droid
- Include link to F-Droid
- Include reason why F-Droid Termux is recommended
> Update Termux notes to recommend F-Droid

- CHANGELOG.md
- client/src/cmdtrace.c
Fix `trace list -r` (relative times) not working unless the `-u` (micoseconds) flag was also provided.
Also makes the `--frame` option respect microseconds and relative times as well.
> Fix `trace list -r` (relative times)

- CHANGELOG.md
- client/src/cmdlfhitag.c
I decided to try and understand some of the simpler hitag commands and this one looked like the simplest non working one. The command as written in the client didn't seem to be sending any commands. Hopefully I've understood it correctly and not broken anything.
**Example usage**
```
[usb] pm3 --> lf hitag dump -h
Read all card memory and save to fileIn password mode the default key is 4D494B52 (MIKR)                                                                  
In crypto mode the default key is 4F4E4D494B52 (ONMIKR)  format: ISK high + ISK low.                                                                      
usage:
lf hitag dump [-h] [-f <fn>] [-k <hex>] [--nrar <hex>]
options:
-h, --help                     This help
-f, --file <fn>                specify file name
-k, --key …
```
> Get the hitag2 dump command working as per docs

- client/src/cmdsmartcard.c
- client/src/cmdsmartcard.h
- Fixing overflow in BigBuffer if requesting to much data
- Fixing integer wrapping with the SIM module by capping APDU data length
- Fixing chaining logic which was loosing previously received data
> Fixing some ISO7816-4 logic.

- armsrc/i2c.c
- client/src/cmdsmartcard.c
Sadly I did the maths wrong: when asking 256 bytes APDU data, it creates a buffer of 261 bytes. Off-by-one. Putting 270 for the peace of mind.
Tested against PIV with big objects and it works nicely.
> Buffer size too conservative

- armsrc/i2c.c
For the max 256-byte frame, SIM wasn't ready early enough, corrupting the reception buffer with 5 spurious bytes.
Empirically, 109 clock cycles is the minimum value that worked. Adding 1 clock cycle as a safety buffer.
> Wait a bit longer for the smartcard.

- CHANGELOG.md
- Makefile
Fixes #1795
Fedora doesn't allow the use of `adduser` to add users to groups. Instead, `usermod -aG` should be used, like in Arch, but with the dialout group instead of uucp.
As a brief discussion item before merge, should non-Arch distros just use `usermod` instead of `adduser`? This should work in general, and would get rid of the extra conditional. However, doing the testing for this might be difficult.
> Fix `make accessrights` for Fedora

- CHANGELOG.md
- armsrc/Standalone/hf_iceclass.c
- armsrc/iclass.c
- armsrc/iclass.h
- armsrc/iso15693.c
- armsrc/iso15693.h
- client/src/cmdhf.c
- client/src/cmdhficlass.c
- client/src/cmdhficlass.h
- include/iclass_cmd.h
Add `--shallow` option to `hf iclass` reader commands to do shallow (ASK) reader modulation instead of OOK.
ISO 15693 requires cards to support both OOK and 10% modulation index ASK. iClass/Picopass cards surprisingly also support this too. Older iClass readers and newer OmniKeys (eg Gen2) readers use ASK, while newer iClass readers (iClass SE branded stuff and Signo) ad older OmniKeys (eg Gen1) do OOK.
Having the ability to quickly switch between OOK and ASK is handy when developing card emulator tools when you want to ensure both modes are working as expected.
In the future adding the `--shallow` option ot `hf 15` commands would be handy too, but just starting with the `hf iclass` commands for the moment.
> Add iclass reader ASK support

- client/src/emv/tlv.c
- client/src/emv/tlv.h
First stage here is to introduce a new API that doesn't leak memory for TLV parsing which will be used for PIV.
Once PIV is merged, I'll make a PR to move EMV code to the new API and deprecate `tlvdb_parse()` and `tlvdb_parse_multi()`
> Initial rework on TLV to avoid mem leaks

- CHANGELOG.md
- client/src/cmdpiv.c
The command iterates through all known containers and tries to read them.
If data is returned, it's printed.
If not, the error code tells wether the containers doesn't exist or if security conditions are not met (e.g. PIN code is required or container is only available on 1 interface and not the other).
> Add `piv scan` command

- armsrc/Makefile
- bootrom/Makefile
Update armsrc and bootrom Makefiles with a .FORCE PHONY target for version_pm3.c
This fixes issues in ProxSpace where the firmware .elf files are sometimes not rebuilt (ie, when only the client src changes, leading to firmware/client mismatch warnings).
Note this is just copying the pattern used in client/Makefile to {armsrc,recovery}/Makefile.
> Update armsrc and bootrom Makefiles to ensure the version always updates.

- armsrc/optimized_cipherutils.h
- client/src/loclass/cipherutils.h
`BitstreamOut_t` in `client/src/loclass/cipherutils.h` is also used in `client/src/cmddata.c` for  down-sampling. 
However, the max number of `numbits` and `position` is 255(limited by uint8_t), which is too small. So I changed the type from uint8_t to uint32_t, keeping the struct the same with the one in `armsrc/lfsampling.h`
> Fix the types of parameters in BitstreamOut_t

- client/src/cmdsmartcard.c
When using the `smart info` command it printed _ISO7618_ instead of _ISO7816_.
> Fix typo in smart info

- client/src/cmdhfmf.c
Similarly to https://github.com/flipperdevices/flipperzero-firmware/pull/2296 there is an issue when dumping cards that have one block unreadable within the sector. While in case of the flipper, it was just authenticating once, here the for loop over the blocks within a sector will break, meaning the other blocks do not get read. Here's the log from the dump:
```
[=] Reading sector access bits...
[=] .................
[+] Finished reading sector access bits
[=] Dumping all blocks from card...
[...]
[+] successfully read block  0 of sector  3.
[+] successfully read block  1 of sector  3.
[+] successfully read block  2 of sector  3.
[+] successfully read block  3 of sector  3.
[+] successfully read block  0 of sector  4.
[+] successfully read block  1 of sector  4.
[!] ⚠️  access rights do …
```
> Fix mifare classic dump when block cannot be read

- CHANGELOG.md
- client/src/cmdhf15.c
Adds support to specifically detect NTAG 5 devices and updates hf 15 info command to performs EAS status checks on other icode tags which support EAS (SLI, SLIX, SLIX-L, and SLIX-S)
> Detect NTAG 5 devices and perform EAS status checks on other icode tags which support it

- client/src/util.c
Fixed more than necessary (e.g. the buffers immediately followed by memset) but that makes sure the pattern is consistent across the file and could prevent bugs from reappearing should the memset line go away :)
> Fix uninitialised stack-based buffers

- client/luascripts/hf_mfu_amiibo_sim.lua
https://github.com/RfidResearchGroup/proxmark3/pull/1886 will use whatever data has been uploaded into the emulator.  Depending on the source of the Amiibo binary data, the values could be 0.  If the user is running the amiibo simulator script, let's gently force the PWD/PACK to sane values.
> unconditionally recalculate pwd/pack for amiibo simulation

- CHANGELOG.md
- doc/magic_cards_notes.md
Gen4 GTU magic command to set maximum block/page for read/write standard (not magic) operations with card.
After executing command 'Dump configuration' (CF <passwd> C6) this parameter is backs to factory and need to be corrected.
> add gen4 GTU magic card command 'Set Ultralight and M1 maximum sectors'

- armsrc/iso14443a.c
I had pulled down and compiled latest after working through https://github.com/RfidResearchGroup/proxmark3/issues/1861 a week or so ago.
Last night, I dusted off my old 2DS XL and noticed that the Amiibo simulator wasn't working in the latest build.  I thought it must be my 2DS XL, but tested it on my kids' Switch and it wasn't working either.
It looks like in a63257799a0092460f86cce8bb3ded3e13cd2de2, the PACK was hardcoded to 00000000.
This patch will pull the PACK from the emulator memory and Amiibo simulation can work well again.
Do let me know if this not the preferred approach.
Thanks!
> use Amiibo PACK if simulator PWD matches generated Amiibo PWD

- CHANGELOG.md
- client/src/cmdhfmfu.c
Small addition so that the 50 pF version of the NTAG 210u (micro) gets identified. Currently, it only looks for the 17 pF version.
> Detect 50 pF version of NTAG 210u (micro)

- CHANGELOG.md
- client/src/cmdhf15.c
I believe that there were some minor issues with how the "nxp get info" command response was being interpreted. I tried to bring the code in line with the specification in the SLIX2 datasheet (page 33)
> Correct some parsing of the "get nxp system information" data from icode tags

- pm3
Currently `pm3-flash-all -p <port>` fails, as it passes the `-p` as the port to the $CMD:
```bash
$ pm3-flash-all -p /dev/ttyS3
[=] Session log /home/marcos/.proxmark3/logs/log_20230203.txt
[+] About to use the following files:
[+]    /usr/local/bin/../share/proxmark3/firmware/bootrom.elf
[+]    /usr/local/bin/../share/proxmark3/firmware/fullimage.elf
[+] Loading ELF file /usr/local/bin/../share/proxmark3/firmware/bootrom.elf
[+] ELF file version Iceman/master/v4.16191-22-g23a3590bb 2023-02-03 14:27:45 a86d9d107
[+] Loading ELF file /usr/local/bin/../share/proxmark3/firmware/fullimage.elf
[+] ELF file version Iceman/master/v4.16191-22-g23a3590bb 2023-02-03 14:27:46 a86d9d107
[+] Waiting for Proxmark3 to appear on -p
🕑  59^C
```
Note how it expects the device to "appear on -p" instead of …
> Fix pm3-flash-all -p XXX

- CHANGELOG.md
- client/src/cmdmain.c
- include/ansi.h
When running `clear` in pm3 client, the scrollback buffer is not cleared. This behavior is different from a lot of the shells'.
This PR adds a `-b` option to clear the scrollback buffer.
> Add a option to clear the scrollback buffer

- client/src/cmdhfwaveshare.c
My new Waveshare 1.54" NFC ePaper has different UID then what was expected in PM code. Probably new HW revision or something.
> Add new UID of Waveshare 1.54" NFC ePaper

- CHANGELOG.md
- Makefile
Regression caused by #1894.
See also PR #1902, where this PR was confirmed to fix the issue.
<details><summary>Root Cause (click to expand)</summary><P/>
PR #1894 updated the udev rules to automatically assign a group owner, and to automatically give the group both read and write privileges.   However, ArchLinux uses a different group name for access rights (according to pre-existing Makefile rules) ... they need the group to be `uucp` instead of `dialout`.   Therefore, the udev rules were split into two ... one file for when using `uucp` and one file for when using `dialout`.   This worked, and the devices were getting assigned the right group names, and automatically were usable without using `sudo`.
Unfortunately, I failed to test the `make install` option, and also failed to notice …
> Fix Makefile regression from #1894

- CHANGELOG.md
- armsrc/Standalone/hf_iceclass.c
This standalone mode starts by reading iCLASS credentials to flash, then after a button press, switches to emulating a previously saved credential.
> feat: add standalone ICECLASS read/sim mode

- armsrc/cmd.c
- armsrc/cmd.h
Small change to allow `reply_ng()` to accept a `const` buffer.
This does not restrict callers from using non-const buffers, and `reply_ng_internal()` is already properly marked as `const`.
This change also improves the function's contract by guaranteeing to callers that `reply_ng()` will not modify the data buffer.  Compilers can use this to further optimize code.  In short, it's good for all the reasons that `const` is generally good for.
> improve const correctness

- CHANGELOG.md
- Makefile.platform.sample
- armsrc/appmain.c
- armsrc/flashmem.c
- bootrom/Makefile
- bootrom/bootrom.c
- bootrom/ldscript-flash
- client/src/cmdhficlass.c
- common_arm/Makefile.hal
- common_arm/flashmem.c
- common_arm/flashmem.h
- common_arm/ticks.c
- common_arm/ticks.h
- common_arm/usb_cdc.c
- common_arm/usb_cdc.h
- doc/commands.json
Fixes #1904 
Enabling flash is now possible via `PLATFORM_EXTRAS=FLASH`, even on PM3 Easy.
I haven't noticed any negative or unexpected behavior.   Tested:
**Hardware:** (2x) PM3 Easy, purchased from DT within the last year.
**OS:** Windows 11 (including full uninstall of device using NirSoft's [`usbdeview`](https://www.nirsoft.net/utils/usb_devices_view.html)).
**OS:** WSL2 under Windows11, using Kali distributions + `usbipd` for connectivity 
NOTE: This REQUIRES flashing bootloader.  Otherwise, the device will sometimes show up without any serial number, and sometimes with.  I think this may depend either on enumeration speed of OS vs. loading stage3 boot (main image), or soft-boot vs. full power loss.   Does not occur after flashing new bootloader.
> Use unique USB Serial using flash's uniqueID

- pm3
This makes enumeration under WSL2 work correctly.
I leaves in the workaround someone added (which does not affect all systems?).
At the same time, it explicitly avoids double-enumeration when the exact same device name is found.
> Prevent double-enumeration under WSL2

- client/src/cmdhflist.c
I noticed when data is missing in the trace (probably due to buggy code on my side), and using `hf mfdes list`,  the hex part was correctly stating `<empty trace - possible error>`, but the Annotations  were displaying valid commands such as `READ RECCORDS` or `CREATE STD DATA FILE`. The `cmd` buffer was read despite `cmdsize` being 0.
> bugfix: wrong text in hf mfdes list when no data exists in trace

- client/src/cmdlfguard.c
- client/src/cmdlfguard.h
Guardall G-Prox fobs appear to store an arbitrary XOR key in the modulated data which is used to encode the FC and CN.  As a consequence of this, different data can decode to the same FC and CN.  Different installations appear to use different XOR keys as well, so without being able to specify the XOR key, it is highly unlikely that the resulting tag created from the clone command will be valid.  Previous code simply hardcoded the XOR key as 0x66;
> Added XOR key extraction and flag to Guardall G-Prox II

- armsrc/mifaredesfire.c
While experimenting with an ultimate magic card with ATQ, SAK and RATS set to mimick a DESFire tag, I noticed `hf mfdes info` returns strange values in different locations.
Actualy, the tag replies `6D 00` (instruction code not supported) to some commands, and this was interpreted as valid data.
This PR adds information on the wrong length of the answers, but keeps going on and adds FF where no data has been received, to cover the most use cases.
> Desfire : check length of tag answers

- client/src/cmdhfmfdes.c
In hf mfdes, in the example description of some commands, '-s' command was used (which does not exist) instead of '--schann'.
Also the error message for an invalid file number was giving the number in decimal, while it is given in hex in the arguments.
> hf mfdes: consistency fixes

- doc/md/Installation_Instructions/Troubleshooting.md
Update the version number of Ubuntu which has the same problem
I checked newer Ubuntu version 22.04 WSL 1 still have problem and solved by same solution sudo strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
> Update Troubleshooting, libQt5Core.so.5 not found

- CHANGELOG.md
- client/src/cmdhficlass.c
Picopass supports 2 KeyAccess configurations.  While the datasheet refers to the configurations as "Read/Write A/B", in practice, A and B themselves refer to the AA1 and AA2 areas of picopass storage.
I have updated the verbiage to be congruent with practice.
Discord discussion link: https://discord.com/channels/738045391416852520/738046308929110076/1083511261758771260
> Updated verbiage WRT iClass info (KeyAccess) to make it clearer

- CHANGELOG.md
- client/CMakeLists.txt
- client/deps/hardnested.cmake
Tested with:
- cmake 3.10.2.4988404/3.24.1
- ndk 25.2.9519653
Build command:
```
cmake \
-DCMAKE_TOOLCHAIN_FILE=/home/gitpod/androidsdk/ndk/25.2.9519653/build/cmake/android.toolchain.cmake \
-DANDROID_ABI=armeabi-v7a \
-DANDROID_NATIVE_API_LEVEL=android-19 \
-DSKIPBT=1 -DSKIPPYTHON=1 -DSKIPPTHREAD=1
```
(armeabi-v7a, arm64-v8a, x86 and x86_64 are all tested)
(I didn't test other versions of NDK, but they should work.)
***
This is for [RFIDtools](https://github.com/RfidResearchGroup/RFIDtools).
The Android build has been broken for a while.
<details>
<summary>preview</summary>
</details>
> Fix client build on Android

- CHANGELOG.md
- client/src/cmdhflegic.c
The `hf legic info` command was only available when reading directly from a card. The command displays deobfuscated and decoded legic data. 
This command is generally really useful and should also be executable on a dump file and on the emulator's memory. 
Changes:
- Extract method `static int decode_and_print_memory(uint16_t card_size, const uint8_t *input_buffer)` from `CmdLegicInfo`
- Call this function from the newly created commands:
- `CmdLegicEInfo` (`hf legic einfo`): Display deobfuscated and decoded emulator memory
- `CmdLegicDInfo` (`hf legic dinfo`): Display deobfuscated and decoded content from tag dump file
This PR also implements a couple of checks to prevent out of bounds memory access. Previously when the card contained invalid data (e.g. too large segment length) the …
> Legic info command for other sources, out of bounds memory

- client/src/cmdmain.c
The `-t`(or `--ms`) tag is necessary when using cliparser
```
[usb] pm3 --> msleep 100
msleep: unexpected argument "100"
[!] ⚠️  Try 'msleep --help' for more information.
[usb] pm3 --> msleep -t 100
[usb] pm3 --> 
```
> Fix the example of msleep

- doc/magic_cards_notes.md
Explained what the unknown command actually does. Set on '00' or '02' it enables direct writes to block 0 while setting it on '01' set block 0 on read only mode like a "normal card".
> Explain "Unknown Command" behaviour

- CHANGELOG.md
- client/luascripts/hf_mf_ultimatecard.lua
- desktop.ini
- doc/magic_cards_notes.md
Now the param `-u` supports 10 bytes uid only for mifare classic + added `Mifare Mini, 1k, 4k 10 bytes` to tag types + documentation fixes
> `hf_mf_ultimatecard.lua` now supports 10 bytes uid + documentation fixes

- CHANGELOG.md
- armsrc/appmain.c
The `rdv40_spiffs_check()` is a time-consuming process for large external flash. 
When running it between `usb_enable()` and the main loop, the enumeration will excess the timeout, just as the original comment says.
> Fix the USB enumeration process for large external flash

- client/src/cmdhfmf.c
Hi,
I fixed a bug in the `hf mf value` transfer attack that was recently implemented. 
Specifically, there was an issue with the `transferkeytype` being mistakenly assigned to `keytype`. This caused the command to fail when the attacked block had a key of type value `b`.  With this fix the attack should now function correctly.
> Fix wrong variable assignment

- include/pmflash.h
for commit 79cfa1d8faa56c390a045d779b997633b357c515 
(Although this definition is unused)
> Add the missing change of definition

- CHANGELOG.md
- doc/md/Installation_Instructions/Mac-OS-X-MacPorts-Installation-Instructions.md
Since mid-2022, arm64 builds of stable releases are working. So its been a while not updating this doc :)
> doc(macos-macports): refactor macports docs

- .github/workflows/rebase.yml
The current changelog reminder workflow always comments 
`You are welcome to add an entry to the CHANGELOG.md as well`
even if the PR contains the changelog entry.
This PR fixes it.
> Fix changelog reminder

- CHANGELOG.md
- client/src/cmdlfhitag.c
Not sure if it belongs here or a separate command. Let me know if you think it needs better formatting etc.
Example output:
```
pm3 --> lf hitag read --21 -k BDF5E846
[+]  UID: 466d9713
[=] Hitag2 tag information 
[=] ------------------------------------
[+] Config byte : 0x06 [ 00000110 ]
[+] Encoding    : Manchester
[+] Version     : Hitag2
[+] Coding in HITAG 2 operation: manchester
[+] Tag is in   : Password mode
[+] Page 6,7    : RW
[+] Page 4,5    : RW
[+] Page 3      : RW
[+] Page 1,2    : RW
[=] ------------------------------------
[=] 00 | 46 6D 97 13 | Fm..
[=] 01 | BD F5 E8 46 | ...F
[=] 02 | 20 F0 4F 4E |  .ON
[=] 03 | 06 F9 07 C2 | ....
[=] 04 | 9D AD 91 08 | ....
[=] 05 | B0 BF 00 03 | ....
[=] 06 | 00 30 00 06 | .0..
[=] 07 | 75 EB 00 10 | u...
[=] 08 | 00 00 00 00 | .... …
```
> Add paxton id to hitag2 info

- CHANGELOG.md
- armsrc/iso14443a.c
Fixes reader not being able to detect the simulated card on second Inventory command due to the RF field being powered off for only 6ms before being turned on again to reset the card to idle state.
Closes #1974
> hf mf sim: reduce 50ms threshold to 6ms for reset to idle

- armsrc/hitag2.c
Hitag 2 write commands are frequently failing;
Given the following command
`lf hitag write --27 -k 4d494b52 -p 4 -d 11111111`
The context of page 4 may be `11 11 11 11`, `FF FF FF FF`, or a random value.
This needs more investigation, but it seems like a bandage for the issue described above.
> 'Fix' writing on hitag2 in password mode

- CHANGELOG.md
- client/src/cmdhfmf.c
For some blank card with ACL `FF 07 80`, you can't write data with key B.
> Auth both key A and key B with default password in `hf mf restore`

- CHANGELOG.md
- armsrc/iso14443a.c
Fixes some readers not being able to detect the simulated card on second Inventory command due to the RF field being powered off for a short time before being turned on again to reset the card to idle state.
Closes #1974
> hf mf sim: reduce 6ms threshold to 4ms for reset to idle

- CHANGELOG.md
- armsrc/fpgaloader.c
FPGA header section "e" contains a four byte (32 bit) "bitstream size" value which is assigned to a uitnt16 (!) current_length which is then assigned to a uint32 section_length
This results in loss of the high 16 bits and truncated FPGA uploads for image sizes over 64K . This is not something that was noticed with the Spartan 2 bitstreams which are only 42KB but pops up with bitstreams over 64KB such as Spartan 3 bitstreams of 170KB like the xc3s250e.
Should also have affected icopy-x with xc3s100e as they have bitstreams of 70KB but they probably have their own workaround in their forked repo.
> Fix truncated FPGA upload due to incorrect integer size variable

- client/src/cmdhflegic.c
- tools/mfd_aes_brute/mfd_aes_brute.c
- tools/mfd_aes_brute/mfd_multi_brute.c
- fix: missing includes when building with "gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)"
- correct LEGIC 16bit CRC calculation "hf legic crc" in proxmark3 CLI
Use init_table(CRC_LEGIC_**_16_**) to be consistent with l_crc16legic in client/src/scripting.c
With this change, correct Legic Cash CRC16 checksums are calculated.
> gcc 11.2.1 - missing includes / correction for LEGIC CRC16 calculation

- client/src/cmdhffudan.c
- doc/commands.json
`hf mf wrbl` -> `hf fudan wrbl`
> Fix note for hf fudan wrbl

- CHANGELOG.md
- client/src/comms.c
I just found that the timeout of TCP connections is overwritten in TestProxmark()
Here is the test output
<details><summary>Details</summary>
```
[=] Using UART port tcp:192.168.0.1:1234
Current timeout(us):500000
...
Current timeout(us):500000
[=] Communicating with PM3 over USB-CDC over TCP
8888888b.  888b     d888  .d8888b.   
888   Y88b 8888b   d8888 d88P  Y88b  
888    888 88888b.d88888      .d88P  
888   d88P 888Y88888P888     8888"  
8888888P"  888 Y888P 888      "Y8b.  
888        888  Y8P  888 888    888  
888        888   "   888 Y88b  d88P 
888        888       888  "Y8888P"    [ ☕ ]
Current timeout(us):20000
...
Current timeout(us):20000
[ Proxmark3 RFID instrument ]
Current timeout(us):20000
...
Current timeout(us):20000
[!] ⚠️  Received packet frame with variable part too …
```
> Fix the timeout of TCP connections

- armsrc/Standalone/hf_colin.c
- armsrc/Standalone/hf_mattyrun.c
- armsrc/appmain.c
- armsrc/iso14443a.c
- armsrc/mifarecmd.c
- armsrc/mifarecmd.h
- armsrc/mifareutil.c
- armsrc/mifareutil.h
- client/src/cmdtrace.c
- include/protocols.h
There was a bunch of duplicate code doing the same thing for reading and writing blocks for mifare classic on the arm side where the only difference was a single byte for the command (normal vs magic vs magic config). This cleans up a lot of that duplication retaining all functionality while culling a few hundred lines of code while making the remaining functions more generic which will be super handy in the near future adding support for some new types of magic cards.
I've avoided changing the RPC interface between the armsrc and client, but with the new functions there is an opportunity to simplify that interface in the future for reading and writing blocks. As hinted by the addition to a define in protocols.h I discovered a GDM read block backdoor command while working on this. Curious …
> Cleanup arm-side reader-mode mifare classic block read/write code.

- CHANGELOG.md
- client/deps/liblua/luaconf.h
iOS can, in fact, use the system() stdlib call.
If I had to guess, this wasn't an issue before because it didn't know the target was IOS? Not really sure, but removing this makes sense, and I can now successfully compile the client.
> Fix compiling liblua on iOS

- client/src/cmdhfvas.c
If I'm not mistaken, premature call to `tlvdb_free ` before `mbedtls_ecp_point_read_binary` caused the latter to get deleted memory, which could have caused a segfault.
> Fix potential memory leak in VAS implementation

- client/src/cmdhfmfhard.c
This PR implements loading of uncompressed hardnested bitflip tables. It allows us to shave 2-3 seconds off a single hardnested attack, which is quite convenient.
To maintain compatibility with the current behaviour, this implementation tries loading the bz2 files first, and if it fails, proceeds with trying to load the uncompressed .bin files.
> Implement uncompressed hardnested tables loader

- client/src/cmdhfmfhard.c
On a server with a large number of CPU cores, we experience weird freezes on hardnested launch. I didn't dig too deep into the core of the issue, but it looks like we get stuck somewhere in the guts of `sysconf()` when it is executed concurently by hundreds of threads.
This PR attempts to exclude extraneous and, frankly, unnecessary calls to the `num_CPUs()` function to work around this issue.
> Eliminate extraneous num_CPUs() calls

- client/deps/hardnested/hardnested_bruteforce.c
This PR fixes the hardcoded limitation of 128 buckets (and hence 128 threads) in the hardnested attack implementation. Buckets are now allocated dynamically in power-of-two increments.
> Dynamically allocate buckets array for the hardnested bruteforce attack.

- client/src/cmdhfmf.c
This PR improves the startup time in offline mode by not trying to detect the EV1 signature.
> Do not try to detect Mifare classic EV1 signature in offline mode

- armsrc/mifareutil.c
Mifare Classic KeyA/B were accidentally switched in some contexts.
> Fix regression caused by edd8e36 (PR #2021).

- client/src/cmdhfmf.c
> Don't require valid key or proxmark3 for hardnested with --tests

- armsrc/iso14443a.c
- armsrc/iso14443a.h
- client/resources/ecplist.json
Hello.
This change is more of a functioning proposal currently, but in case you're fine with it, it could be merged.
I've refactored the GetATQA method, allowing to pass different polling configurations to it using the newly defined `iso14a_polling_frame` and  `iso14a_polling_parameters` structs.
This allows to remove different proprietary, implementation-specific polling hacks (like ECP, MagSafe) that were once inside this method, and bring them to the outer layers (currently to `iso14443a_select_cardEx` and `iso14443a_fast_select_card` methods, in the future to the client). 
What I assume could be done in next PRs, is to bring the custom-configuration-forming logic (leave WUPA at arm side) to the client side, which could allow more flexibility when someone wants to implement new logic …
> Make GetATQA/ISO14443-A polling method more flexible

- armsrc/iso14443a.c
- armsrc/iso14443a.h
- client/src/cmdhf14a.c
- client/src/cmdhf14a.h
- client/src/cmdhfvas.c
- include/mifare.h
This PR incorporates following changes related to the previous one:
* To save stack memory, passing polling parameters by value was replaced by pointer.
* Reduce polling parameter struct memory footprint by reducing inner array sizes to minimum required;
* Moved ECP, Magsafe polling frame generation to client;
* Remove ECP, Magsafe constants from device;
* Make VAS command emit ECP VAS ONLY frames using new feature, so now a device will display a particular pass for authentication instead of a payment card (express mode does not exist for VAS).
> Move custom polling frames to client

- CHANGELOG.md
- client/src/cmdhflist.c
- client/src/cmdhflist.h
- client/src/cmdhfmfp.c
- client/src/cmdtrace.c
- doc/commands.json
- include/protocols.h
Adds interpretation of MIFARE Plus protocol:
```
[usb] pm3 --> trace list -t mfp -c -1
40744032 |   40754496 | Rdr |0b  07  70  23  40  01  01  3e  5c                                       |  ok | FIRST AUTH (Keynr 0x4023: B sector 17)
[...]
41218160 |   41236688 | Rdr |0b  07  31  44  00  01  73  0e  ae  ee  e3  67  12  c1  7b  b2           |  ok | READ ENCRYPTED(68)
41655424 |   41673952 | Rdr |0a  07  31  44  00  03  55  61  a4  49  5b  71  c1  c8  d7  8d           |  ok | READ ENCRYPTED(68-70)
[...]
|            |     |39  ca  9e  2a  4d  03  7a  ae  6e                                       |  ok | WRITE ENCRYPTED(68)
```
Tested with a few real life traces; however I do not have blank MIFARE Plus cards or cards with known keys to fully test.
Information gathered from public part of …
> Add MIFARE Plus commands in trace list

- client/src/cmdhflist.c
source: ISO14443-4, section 5.
PPSS is detected on 4 bits matching the begining of frame, hopefully this does not conflict with higher level protocols
> trace: fix PPSS and  add CID, FSDI to RATS

- client/luascripts/hf_legic_clone.lua
variable "length" was used parameter in function, but later called as "len"
> Fix typo in hf_legic_clone.lua

- client/src/cmdhflist.c
- client/src/cmdhflist.h
This adds `MAC_MAced` `NoMAC_UnMACed`,  and so on to the relevant commands, according to the datasheet.
example:
```
|     |39  ca  9e  2a  4d  03  7a  ae  6e                                       |  ok | WRITE ENCRYPTED(68) MAC
| Tag |0b  07  90  e8  74  62  db  46  e7  72  de  63  bd                       |  ok | 
| Rdr |0a  07  31  48  00  03  be  e0  5c  44  65  7e  3a  1e  8c  d7           |  ok | READ ENCRYPTED(72-74) MAC_MACed
```
This was also the occasion to refactor code by moving more messages to the lookup table.
> MIFARE Plus traces: Adds MAC, UnMACed to annotations, and code factorisation

- armsrc/iso14443a.c
These values were observed from a standard-keyed 4K Seos card.
> Add a tagType for Seos cards to SimulateIso14443aInit

- client/src/cmdhfmf.c
This fixes a regression caused by edd8e36 (PR #2021).
gdm auth has no concept of A or B keys, a partial cleanup in the previous PR removed the key type from the arm code, but the corresponding removal was missed in the client side resulting in mismatched structs for cmd CMD_HF_MIFARE_G4_GDM_WRBL.
> Fix hf mf gdmsetlbk block data being accidentally prefixed with a 0x00

- client/src/cmdhflist.c
- include/protocols.h
* Added a new DESFire command code `0xEE` definition and annotation.
This code is not mentioned in any docs. It's used by Apple-ECP-certified DESFire readers at the end of communication to notify the device that the transaction has been successful. It doesn't seem to have any other effect apart from UX, although use this command is mandatory for Apple device to consider a read "successful" (otherwise an error will appear on a screen). Android (Mifare2GO) and physical cards (EV3) don't know this command code.
This seems to be the thing that some reader brochures referred to, by using ECP as an abbreviation for "Enhanced contactless **protocol**" instead of "polling". In this case DESFire protocol has been enhanced to add a command that allows a reader to explicitly tell a device that …
> Add new DESFire command code and annotation

- client/src/guidummy.cpp
link time optimization requires all functions named the same to actually operate the same.  I am pretty sure this fixes it without breaking anything.
Fixes: https://github.com/RfidResearchGroup/proxmark3/issues/2058
src/proxgui.h:35:6: error: type of ‘ShowPictureWindow’ does not match original declaration [-Werror=lto-type-mismatch]
35 | void ShowPictureWindow(uint8_t *data, int len);
|      ^
src/guidummy.cpp:33:17: note: type mismatch in parameter 2
33 | extern "C" void ShowPictureWindow(char *fn) {
|                 ^
src/guidummy.cpp:33:17: note: type ‘void’ should match type ‘int’
src/guidummy.cpp:33:17: note: ‘ShowPictureWindow’ was previously declared here
> fix lto-type-mismatch in guidummy.cpp

- client/src/mifare/mifarehost.c
We are reading this 26 bytes into a 32 byte buffer, is this even any worse?
Fixes: https://github.com/RfidResearchGroup/proxmark3/issues/2060
> fix -Wstringop-overread error

- client/src/cmddata.c
the call to `return atr_selftest()` being commented, the function kept going to the end, reading an uninitialised data[] array, and printing the results.
> Bugfix: `data atr -t` was reading uninitialized data

- client/src/proxmark3.h
- common/commonutil.c
- common/commonutil.h
- doc/md/Installation_Instructions/Windows-WSL2-Installation-Instructions.md
Three items:
1. Extend Little-endian and Big-endian functions to support 5-9 byte data.
2. Update WSL2 instructions for improved user experiences
3. Add hours / minutes / seconds to logfile
<details><summary>LE and BE functions</summary>
<p>
These functions are added because they are useful for em4x70 data structures.
These mirror functionality already existing for 2-4 byte versions:
```C
uint64_t MemLeToUint5byte(const uint8_t *data);
uint64_t MemLeToUint6byte(const uint8_t *data);
uint64_t MemLeToUint7byte(const uint8_t *data);
uint64_t MemLeToUint8byte(const uint8_t *data);
uint64_t MemBeToUint5byte(const uint8_t *data);
uint64_t MemBeToUint6byte(const uint8_t *data);
uint64_t MemBeToUint7byte(const uint8_t *data);
uint64_t MemBeToUint8byte(const uint8_t *data);
void …
```
> Minor (useful) updates

- client/src/proxmark3.c
- client/src/util.c
- client/src/util.h
This PR adds a new command line argument, `--ncpu`, to override the detected CPU core count. It is intended to allow for better fine-tuning of performance on machines with large numbers of CPUs.
> Configurable number of CPU cores.

- CHANGELOG.md
- client/src/cmdhficlass.c
- client/src/util.c
- client/src/util.h
- doc/commands.json
Now relies on the legacy config block for SR detection and the end-of-SIO detection no longer partially cuts off the SIO for any dumps I have.
The previous code would cut off some SIOs mid way through if they happened to contain the wrong bytes mid way through.
Also fixes a couple of super minor display quirks I noticed while running `hf iclass view` on all my dumps - for example if the stars aligned on a SE dump it could in some cases try and decode block 7 as if it were a legacy dump resulting in rather confusing output, and a case where `hf iclass decrypt` would attempt to use a card helper even if the flag wasn't set (again if the stars aligned with the right block data).
> Improve iClass SIO and legacy credential detection reliability

- tools/cryptorf/Makefile
- tools/cryptorf/sma.cpp
I'm not sure if the count = 0 should have been deleted but it was also being reported as an error with the default make command.
Closes 2089
> Fix macOS errors while building after cryptoRF solvers was added.

- client/resources/aidlist.json
- include/protocols.h
This commit adds SEOS AIDs to the json database.
It also removes duplicate MFP command definitions created by me on accident in one of the last PR's.
> Remove duplicate MFP definitions. Update AIDlist

- README.md
- doc/md/Installation_Instructions/Troubleshooting.md
- doc/md/Installation_Instructions/macOS-Compile-From-Source-Instructions.md
- doc/md/Installation_Instructions/macOS-Homebrew-Installation-Instructions.md
- doc/md/Installation_Instructions/macOS-MacPorts-Installation-Instructions.md
In 2012, Apple changed the name of their operating system from "Mac OS X" to  "OS X" and later (in 2106) to "macOS".  This PR updates all references in the documentation from the outdated "Mac OS X" to the new name - "macOS".
> Change "Mac OS X" to "macOS" in documentation

- client/src/cmdtrace.c
This fixes crc rendering when data len is multiple of 16. Before you would for example get this when the first char of ANSI escape code would get lost:
```
77369536 |   77392704 | Tag |xx  xx  xx  xx  xx  xx  xx  xx  xx  xx  xx  xx  xx  xx  xx  xx  xx  xx   |     | 
|            |     |[0m yy  yy  
```
> Fix crc render position when data len is multiple of 16

- CHANGELOG.md
- armsrc/appmain.c
- armsrc/iclass.c
- armsrc/iclass.h
- client/src/cmdhficlass.c
- client/src/pm3line_vocabulary.h
- doc/commands.json
- doc/commands.md
- include/iclass_cmd.h
- include/pm3_cmd.h
Note that this can not be achieved with simple `hf iclass wrbl` commands as it requires two writes back ot back without dropping the field.
Note since the recharging value must be decreased this sadly does not allow complete rollback of the epurse value to a prior state.
> Add `hf iclass creditepurse` command to allow crediting the epurse debit value

- client/src/cmdhfmf.c
Problem:
`hf mf autopwn` returns silently when no card is detected. There is a DEBUG message that most people won't see
Proposed Solution:
Change the DEBUG to a FAILED and add a HINT
> Change in behavior of hf mf autopwn when no card is detected

- tools/cryptorf/sma_multi.cpp
ATOMIC_VAR_INIT is now deprecated and is causing build failures for MacOS.
The unused functions were also causing errors. What is the desired approach for dealing with those cases?
> Fixing macOS errors.

- CHANGELOG.md
- client/src/cmdhficlass.c
It now does some super basic parsing of the ASN.1 to determine the length rather than pattern matching. I also feed this information into the block view to correctly highlight the SIO blocks rather than always assuming it's the same number of blocks.
I also added some bounds checking for safety and tweaked the legacy block display to show "HID CFG" for block 6, and "Enc Cred" if the legacy block is encrypted instead of just always showing "Cred".
This fixes the bug mentioned in discord where it would fail to show custom keyed SIOs correctly
> Changed hf iclass view/decrypt to detect SIO lengths better and show if legacy credentials are encrypted

- CHANGELOG.md
- README.md
- doc/md/Installation_Instructions/iOS-Installation-Instructions.md
This patch/pr adds documentation I have written on how to compile and install proxmark3 on iOS. It's not the cleanest process ever, but it's getting there.
> Add documentation for iOS

- doc/commands.json
As all the commands require cardhelper it is not possible to run this command without being in online mode.
> Fixed command to be online only

- CHANGELOG.md
- client/src/comms.c
Before PR #2022, the default communication timeout for TCP is accidentally set to 20ms, but it works  for Termux.
In PR #2022, I fixed the default timeout of TCP connections, but it increases the latency when running some commands in Termux. To reduce the latency, I added some code to detect whether the host address is `127.0.0.1` or `localhost`, and reduce the timeout if so.
> Reduce latency in local TCP connection

- CHANGELOG.md
- client/src/cmdhficlass.c
Finalized implementation of configcard generation for mode 9 & 10 (keyroll) when cardhelper is not present.
Results need to be compared with cardhelper output to confirm blocks 14 & 15 behavior / accuracy.
> Finished configcard implementation for keyroll cards

- client/src/uart/ringbuffer.c
- client/src/uart/ringbuffer.h
- client/src/uart/uart_posix.c
The `read()` can only write data to a continuous block of memory, so theoretically we need a transit buffer to hold the data from `read()` before we can put the data into the ring buffer.
However, we can write data to the internal buffer between `data[rear]` and `data[capacity-1]`, in which the space is continuous.
> Increase the speed of uart_receive() in UDP mode

- armsrc/Standalone/hf_iceclass.c
Function is already declared (non-static) in `armsrc/iclass.h`.
Compiler was complaining about re-defining a non-static func by a static one.
> Remove compilation error.

- README.md
The badge of macOS CI always shows failing for a long time, even for successful runs of CI
`![MacOS Build and Test](https://github.com/RfidResearchGroup/proxmark3/workflows/MacOS%20Build%20and%20Test/badge.svg?branch=master)`
It turns out the URL of these badges has changed. So this one works
`![MacOS Build and Test](https://github.com/RfidResearchGroup/proxmark3/actions/workflows/macos.yml/badge.svg?branch=master)`
The API changes can be found there.
https://github.com/github/docs/pull/3802/files#diff-95d58394efa588c4f92f85274259efb8ca1e10a02bd346549e65b57604c156c4
> Change URLs of badge in README.md

- CHANGELOG.md
- client/deps/cliparser/cliparser.c
When a quoted command argument is seen, it will take all characters until the next double-quote (no supported escape sequence here for simplicity), skipping spaces (space, tab, etc.) inside.
This is meant to allow copy/pasting of formatted code, especially hex-encoded values. This doesn't add the capability to pass argument containing spaces (e.g. filenames).
This means that the following commands should behave the same:
```
pm3> wiegand encode --fc 101 --cn 1337
pm3> wiegand encode --fc "1 0 1" --cn "1    3    3   7"
```
Or a more realistic/useful example, when copy/pasting hex formatted values from other commands:
```
pm3> hf iclass calcnewkey --old 1122334455667788 --new 2233445566778899
pm3> hf iclass calcnewkey --old "11 22 33 44 55 66 77 88" --new "22 33 44 55 66 77 88 99"
```
> Support double-quoted arguments in CLI

- client/src/cmdhficlass.c
- doc/commands.json
Fixed command help file as it incorrectly shows -b instead of --blk
> Fixed esetblk command description

- CHANGELOG.md
- client/src/cmdhficlass.c
- doc/commands.json
Added support for a scenario in which the old key is elite and the new key is not elite.
> Modified hf iclass calcnewkey

- CHANGELOG.md
- common_arm/usb_cdc.c
Transfer speed before this fix:
616448, 618496, 618496, 615424, 615424 -> average: 616857.6 bytes/s
Transfer speed after this fix:
~~707584, 709632, 707584, 709632, 710656 -> average: 709017.6 bytes/s (+14.9%)~~
722944, 733184, 732160, 731136, 733184 -> average: 730521.6 bytes/s (+18.4%)
Tested by running `hw status`
> Increase the USB speed by fixing synchronization waits in usb_write()

- client/src/cmdscript.c
Brought to attention by preparation for Fedora 41 packaging @ https://bugzilla.redhat.com/show_bug.cgi?id=2245823
> cmdscript.c: explicitly include ctype header

- CHANGELOG.md
- armsrc/lfsampling.c
This improves the performance of sampling for `bps < 8`, makes it perform better on low-end machines.
@wh201906 did a benchmark for this
> Improve sampling performance

- CHANGELOG.md
- client/src/cmdhficlass.c
Was able to compare the output of nfc-iclass and I identified two bugs in the generation of blocks 0x0D (was being overwritten with FF, it seems this was an original bug in the original pm3 code?) Fixed the porting for block 15 generation.
> Fixed keyroll mode for hf ic configcard

- client/src/fileutils.c
The code was incorrectly checking the loop variable `i`,
rather than checking the used data length / current buffer pointer.
This causes dumps with all 64 sectors of data to refuse to load, with false error message that the data buffer size was exceeeded.
Also improved flow for dump files, by providing distinct error message when a data block in the JSON ...
* ... would exceed maximum total data size
* ... has zero data
* ... has fewer than 16 bytes of data
Bonus fix for that third case (< 16 bytes):
The old code would save the partial-block into the buffer ... but all future blocks of data would then be loaded at an incorrect offset.  The fixed code ensures zero-filled data is used, and this is noticable at the client via the warning message.
> Fix mf file loading error

- client/src/fileutils.c
No functional problems occur with existing code.  However, this code path is **_normal_** ... it occurs at every startup, and thus prints a useless error message every time the client connect.
I didn't notice the error message earlier in my tests -- my apologies!
> Remove incorrect message (my own regression)

- client/src/cmdhfmfdes.c
- client/src/cmdhfmfdes.h
- client/src/cmdhfntag424.c
Implemented GetVersion and GetSignature commands for NTAG424, and added getting/printing of them in the "info" command.
I did a dubious thing by making the signature verification from DESFire public by making a wrapper function that didn't need to supply card_type. Seems like that parameter is not needed anyway.
The version information command is the same as for desfire, so might have been possible to use that instead, but the signature was not readable by the desfire commands.
> Implemented 'info' command for NTAG424

- client/src/cmdhw.c
I couldn't find this exact chip ID on any datasheet but that's the ID I have on my genuine PM3 RDV4 and I was tired of seeing `Unknown` :)
The last 5 bits of the chip ID only indicate the version of the chip (Section 26.5.10 page 235 of the datasheet from 2012) so I arbitrarily merge the 0xE version with the 0xF and identify them as rev B.
> Add alternative chip ID

- CHANGELOG.md
- armsrc/appmain.c
- armsrc/appmain.h
- client/src/cmdhw.c
It's helpful to get a stable speed test result by extending the timeout.
I've tested the compatibility. Both the old client and old firmware can be used with the new client and new firmware.
> Add `--ms` option in `hw status`

- client/Makefile
This fixes issue #2182
The issue is caused by upstream bug
https://github.com/python/cpython/issues/106560
The fix is like this
https://github.com/intel-media-ci/gstreamer/commit/bbdf6d46539061bf171319ae51999f061148ecbc
> Fix client build with Python 3.12

- client/src/cmdsmartcard.c
This fixes #2184
`ExchangeAPDUSC()` in `cmdsmartcard.c` doesn't return 1 if the retry fails, which is different from the behavior of the first try.
`Iso7816ExchangeEx()` will treat the negative length as the valid one when the failed retry occurs. This causes overflow when accessing `result[*result_len]`
> Fix `ExchangeAPDUSC()` in `cmdsmartcard.c`

- client/src/cmdsmartcard.c
- client/src/iso7816/iso7816core.c
As @iceman1001 suggested in https://github.com/RfidResearchGroup/proxmark3/pull/2186#issuecomment-1826192861
I've checked all the usages of `ExchangeAPDUSC()`. Only the call in `Iso7816ExchangeEx()` uses the return value of `ExchangeAPDUSC()`, and the code there can handle the negative return value (`PM3_Exxx`)
> Use defined return value

- CHANGELOG.md
- armsrc/iclass.c
- client/src/cmdhficlass.c
Fixes a couple of bugs, the first being that `block_cnt` was actually the last block read not the block count, but was being used as both depending on context. This meant dumping eg a 16k card with both debit and credit keys specified would only dump blocks 0-236 truncating the last 19 blocks when AA2 first block was 19 (236+19=255). The new code now dumps all 256 blocks (0-255) for a 16k card.
While dumping full 16k blocks a bunch of times to test  this, I noticed if coupling wasn't perfect it would fail on a few of the blocks which seemed strange as the code should have retried any failed reads. Looking closer at the trace I noticed the retry logic seemed to immediately retry so all 3 attempts failed - even though it read the block before and after perfectly fine. I realised this was …
> Fix iClass dump truncating the AA2 area and improve dump reliability by fixing cmd retry delays.

- armsrc/appmain.c
- armsrc/fpgaloader.c
- armsrc/lfsampling.c
- armsrc/lfsampling.h
- armsrc/lfzx.c
- armsrc/util.c
- armsrc/util.h
- client/src/cmddata.c
- client/src/cmddata.h
- client/src/cmdlf.c
- client/src/cmdlf.h
- client/src/cmdlfhid.c
- client/src/cmdlfindala.c
- client/src/cmdlfio.c
- client/src/cmdlfparadox.c
- client/src/cmdlfpyramid.c
- client/src/comms.c
- client/src/comms.h
- client/src/graph.c
- client/src/graph.h
- common_arm/usb_cdc.c
- common_arm/usb_cdc.h
- include/common.h
- include/pm3_cmd.h
#2167 with clear commit history and some minor improvements
Known limitations:
1. Only `bits_per_sample = 8` is supported now.
2. Only USB connection is supported now. The transfer speed should be greater than 300kByte/s to support this feature.
3. When LF image is not loaded into the FPGA, the first 14 bytes could be the response of CMD_WTX rather than real samples.
> Real-time LF sampling

- CHANGELOG.md
- armsrc/fpgaloader.h
- client/src/cmdhfmf.c
- client/src/cmdhw.c
- client/src/cmdlf.c
- include/pm3_cmd.h
1. Make sure the LF bitstream is loaded before real-time sampling so the response of CMD_WTX won't appear.
2. Decrease the wait time from 2.5s (1s + FPGA_LOAD_WAIT_TIME) to 1s if the real-time sampling stops.
> Fix corrupted data caused by CMD_WTX

- client/src/cmdtrace.c
When a trace is loaded, then a subsequent load fails, 'trace list' segfaults because CmdTraceLoad frees gs_trace but doesn't zero the length, and CmdTraceList doesn't check for NULL.  Fixed.
> cmdtrace.c: fix segfault in 'trace list' after failed load

- CHANGELOG.md
- client/src/cmdhfmf.c
The help for `hf mf sim` says that if `-i` is passed, "Console will not be returned until simulation finishes or is aborted." However, when using interactive with the reader attack option (`hf mf sim -ix`), the console does not return when the simulation is finished or when the button is pressed.
This seems to be because in `cmdhfmf.c`, it continues waiting for more `CMD_ACK`s after processing the information from the device, while the device only sends `CMD_ACK` once (after the simulation is finished or the button is pressed.) Adding `break` after the `readerAttack` line seems to fix this, and doesn't seem to cause any other issues.
> Fix Mifare Classic sim with interactive and reader attack mode never returning console

- CHANGELOG.md
- bootrom/bootrom.c
This fixes a bug with the USB device serial number sometimes not working in bootloader mode.
> Clear bss on bootloader start.

- doc/fpga_arm_notes.md
The note should be pretty self-explanatory.
It should be simple for the reviewer to test this works. Delete a bit file and follow this method to recreate it. I don't know if there is a proxmark docker repo, but if there is, it should be a simple matter to retag it and push it to there, instead.
Tested on M1 mac and x86 ubuntu.
==========================================================
Perhaps there was an easier way, but...
For future reference to anyone reading this PR, to install Xilinx WebPack ISE 10.1 it was downloaded as a zip, mounted into a linux container and then during the install the gui installation popups were forwarded back to the host (ubuntu 22.04.1) with the following command:
`docker run -v <LOCAL_PATH>:/tmp --rm -it -v $XAUTHORITY:/tmp/.XAuthority -e …
> Add a note on building in a docker image instead

- CHANGELOG.md
- client/src/uart/uart_posix.c
- client/src/uart/uart_win32.c
The client can detect if the TCP connection is lost and show `offline` in the command line.
> Check TCP connection state

- client/CMakeLists.txt
- client/Makefile
- client/experimental_lib/CMakeLists.txt
- client/src/uart/uart.h
- client/src/uart/uart_common.c
- client/src/uart/uart_posix.c
- client/src/uart/uart_win32.c
- include/pm3_cmd.h
+ Move `uart_bind()` to `uart_common.c`, as most of the code in it is platform-independent.
+ Add const qualifier to some arguments of `uart_bind()`
+ Refactor the address/port parser into a separate function `uart_parse_address_port()`. This code block was repeated 8 times in the old implementation.
+ Merge the code of TCP and UDP connection in `uart_open()`
+ Add some code to check the prefix length before calling `memcmp()`
> Clean up the code for network connection

- CHANGELOG.md
- client/src/proxmark3.c
- client/src/proxmark3.h
- client/src/uart/uart_posix.c
- client/src/uart/uart_win32.c
The connection type prompt wouldn't change if I connect to hardware via TCP then run `hw connect -p /dev/ttyACM0`. The old `prompt_net` is not cleared.
I also cleaned up some code in commit e5dd9952d78e6b9a7a6e18cb4da8dd71352a1ba1
> Update connection type in CLI prompt

- CHANGELOG.md
- armsrc/Standalone/hf_cardhopper.c
This functionality can be enabled by adding the following to your Makefile.platform:
`STANDALONE_PLATFORM_DEFS+=-DCARDHOPPER_USB`
> Changed hf_cardhopper standalone mode to allow running over the internal PM3 USB-CDC serial port.

- CHANGELOG.md
- armsrc/mifarecmd.c
- client/src/mifare/mifarehost.c
- include/protocols.h
Magic detection no longer stops when a single type is found as cards may support multiple types of magic, so all detected types will be reported now.
GDM/USCUID chips are now detected when GDM magic auth is disabled but magic WUP (40 or 20) is enabled.
Gen2/CUID/DirectWrite is now detected when default keys and ACLs are used by attempting to write to block 0 but aborting before actually completing the write.
Some example `hf 14a info` output
CUID chip (factory defaults, default keys/etc)
Before:
```
[+]  UID: F1 E6 A9 30
[+] ATQA: 00 04
[+]  SAK: 08 [2]
[+] Possible types:
[+]    MIFARE Classic 1K
[=] proprietary non iso14443-4 card found, RATS not supported
[+] Prng detection: weak
[#] Auth error
[#] Auth error
[?] Hint: try `hf mf` commands
```
Now:
```
[+]  UID: F1 E6 A9 30
[+] ATQA: …
```
> Improved magic detection

- client/src/comms.c
- client/src/uart/uart.h
- client/src/uart/uart_posix.c
- client/src/uart/uart_win32.c
1. Add `msleep()` to reduce the CPU usage
2. Disable printing error information when calling `uart_open()` in `OpenProxmarkSilent()`
I'm still finding the reason of crash when running `hw connect` to a different port in the offline mode, so I created this as a draft.
> Some fixes for the reconnect feature

- CHANGELOG.md
- client/src/cmdhf14a.c
This fixes issues when using the command against cards that indicate really slow times, such as card emulation by hf_cardhopper.
> hf 14a apdu now uses the FWI and SGFI values from the ATS to determine an appropriate timeout.

- CHANGELOG.md
- client/src/cmdhf.c
It was:
```
[usb] pm3 --> hf search
🕙  Searching for iCLASS / PicoPass tag...   
[+] iCLASS / Picopass CSN: CE F0 43 01 F7 FF 12 E0 
[+] Valid iCLASS tag / PicoPass tag found
```
And now it is 
```
[usb] pm3 --> hf search
🕗  Searching for iCLASS / PicoPass tag...   
[+] iCLASS / Picopass CSN: CE F0 43 01 F7 FF 12 E0 
[+] Valid iCLASS tag / PicoPass tag found
[?] Hint: try `hf iclass` commands
```
> Add hint for iClass in `hf search`

- client/src/cmdflashmemspiffs.c
- client/src/cmdtrace.c
- client/src/cmdtrace.h
Sometimes one has a bunch of traces in SPIFFS after a long day of standalone work, and wants to look at them and decide what to save.  Adds '-t' option to mem spiffs dump, to download the data into client trace buffer instead of creating a local file which one must then 'trace load'
Not sure I like how I implemented this, or whether it's useful to anyone else.
> SPIFFS: implement dumping from SPIFFS to client trace buffer

- CHANGELOG.md
- bootrom/bootrom.c
Commit 51e4df533e79399fef1672325d2ec57fdcc27986 changed the button behavior, but it doesn't work on my Proxmark3 Easy. I think it's caused by the jitter (bounce) when pressing/releasing the button.
> Ignore button jitters in bootloader mode

- client/src/cmdhfwaveshare.c
This command should be 3 bytes long, not two, as shown in the following decompilation of their Android APK:
> Fix incorrect Waveshare command

- CHANGELOG.md
- armsrc/Standalone/hf_cardhopper.c
Allow button presses to break
Handle non-zero CID from reader by relaying RATS to the card and improving PPS and WTX handling More reliably cook ATS values
Ignore packets that look like they're coming from the client (NG packets)
> Multiple hf_cardhopper improvements

- client/src/cmdhfxerox.c
The partnumber additional information was incorrect, because of strncmp seeing "-1" suffix as pattern. It now shows correct information, based on the partnumber example "006R01530". The pattern of partnumbers can be different, so we need to check what the variations can be. I also wonder what "-1" suffix means.
It would be nice if all block data would be placed at the top of the code, to prevent searching.
> Small Xerox changes, finding correct partnumber additional information

- CHANGELOG.md
- client/src/cmddata.c
- doc/commands.json
- doc/commands.md
Implementation to quickly cipher data and not look for a tool online, with some proprietary algorithms.
Includes:
* DES ECB/CBC de/encryption
* 2/3 key TDEA ECB/CBC de/encryption
* AES 128 CBC de/encryption
* FMCOS DES MAC calculation (part of DES CBC encryption)
* AES CMAC
Tests were done on real chips. The outputs are equal.
A sample is provided.
*FeliCa Lite MAC is not implemented due to lack of testing material*
> Add `data crypto` command

- client/src/cmdhfxerox.c
At `xerox_part_t` I added interchangeability (color, black, both) of slots for drums, I tried splitting it to xerox_consumable_t, xerox_toner_t, xerox_drum_t but didn't manage, so this is my approach with empty values.
In `CmdHFXeroxInfo `and `CmdHFXeroxView `I added a way of showing toner of drum specific additional information. Note that this code is a duplicate so I think we need a function for logging the tag memory and additional information.
> Added small drum data, for showing interchangeability of slots

- CHANGELOG.md
- armsrc/appmain.c
- armsrc/util.c
- armsrc/util.h
- bootrom/bootrom.c
- client/src/cmdhw.c
- client/src/comms.c
- client/src/comms.h
- client/src/proxmark3.c
- doc/commands.md
- include/pm3_cmd.h
Reading memory works when the device is running either osimage or bootloader.
- New memory reading command in osimage and bootloader.
- Extended 'hw readmem' command with length parameter, file writing and hex viewer.
- Introduced '--dumpmem' option to proxmark3 executable to support dumping from bootloader.
Simple interactive examples:
- `hw readmem -f flashdump`
- `hw readmem -l 1024`
CLI example:
- `./pm3 --dumpmem flashdump.bin`
Reading from arbitrary memory ranges can be unlocked using the 'raw' option.
> Adding processor flash memory reading, viewing and writing to file.

- armsrc/appmain.c
- bootrom/bootrom.c
- client/src/cmdhw.c
- client/src/proxmark3.c
Some minor cleanup in the new readmem functions.
- number entry should be unsigned and allow hexadecimal
- printing filename to the console twice
- corner case at the end of adressable memory
> Readmem small fixes

- CHANGELOG.md
- armsrc/BigBuf.c
- armsrc/hfsnoop.c
This was broken in commit 17ab86c52 as the forced rounding up of the size to 4-byte alignment in BigBuf_malloc made the size check possibly larger than the buffer size as the check was always +3 on the requested size rather than the rounded size. This was made worse by BigBuf_max_traceLen not taking into account alignment either and the alignmentn check in hfsnoop.c checking to 2 byte alignment instead of 4 byte alignment.
The alignment size check now checks the size after alignment rounding, and BigBuf_max_traceLen takes into account alignment losses too reducing the need for BigBuf consumers to have to care about alignment.
> Fix hf sniff

- armsrc/appmain.c
- bootrom/bootrom.c
- client/src/comms.c
- include/pm3_cmd.h
CMD_READ_MEM_DOWNLOAD_RAW got automatically included in pm3_cmd.lua.  It then broke lua scripting because some versions of lua don't like the bit shift in the value.
Renaming it from CMD_READ_MEM_DOWNLOAD_RAW to READ_MEM_DOWNLOAD_FLAG_RAW so it's not included anymore.
> Rename CMD_READ_MEM_DOWNLOAD flag.

- client/src/cmdhf15.c
Fix "hf 15 info", "hf 15 writedsfid" and "hf 15 restore" supports for "-u UID" option.
> cmdhf15: fix sanity checks (uidlen alone is > 1 when -u is set)

- client/deps/liblua/ldebug.c
CVE-2020-24370 is a security vulnerability in lua. Although the CVE decription in [CVE-2020-24370](https://nvd.nist.gov/vuln/detail/CVE-2020-24370) said that this CVE only affected [lua](https://www.lua.org/bugs.html#5.4.0-11) 5.4.0, according to lua this CVE actually existed since lua 5.2. The root cause of this CVE is the negation overflow that occurs when you try to take the negative of 0x80000000. Thus, this CVE also exists in [proxmark3](https://github.com/RfidResearchGroup/proxmark3).
Try to backport the [fix](https://github.com/lua/lua/commit/a585eae6e7ada1ca9271607a4f48dfb17868ab7b) to the lua in [proxmark3](https://github.com/RfidResearchGroup/proxmark3) since the original fix is for 5.4 and several functions have been changed.
> Backport CVE-2020-24370's patch

- CHANGELOG.md
- armsrc/appmain.c
- client/src/cmdhw.c
Bring back support for detecting both HF and LF reader in mode 1
Add support for switching modes by keyboard
> Improve `hw detectreader`

- client/src/cmdhfmfu.c
Fixed a typo in the help text for `hf mfu rdbl`. Changed `Nlock number to read` to `Block number to read`.
> Fix typo in hf mfu rdbl help text.

- client/src/cmdhfmf.c
I was confused why `hf mf dump` wasn't showing any errors but the dump file was all zeros:
```
[usb|script] pm3 --> hf mf dump
[+] time: 0 seconds
[+] saved 1024 bytes to binary file `/Users/gsgx/hf-mf-D6E6ACDF-dump-001.bin`
[+] saved to json file `/Users/gsgx/hf-mf-D6E6ACDF-dump-001.json`
```
For some reason `PM3_SUCCESS` was being returned from this error path, and the log message was using the `DEBUG` log level. After this PR, it's more clear an error occured:
```
[usb|script] pm3 --> hf mf dump
[-]  iso14443a card select failed
```
> Properly handle "hf mf dump" errors

- client/src/cmdhf14b.c
- client/src/pm3line_vocabulary.h
Added the function `hf 14b restore` to restore dump to 14b card.
Modified `hf 14b reader` to make it show the plot like the reader for 14a does.
Modified `hf 14b wrbl` because previously if no flag for the tag size was given it worked even out-of-range but printed that was working with a SRI512 tag.
> Added 14b restore, modified 14b reader,wrbl

- Makefile.platform.sample
- armsrc/util.h
- common_arm/Makefile.hal
- include/config_gpio.h
Added parameter `LED_ORDER` in Makefile.platform to correct led GPIO on Proxmark3 Easy board.
When setting `LED_ORDER=PM3EASY`, the LEDs get configured in the right order for this board, allowing correct binary counting of standalone modes and nice animations (SpinUp and SpinDown).
> Added led order parameter (for Proxmark3 Easy board)

- doc/cloner_notes.md
- doc/magic_cards_notes.md
Some issues were found in the current doc.
Changes in that PR: 
- Updated commands for magic cards (from `hf 14a info` to `hf mf info`)
- Added the usage of commands which were adjusted for GDM (like `hf mf gdmcfg`)
- Added parsed config for well-knows species of `USCUID` tags
- Fixed typos (like `hf mf raw`)
- Links fixes in header (OTP 2.0 link was broken + one "dead" link was present)
- Made a soft linting of MD for style consistency and readability in the editor mode
- Updated info about UL-5, based on the official communication from the manufacturer
The main work is described above. If you have any comments/suggestions - pls, let me know.
> WIP: Magic card docs editing

- doc/T5577_Guide.md
In part 2 of the T5577 guide we create an EM4100 with an ID of 1122334455, and then check that we are successful.  The sample shown to check against does not match and is for an EM4100 with ID of 0F0368568B.
- Removed dump of EM4100 with ID: 0F0368568B
- Added dump of EM4100 with ID: 1122334455
> Update to sample dump part 2 of T5577_Guide.md.

- .gitignore
For example, I have my own makefiles named:
* `Makefile.platform.RDV4`
* `Makefile.platform.PM3Easy`
I can imagine similar options others might then be able to create, without having to remember to always remove those files from any commit / push / PR, such as:
* `Makefile.platform.PM3Easy_NoFlash`
* `Makefile.platform.PM3Easy_WithFlash`
* `Makefile.platform.PM3X`
* etc.
> No code change: .gitignore user's custom Makefile.platform.xxx files

- client/dictionaries/mfc_default_keys.dic
only block one is used, rest of the card is empty. the key is the same on 5 cards I tested (got the key via mfkey32)
> Assa Abloy Hotel System in Spain

- doc/ext_flash_notes.md
I think the last advice to backup is important, but the command does not work. "mem dump p f flash_signature_dump o 262015 l 128" is now "mem dump -f flash_signature_dump -o 262015 -l 128". (OS: Iceman/master/v4.18218)
> Update ext_flash_notes.md - update old backup command

- CHANGELOG.md
- client/luascripts/hf_mf_ultimatecard.lua
- doc/magic_cards_notes.md
This PR mainly sets the max write blocks to 251 before attempting to write either the version or signature in NTAG chips (see 90e9a0da39bed2ba6cb7d686338abafee208520d).
Besides, it changes the UID and signature used in the CLI example so that they match. Currently, using the example signature returns an error, since the format is invalid.
Finally, a trivial typo (`` ` ``instead of `'`) has been fixed.
_This is a purely personal contribution, not related to my current employer whatsoever._
Fixes #2325
> Set max write blocks to 251 in `hf_mf_ultimatecard` before writing version/signature in NTAG 21X

- armsrc/em4x70.c
Fixes the following error messages when using em4x70 tags:
```
[#] Should have a multiple of 8 bits, was sent 65
[#] Should have a multiple of 8 bits, was sent 33
```
The underlying issue is that the manchester decoder was writing one extra bit of data when reading certain tag data.  (_the buffer happened to always be larger than necessary, so did not happen to corrupt data_)
To repro the problem behavior:
`lf em 4x70 --block 12 --data 0xAAAA`
`lf em 4x70 --block 0 --data 8765`
> Decoder must not write more bit than requested

- client/resources/aidlist.json
CEPAS is a (Singaporean) standard for e-money smart cards; it's mainly used for transit, road tolls, and parking payments, but it also sees some use for retail payments and access control.
> Updated aidlist to include CEPAS AID

- client/src/proxguiqt.cpp
Compiling current code shows this error on macOS & Linux Mint. Reverting the one style line change fixes on both.
`src/proxguiqt.cpp: In member function ‘virtual void Plot::paintEvent(QPaintEvent*)’:
src/proxguiqt.cpp:866:47: error: format ‘%zi’ expects argument of type ‘signed size_t’, but argument 6 has type ‘uint32_t’ {aka ‘unsigned int’} [-Werror=format=]
866 |     snprintf(str, sizeof(str), "@%u..%u  dt=%zi %szoom=%2.3f  CursorAPos=%zu  CursorBPos=%zu  GridX=%lf  
... 
make[1]: *** [Makefile:1002: obj/proxguiqt.o] Error 1
make: *** [Makefile:177: client/all] Error 2`
> Fix compile error from variable type declaration

- client/src/cmddata.c
- client/src/cmdlfawid.c
- client/src/cmdlfem4x05.c
- client/src/cmdlfhid.c
- client/src/cmdlfindala.c
- client/src/cmdlfio.c
- client/src/cmdlfparadox.c
- client/src/cmdlfpyramid.c
- client/src/cmdlft55xx.c
- client/src/graph.c
- client/src/graph.h
- client/src/proxguiqt.cpp
- client/src/proxguiqt.h
Not the refactor I _wanted_ to do, but the one I did.
I cleaned up and rewrote how annotations are displayed on the plot window. They are now a lot more flexible and should be easier to add to in the future, since 90% of them are set up and rendered in `Plot::drawAnnotations()`. The only other annotations that are rendered is in the `Plot::PlotGraph()` function, because I really didn't want to redo all the min/max/mean calculations again.
This now has the ability to show up to 4 graphs of min/max/mean numbers, all 4 cursors info (including Operation Buffer changes with CursorA), and has enough space to add future info. Oh, and a lot of the annotations are tied to the state of the objects they track, so if the cursors aren't on screen, those annotations won't show up. Same with the grid, …
> Refactored Plot Annotations and some cleanup

- client/src/cmddata.c
- client/src/cmdhw.c
- client/src/proxgui.h
- client/src/proxguiqt.cpp
- client/src/proxguiqt.h
- client/src/ui.c
Cleaned up and unified the marker code I've been combing through.
- Renamed `CursorXPos` to `g_MarkerXPos` and moved all of them under `ui.h/ui.c` for consistency. It also is a better name for the variables due to them actually being markers and not cursors.
- Made the Marker drawing a bit more flexible by throwing it into its own function. It is now easier to add markers in the future. Note: I need to do that to the Annotation drawing code as well, but I'm not sure if the function should go in `proxguiqt.cpp` or `ui.c` or what. I honestly think it might be better to move the utility functions I've been creating into another file that's suited for that instead of gumming up the `proxguiqt.cpp` file more.
- Extended `data setgraphmarkers` to be able to modify Marker A and B as well as C …
> Marker code cleanup

- client/Makefile
After install of `brew install qt5` compilation with `make clean && make -j` didnt find Qt5 lib. 
I found [this old PR](https://github.com/RfidResearchGroup/proxmark3/pull/1737) that once fixed same issue but by now homebrew changed the lib path, so here is a fix again
> GUI support:       QT5 found, enabled (Qt version 5.15.13 in /opt/homebrew/Cellar/qt@5/5.15.13/lib)
> Fix homebrew Qt5 detection on MacOS

- client/CMakeLists.txt
similar to #2349 but this time for cmake
> -- GUI support:       QT5 found, enabled
> Fix homebrew Qt5 detection on MacOS also for cmake

- client/Makefile
with make by prefering python3-embed over python3 (as CMakeLists.txt does see https://github.com/RfidResearchGroup/proxmark3/blob/master/client/CMakeLists.txt#L488-L500)
fixes #2305
> Fix building against Python3.12 on MacOS 

- .gitignore
- client/CMakeLists.txt
this was missed in #2351 and produces a build warning
I also updated the gitignore with generated artifacts of CMake but could also bring that to a separate PR
> Fix typo in cmake for qt5 detection

- client/src/proxguiqt.cpp
For now, at least until I can fully and correctly implement it.
This should "fix" any weirdness with various commands rendering two graphs.
> Disable Rendering the Operation Buffer

- CHANGELOG.md
- client/src/cmddata.c
- client/src/cmdhw.c
- client/src/cmdlfti.c
- client/src/graph.c
- client/src/proxgui.cpp
- client/src/proxgui.h
- client/src/proxguiqt.cpp
- client/src/proxguiqt.h
- client/src/ui.c
- client/src/ui.h
Did a decent overhaul of the Graph Markers (again, but this time with more features!)
- Moved things around again. The four main markers (A through D) now live in proxgui instead of ui
- Implemented the `marker_t` struct, which currently holds a marker's position and it's label
- Added the ability to set Temporary Markers
- These Markers are only set in code (for now), and are for things like marking noteworthy positions on the graph (like the start of a bit)
Oh, I also fixed a few memory leaks I accidentally introduced 😅
If you want to see what a full implementation of this updated marker system can do, load `lf_TI` and `demod` it.
> Graph Markers, Version 2

- armsrc/appmain.c
In this patch a duplicate header file ``fpga.h`` is removed from ``armsrc/appmain.c``.
> Delete a duplicate header file fpga.h in armsrc/appmain.c

- client/src/cmdhficlass.c
Since elite keys are in a separate dictionary, the helptext should tell the user to call that elite dictionary when checking elite keys.
> update iclass elite key chk helptext

- armsrc/em4x70.c
- client/src/cmdlfem4x70.c
- tools/pm3_tests.sh
This is the first PR related to #2376 .
* Prevents sending corrupt data with minimal code change.
* Fixes em4x70 firmware to return `PM3_*` value (not boolean).  Thanks to @iceman1001 for noting these errors so they could be fixed!
* Adds help text for third key, which is specifically optimized for `lf em 4x70 autorecover`
**NOTE:** MacOS builds fail due to Python install issue.  This is fixed with PR #2380.
Even so, linked are GitHub action results from a branch with **_one extra commit_** that disables the broken HiTag2 test:
* ✅ [Ubuntu Build and Test](https://github.com/henrygab/proxmark3/actions/runs/8961883190)
* ✅ [Windows Build and Test](https://github.com/henrygab/proxmark3/actions/runs/8961883191)
* ❌ [MacOS Build and Test](https://github.com/henrygab/proxmark3/actions/runs/89618 …
> Prevent sending corrupt data to em4x70 w/`--par` option

- client/src/proxguiqt.cpp
This fixes an issue that was found by `gentilkiwi`. I added bounds checking to the marker placing code. I also modified it to run only when a left/right mouse click was made, instead of doing all the math every time the `Plot::MouseMoveEvent()` function was called and then only applying it if there was a mouse click.
> Fix OOB segfault with markers

- CHANGELOG.md
- armsrc/em4x70.c
- client/src/cmdlfem4x70.c
- client/src/cmdlfem4x70.h
- tools/pm3_tests.sh
As requested in Issue #2376, adding unit tests for `lf em 4x70` commands.
Also added new `lf em 4x70 calc` command:  Given a key and 56-bit random value, it will generate the reader challenge (`frn`) and tag response (`grn`).
> add `lf em 4x70 calc` and self-tests

- armsrc/em4x50.c
A "0" bit is half a period no readerfield and half a period readerfield. When read_bit func was called my readers field was still active and it always read a "1". It now waits for 1/4 period before reading the bit to make sure there is no field when reading a "0" bit.
> fixed em4x50_sim_read_bit

- client/dictionaries/mfc_default_keys.dic
Just one key is used. The rest of the card is blank.
I tested on 3 different cards and got through a hardnested attack.
> Inside Wash Membership Card in Portugal

- client/resources/aidlist.json
- client/resources/ecp_taxonomy.json
- client/resources/ecplist.json
Added the following:
* AID:
- Apple Access Key;
- Aliro;
- Navigo.
* ECP:
- Navigo.
* Added ECP taxonomy file, which was missing (I intended to add it when creating ecplist.json initially).
> Add new AID & ECP definitions

- client/dictionaries/mfc_default_keys.dic
Updated gym list; made some minor spelling corrections.
Added Jett's 24 Hour Fitness Sector 0 Keys A/B to the MFC Default Keys dictionary; these keys are static based on testing using inactive credentials purchased on second-hand marketplaces.
Jett's 24 Hour Fitness might also share access keys with Zap Fitness gym tags; however, I am currently unable to test that theory.
Thank you for your time.
> Added Jett's 24 Hour Fitness

- CHANGELOG.md
- client/dictionaries/t55xx_default_pwds.dic
I have a handheld white cloner and a handful of t5577 fobs that were supposedly re-writable but would not wipe. After some sniffing with the Proxmark3 I was able to uncover the password and to wipe the fobs, subsequently using the fobs with the PM3:
```
[usb] pm3 --> lf t55xx sniff
[=] T55xx command detection
[+] Downlink mode           |  password  |   Data   | blk | page |  0  |  1  | raw
[+] ------------------------+------------+----------+-----+------+-----+-----+-------------------------
[+] Default pwd write       |   44B44CAE | 002BCFCF |  7  |   0  |  19 |  46 | 1001000100101101000100110010101110000000000001010111100111111001111111
[+] ---------------------------------------------------------------------------------------------------
```
Picture of the cloner w/firmware version, …
> Add new t55xx password (002BCFCF) sniffed from cheap cloner

- CHANGELOG.md
- armsrc/iso14443b.c
- armsrc/iso14443b.h
See https://github.com/RfidResearchGroup/proxmark3/issues/1652
- Fix Bit Coding PICC -> PCD:  Encoding for 0 and 1 bits were reversed.
- Add a frontend delay for TR0 (No subcarrier) in TransmitFor14443b_AsTag.
- Remove unconditionally prefixing the encoded data with two '1' bits.
- Improve the Type B PICC State Machine implementation.
With these improvements my PCD can read the ISO 14443-B tag emulated by a Proxmark3 Easy.
> Fix ISO 14443-B tag simulation

- client/src/wiegand_formatutils.c
Added an if statement specifically for the handling of C1k48s (48-bit HID) to ensure that the clone and sim functions work as intended. Adjustment does not impact the handling of other card types.
> Updated clone and sim handling for 48-Bit HID (C1k48s)

- client/src/wiegand_formats.c
Some formats were declared with not adequate flags resulting in the format being filtered out for encoding/decoding unless explictly setting it.
> Fix invalid Wiegand format flags.

- CHANGELOG.md
- client/src/cmdhficlass.c
- client/src/cmdhficlass.h
Ported @bettse work from the Flipper Zero Picopass repository to use the lookup function with the VB6 rng as an option.
Limited key generation to the first 5000
> Implemented VB6 rng for iclass lookup elite key search

- CHANGELOG.md
- client/src/cmdhficlass.c
Implemented VB6 rng for iclass chk elite key search based on @bettse implementation on Flipper Zero Picopass app
> Implemented VB6 rng for iclass chk elite key search

- CHANGELOG.md
- armsrc/appmain.c
- armsrc/iclass.c
- armsrc/iclass.h
- armsrc/util.c
- armsrc/util.h
- client/src/cmdhficlass.c
- client/src/cmdhficlass.h
- include/iclass_cmd.h
- include/pm3_cmd.h
Based on the work described in Dismantling iClass whitepaper. 
- `hf iclass legbrute` is tested working on sample data generated accordingly to the hash0 logic.
- `hf iclass legrec ` is partially working: 
1. Logic of operations and sequence are in order 
2. Individual functionalities have been tested on sample/simulated data and was found to be effective and correct.
3. The privilege escalation operation is still NOT working during my tests (may be a silicon issue tho), but the logic in place should be correct.
> Iclass Legacy Raw Key Recovery Function

- armsrc/iclass.c
- armsrc/util.c
- armsrc/util.h
- client/src/cmdhficlass.c
1- Inlined functions related to hf iclass legrec within util.c for marginal performance gains.
2- Fixed bug preventing errors to be displayed properly and the process from interrupting on an error or on completion.
3- Fixed code indentation of the while loop in iclass.c
4- Fixed bug in the while cycle (was missing index++)
5- Improved printing of k1 hex bytes results by using dbhexdump
> Bugfixes and code improvements for hf iclass legrec

- client/resources/aid_desfire.json
**Re-Added Gallagher AIDs**
- The alternative endian Gallagher AIDs have been re-added out of an abundance of caution.
**Added Transact Campus AIDs**
- The AIDs were retrieved from an Institution's Guest Card via `NXP TagInfo` and `PM3`; a Google search revealed that `Transact Card, Inc.` are the ID Card provider for said Institution, so the Institution has not been explicitly named.
> R&Y: Re-Added Gallagher AIDs and Added Transact Campus AIDs

- client/src/cmdhfmf.c
Allows users to collect nt_enc and parity via tag trace for static encrypted nonce attacks.
> Allow static encrypted nonces to be collected via trace

- client/resources/aid_desfire.json
**Added Public Transport AIDs**
- DOH Travel Pass
- JFK OMNY (One Metro New York)
**Updated dormakaba mobile access AID**
- Moved AID from `Transport` section to `PACS` section
- Updated AID `Vendor`, `Name`, and `Description`
> R&Y: Added DOH Travel Pass and JFK OMNY AIDs

- CHANGELOG.md
- client/src/cmdhficlass.c
- client/src/wiegand_formats.c
Added the ability to update emulator memory instead of only writing to card as well as encoding issuance level directly from the encode command.
> Add `--emu` and `--issue` support to `hf iclass encode` 

- client/src/cmdhficlass.c
From thundacatz in Discord.  I did this in the GitHub UI.
> Fix length of credential in `hf iclass sam`

- client/src/cmdlfindala.c
Updated the party from fixed "11" parity to even/odd calculation.
Has worked for every test on both an omnikey and signo reader.
I have tested all single bit FC with CN 1 and all single bit CN with FC 1
Also random range checks with a fixed FC and sequential CN over a range of 10-15 CNs.
> Indala 26 parity

- tools/mkversion.sh
split of https://github.com/RfidResearchGroup/proxmark3/pull/2456
> fix: sha256sum: command not found on macOS

- armsrc/lfops.c
- client/src/cmdlf.c
4 extra symbol.
avoid include SOF in crc-hitag
split of #2456
> fix: lf cmdread. skip WaitMS(100) when keep signal field ON.

- client/src/flash.c
need a bit longer time for macOS to make the port disappear
> fix: enter_bootloader on macOS

- CHANGELOG.md
- client/dictionaries/mfc_default_keys.dic
The anonymous multi-use ticket keys are verified to be static between such cards. I was not able to verify the other two (yellow and blue subscription card) as I only have one of each.
> Add Sofia public transport system keys (before January 2024)

- client/resources/aid_desfire.json
**Added SOF Sofia City Card**
- *Please note that there is no official Bulgarian translation for `Sofia City Card`.*
**Updated MAD Public Transport Card**
- *The `010000` AID is in an alternative endian of `000001`, and has been reflected to show this.*
**Various Formatting Updates**
- *`[` and `]` have been replaced in favour of `(` and `)`.*
Many thanks, and kind regards.
> R&Y: Added SOF Sofia City Card to aid_desfire.json

- client/CMakeLists.txt
- client/experimental_lib/CMakeLists.txt
Corrected an incorrect Readline library URL in client and client/experimental_lib CMakeLists.txt
from ftp://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz Change to https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz
> Corrected an incorrect Readline library URL in client CMakeLists.txt

- client/resources/aid_desfire.json
**Added PACS CA RBH Access Technologies, Inc. AID to `aid_desfire.json`**
- AID added was found from discussions and screenshots on the Server with another Member.
- AID is for their EV1 cards/fobs; they currently only stock EV3 cards/fobs, which potentially could be using a different AID.
- It is assumed *until proven otherwise by the other Member* that the AID is for the BlueLINE range of readers.
Many thanks in advance, and kind regards.
> R&Y: Added PACS CA RBH Access AID to aid_desfire.json

- client/pyscripts/fm11rf08s_recovery.py
In Proxspace or some other specific environments, if the encoding is not specified, an error will occur:
[+] args ''
UID: 23A6D2A0
Getting nonces...
Processing traces...
Loading mfc_default_keys.dic
Traceback (most recent call last):
File "fm11rf08s_recovery.py", line 146, in <module>
for line in file:
UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 506: illegal multibyte sequence
[!] finished fm11rf08s_recovery.py with exception
> fm11rf08s_recovery: Specify the encoding as UTF-8 when opening the MFC dictionary file.

- CHANGELOG.md
- client/src/cmdhficlass.c
The changes were faking the read of AA1 while an invalid key was provided
> Reverted changes to hf iclass dump due to buggy behavior

- tools/pm3_tests.sh
CheckExecute() has a flag to tell it if a check needs opencl support or not and can automatically disable the check if opencl checks are not requested.  Mostly copy and paste the same feature into CheckFileExist and add it where needed.
> add opencl support to CheckFileExist()

- tools/mkversion.sh
While building proxmark3 in an environment without `git` installed, I noticed the following errors on stderr:
```
mkversion create test                   env: 'git': No such file or directory
stat: cannot statx '../README.md': No such file or directory
```
The first line "env: 'git': No such file or directory" is expected, as git is not installed.
However, the second line "stat: cannot statx '../README.md': No such file or directory" is a real error: we're running from top-level directory, so the correct path for README.md is just "README.md".
> mkversion: Fix readme location

- client/src/cmdhficlass.c
- client/src/cmdhficlass.h
Update legbrute to perform a double check when finding a potentially valid raw key, to ensure that is indeed the raw key and works against multiple macs (for the same epurse values).
> Updated hf iclass legbrute

- CHANGELOG.md
- client/deps/hardnested/hardnested_bf_core.c
This is solution provided by @xianglin1998  in #2410.
> Patch for hardnested attack, for avx512f, by @xianglin1998

- CHANGELOG.md
- armsrc/appmain.c
- armsrc/iso14443a.c
- armsrc/iso14443a.h
- client/src/cmdhf14a.c
- client/src/cmdhf14a.h
- include/pm3_cmd.h
Adding the `hf 14a simaid`, this is heavily based on `hf 14a sim` however, has been pulled out of the original and modified to speed up processing of responses during a simulation. 
Simulate ISO/IEC 14443 type A tag with 4,7 or 10 byte UID, and filter for AID Values. These AID Values can be responded to and include extra APDU commands on GetData after response. The Simulation will break once the GetData has been replied to, or if the reader sends a Deselect command. 
Simulate a DESFire tag, and if an AID of `a000000000000000000000` appears, respond with `9000`, and on the next GetData request, respond with a `9000`
`hf 14a simaid -t 3 --aid a000000000000000000000 --response 9000 --apdu 9000`
Simulate a DESFire tag with a custom RATS, and if a GetData request is received, respond with a …
> Adding hf 14a simaid

- armsrc/iso14443a.c
Commit 34e0014 made proxmark ignore reader commands when sniffing. If sniffing with -r flag, it was only recording first WUPA from a reader. This commit fixes this behavior.
> Fix hf 14a sniff ignoring reader commands

- CHANGELOG.md
- armsrc/Standalone/hf_young.c
SimulateIso14443aTag() now requires five arguments, added NULL to all calls in hf_young.c
> Fixed argument count for SimulateIso14443aTag() in hf_young.c

- CHANGELOG.md
- client/src/cmdhficlass.c
- client/src/loclass/ikeys.c
- client/src/loclass/ikeys.h
Added hf iclass unhash based on the document "Exposing iClass Key Diversification" The command works but only handles the "main" scenarios, retrieving only the main 8 of 512 potential hash0 pre-images.
Handling the generation of the additional pre-images is still work in progress.
> Added hf iclass unhash

- CHANGELOG.md
- client/src/cmdhfmfu.c
The last 3 bytes of the 7 byte uid are zeroed out
Tested with the example from the forum http://www.proxmark.org/forum/viewtopic.php?pid=44238#p44238
> fix hf mfu pwdgen for 7 byte uid

- client/src/util.c
For some reason, `isprint()` claims that `0xff` is printable. But it's used by `PrintAndLog` functions as a marker value to suppress the line return.
So when viewing a dump where the last byte of a block/sector is `0xff`, it was suppressing the new line between blocks/sectors. This fixes it by excluding `0xff` from printable values.
> Fix missing line return when viewing dumps

- client/src/cmdhficlass.c
Fixed segmentation fault error from commit 6264b1df9af5fbc5ab64b64ea0dd092cc16757f6 when trying to generate config cards.
> Fixed config cards segmentation fault

- CHANGELOG.md
- armsrc/Standalone/hf_aveful.c
- armsrc/Standalone/hf_craftbyte.c
Just a quick fix to the build (+ CHANGELOG). I adapted the change from `hf_young.c` (just added a NULL pointer), but didn't dive into the code to figure out if this is the best approach or not.
btw, thanks for the tool + code!
Original error:
```
[-] CC ../armsrc/Standalone/hf_aveful.c
../armsrc/Standalone/hf_aveful.c: In function 'RunMod':
../armsrc/Standalone/hf_aveful.c:254:17: error: too few arguments to function 'SimulateIso14443aTag'
254 |                 SimulateIso14443aTag(7, flags, card.uid, 0);
|                 ^~~~~~~~~~~~~~~~~~~~
In file included from ../armsrc/Standalone/hf_aveful.c:44:
./iso14443a.h:143:6: note: declared here
143 | void SimulateIso14443aTag(uint8_t tagType, uint16_t flags, uint8_t *data, uint8_t exitAfterNReads, uint8_t *iRATs);
|      ^~~~~~~~~~~~~~~~~~~~ …
```
> Fix hf_aveful.c: too few arguments to function 'SimulateIso14443aTag'

- CHANGELOG.md
- armsrc/Standalone/hf_cardhopper.c
- armsrc/Standalone/hf_msdsal.c
- armsrc/Standalone/hf_reblay.c
- armsrc/Standalone/hf_tcprst.c
Added NULL as `uint8_t *iRats` to all invokations in armsrc/Standalone.
Not sure if that is the right thing to do: The actual code checks for the presence of a special flag, but does not contain a check for NULL. IMHO adding a NULL check in `iso14443a.c` line 1259 wouldn't hurt, and could catch programming errors (flag set by accident, but NULL passed).
Maybe @evildaemond wants to verify whether my fix does the right thing or if I missed something (they added the iRATs to `iso14443a.h` with 56324b16b2).
> Fix SimulateIso14443aInit usage

- CHANGELOG.md
- client/pyscripts/mf_backdoor_dump.py
Simple python script that uses the backdoor keys from `fm11rf08s_recovery.py` script to quickly dump the tag contents that those keys can directly read. 
Really handy if you just want to read the tag data without waiting 15 minutes to crack the real keys.
> Add mf_backdoor_dump script

- client/pyscripts/mf_backdoor_dump.py
Add support for dumping backdoor'ed 4k tags as well, thanks to a tip from @doegox 
Also added a more robust error check to catch general unexpected outputs.
> mf_backdoor_dump.py: 4k tag support, additional error check

- CHANGELOG.md
- client/src/cmdlfem4x50.c
affected `lf search` and `lf em 4x50 rdbl -b <blk>`
```
[usb] pm3 --> lf em 4x50 rdbl -b 3
Thread 10 "WorkerThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdefff700 (LWP 2592)]
em4x50_prepare_result (words=0x7fffdeffe310, lwr=3, fwr=<optimized out>, data=<optimized out>)
```
```
[usb] pm3 --> lf search
Thread 10 "WorkerThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdefff700 (LWP 3091)]
em4x50_prepare_result (words=0x7fffdeffe340, lwr=32, fwr=<optimized out>, data=<optimized out>)
at /home/ant/src/RF/Proxmark3/pm3/client/src/cmdlfem4x50.c:40
40	            words[i].byte[j] = data[i * 4 + (3 - j)];
```
> fix em4x50_read function

- CHANGELOG.md
- tools/mfd_aes_brute/Makefile
The compiler don't support `march=native` / `mcpu=native` on risvc64, either. This fix the compile failure on riscv64.
Reported-by: https://archriscv.felixc.at/.status/log.htm?url=logs/proxmark3/proxmark3-4.18589-1.log
Refactor the way that detect whether `march=native` / `mcpu=native` are supported on the platform, following the comment.
Add an option `DONT_BUILD_NATIVE` to suppress building with `march=native` / `mcpu=native`. For building it someone-self, it is helpful to generate the fastest binary, but for Linux or some other operating system distribution package maintainer, it is over optimized. We may build and package this software on a machine that is `x86_64-v3` but distribute it to a user that using an old hardware like `Intel Atom`, and result in a `SIGILL`.
Already tested it …
> feat: detect march and mcpu

- armsrc/mifarecmd.c
There are some tags with static nonce in which the offset between the first (plain) nonce and the encrypted (nested) ones is 0 instead of 160. On these tags the staticnested failed silently, now we make a check, if the plain nonce is equal to the nested one (after unencryption), we force the distance to 0 overriding the prng successor, in this way the attack works.
> Static Nested for cards with offset 0

- client/luascripts/hf_mf_ultimatecard.lua
The ultimate magic gen 4 tags with version 06a0 use the value of 04 (instead of 01) to activate the shadow mode, as stated in the documentation. While it was possible to send this value using the raw command, the lua script rejected it, now instead we can use the 04 value and it gets correctly recognised and sent to the tag.
> Shadow mode support for 06a0 ultimate magic tags

- CHANGELOG.md
- armsrc/Standalone/hf_young.c
Missing a semicolon, prevented compiling if hf_young was set as Standalone mode
> Fixed syntax error in flags declaration in hf_young.c

- armsrc/mifarecmd.c
The distance between nonces was hardcoded in the static nested attack, but in that way the attack failed against cards with a different distance between nonces (other than 160 or 0). Now we measure the distance before making the attack, we do a first auth, then a nested auth on the same sector and finally another nested auth on the same sector. In this way we can calculate the distances (nt2 - nt1) and (nt3 - nt1) and use them to make the attack. It was successfully tested on both cards with 160 and 0 distance and it takes the same amount of time as before, so we can conclude that the attack should now work even against cards (present or future ones) with different distances
> Static nested auto distance measurement for nonces

- doc/magic_cards_notes.md
Update which includes new developments with USCUID-ULs and amended language for clarity.
- Added new discovery by @Eltrick which specifies tearing counters in hidden blocks F2-F4
- Cleared up some language regarding turning on CUID mode, including fixing incorrect A0 to turn it on instead of the correct 0A.
- Added anticoll settings for hidden block F6, thanks to @AnnPlusPlus
> Update to fix some small USCUID-UL errors and add new developments

- client/pyscripts/mf_backdoor_dump.py
In this patch an extra whitespace character in mf_backdoor_dump.py will be deleted. 
This blank character prevents the for loop from trying the next backdoor key.
> Delete extra whitespace character in mf_backdoor_dump.py

- armsrc/hitagS.c
tested with a hitagS transponder.
one could also reverse rnd when initializing the state, but this way it is in the same order as previously
> lf hitag hts: use correct byteorder for authentication

- client/src/cmddata.c
The examples shown in the help output were referencing "envelop" instead of "envelope"
> Fix typo from envelop to envelope

- client/src/cmddata.c
The example shows a formatting that the command actually does not support, `0x` in front of the value returns an error. This was true since the inception of the command, and it seems easier to keep the functionality the same instead of changing the logic. At the same time, changing the logic would ideally also mean converting from binary should follow the same type of formatting (prepending with `0b`).
Changed the value in the example a bit at the same time to make sure the distinction is still visible between a hex and decimal value, just for the fun of it.
> Show correct example for `data num --hex`

- CHANGELOG.md
- client/dictionaries/t55xx_default_pwds.dic
Bought one of these cool little rings.  It has two integrated t55x clone chips (among others), however they come pre-password protected and the tradition test mode wipes didn't seem to unlock them.  I was able to unlock them with passwords in their manual (http://www.jakcom.com/ins/r5/r5en.html) and so I thought they would be good to add to the dictionary.
> Add JAKCOM R5 smart ring t55x default passwords

- armsrc/Standalone/hf_cardhopper.c
- common_arm/usb_cdc.c
- common_arm/usb_cdc.h
if packets arrive in quick succession part of the next packet can sit in the buffer which isn't checked by cardhopper resulting in the standalone hanging. this makes it check for data in the internal buffer too preventing that condition.
I expect the same benefit may occur in `recieve_ng` (sic) by changing the `usb_poll_validate_length()` check to be `usb_read_ng_has_buffered_data() || usb_poll_validate_length()` as this does in the cardhopper standalone but it'd need more testing. I've been testing this change with cardhopper for a few months now and I'm confident it's good but haven't tested the same change in `recieve_ng` yet
> improve cardhopper to improve reliability when parts of the packet are buffered

- client/src/proxmark3.c
this replaces the old behaviour of using a fixed length of spaces which can sometimes fail to clear the entire line if it's too long
> clear the prompt using ANSI "clear entire line" escape

- common_arm/ticks.c
this could happen if TC2 was already 0 when it was started or reset resulting in the initial reset not happening until TC0 had overflowed for the first time as the delay to ensure this didn't happen would be missed when TC2 was already 0
the new behaviour results in TIOA0 being toggled when a software trigger of TC0 happens which makes TC2 reset immediately without having to wait for TC0 to overflow
I tested this quite thoroughly with all the edge cases I could think of around calls to `StartCountSspClk` and `ResetSspClk` and it seems to be doing the right thing now in all cases (eg TC2 starts at 0 after either function returns and increments exactly once each time TC0 overflows regardless of the initial value of TC2 when when the functions are called).
This fixes #2611 - I suspect the …
> fix ssp_clk sometimes resetting to 0 shortly after being started or reset

- CHANGELOG.md
- client/src/cmdhficlass.c
Fixed elite configcard generation. From nfc-iclass and other resources block 13 generation was completely missing. This resulted in configcards for legacy readers to be working on Rev.A readers but not Rev.C readers when it came to setting elite keys or enabling keyrolling.
> Fixed elite configcard generation

- CHANGELOG.md
- armsrc/iclass.c
Improved algorithm for hf iclass legrec by taking in account the hash0 limitations for the ending bits distributions of each key bite, thus reducing the key entropy and number of required tries from 2^24 to almost 2^19
> Improved algorithm for hf iclass legrec

- client/pyscripts/fm11rf08_full.py
- client/pyscripts/fm11rf08s_recovery.py
Beyond the original recovery script (used by this script) this script performs a number of tasks to aid us teaching NFC at our local defcon meet.
qv. https://eprint.iacr.org/2024/1275.pdf [Philippe Teuwen]
+ Full breakdown of Block 0 (esp. Fudan specific details)
+ Verify UID/BCC
+ SAK decode
+ Optionally perform online Fudan validation check
+ [[key recovery]]
+ Dump all 64+8 blocks
+ ...with all 32+2 keys
+ Decode ACL [clearer output]
+ [[MAD decode]]
+ Bambu tag decode
+ Create full 64+8 block dump (incl keys) ...for the CTF flag
> Fudan FM11R08* full-card recovery script; with Bambu tag support

- armsrc/iclass.c
Fixed legrec bug that was generating blank keys after one line of code misalignment in commit: 110dfab668307ba2ed5f320bf6ea6200f9a91a97
> Fixed keygen bug in legrec

- client/src/cmdhficlass.c
Fixed error messaging that was swapped between card key and keyroll key
> Minor hf iclass configcard fixes

- client/src/cmdhfmf.c
- client/src/mifare/mifarehost.c
- client/src/mifare/mifarehost.h
`src/mifare/mifarehost.[c/h]` implements `mfReadBlock` and `mfReadSector` so I was expecting to also find `mfWriteBlock` and `mfWriteSector`, but they don't exist. Looking a little further and `cmdhfmf.c` used a static `function static bool mf_write_block` for this. 
As I want to use it in a hf gallagher extension I'd like it to not be static.
The other similar functions mentioned above return a PM3 status enum rather than bool's, so I also lightly refactored the uses of `mfWriteSector` to check for `PM3_SUCCESS` or similar.
I did read
> Function names should be separated_with_underscores(), except for standard functions (memcpy, etc.). It may make sense to break this rule for very common, generic functions that look like library functions (e.g. dprintf()). 
However the other functions …
> Move and Rename Static Mifare Classic Write Block Function

- CHANGELOG.md
- client/src/cmdhficlass.c
Documented and added an extensive list of configcards available and functionalities.
- Led Operations (A8 byte) are now fully documented (up from 2)
- Added : Beep Operations
- Elite Key Operations fully documented (3 up from 2)
-Added potential other bytes pending full documentation / discovery
-To Add: Reader Master Key Operations and Erratic Operations
While initially I was trying to maximize backward compatibility with cardhelper, the way its functions were linked and engrained in the code, caused a constant flow of errors and did not allow the flexibility to easily expand the list of cards. Maintaining that code would lead to creating multiple duplicate functions with no real added value perceived (except increased complexity of the code and difficulty to continue maintaining its …
> Updated hf iclass configcard

- doc/magic_cards_notes.md
Update contains the following changes:
- Remove reference to Magic85 chip (was the nomenclature before the USCUID term was coined)
- Update notes on FUID chips, as there have been some spotted that have had the config block locked down, making them truly write once
> Update to include new style FUID chips, and fix an old nomenclature

- client/pyscripts/fm11rf08_full.py
- client/src/cmdhfmf.c
MAD data is not autodetected unless keys are recovered.
With the FM11RF08S (and siblings) it is possible to retrieve the data and never know the keys.
If the data is MAD, but the keys are missing `hf mf mad` refuses to decode the data.
This patch adds the `--force` switch to the core functionality, and `--mad` to fm11rf08s_full.py so the user can decode MAD data even when the keys are not known.
> Ability to force MAD decode

- armsrc/Standalone/hf_young.c
- client/src/cmdhfict.c
- client/src/cmdhfjooki.c
- client/src/cmdhfmf.c
- client/src/cmdhfmfp.c
- client/src/mifare/mifarehost.c
- client/src/mifare/mifarehost.h
- client/src/scripting.c
Based on the discussion in [Move and Rename Static Mifare Classic Write Block Function](https://github.com/RfidResearchGroup/proxmark3/issues/2624), I've re-styled the functions to match [Style Guide](https://github.com/RfidResearchGroup/proxmark3/blob/master/CONTRIBUTING.md#fonctions)
> Style src/mifare/mifarehost

- CHANGELOG.md
- Makefile.defs
- client/Makefile
- doc/md/Use_of_Proxmark/0_Compilation-Instructions.md
- docker/opensuse-leap/Dockerfile
Tested in the following docker containers
* opensuse-leap - just `make` is failing, `make PYTHON3_PKGCONFIG=python-3.11` succeed
* opensuse-tumbleweed - just `make` succeed, as expected
* debian-13-trixie - just `make` succeed, as expected
So, the patch is properly activated only when the make variable is defined
> add option to build against non-default python3 package

- docker/opensuse-leap/Dockerfile
@doegox  forgot to restore the opensuse-leap/Dockerfile changes when reworking commit https://github.com/RfidResearchGroup/proxmark3/commit/39c846ada4832a874a1744bc45851b385857f6cb
> revert opensuse-leap docker to default Python 3.6

- CHANGELOG.md
- armsrc/mifaresim.c
This change causes `hf mf sim` not to respond for auth attempts for sectors that are out of range for a selected mifare type.
This prevents some readers to always identify simulated card as Mifare Classic 4k
Resolves #2635
> Do not respond to mifare simulation sectors out of bounds

- CHANGELOG.md
- armsrc/spiffs.c
the used strtok(...,".")` is cutting the name to the first dot linkname.txt.lnk -> linkname
with the fix it is
linkname.txt.lnk -> linkname.txt
> fixed symlink name in mem spiffs tree

- CHANGELOG.md
- client/luascripts/hf_mf_ultimatecard.lua
As this was not covered before in the script mentioned I made few changes:
1. Added display of maximum read/write block to read magic configuration option
2. Added `-b` argument to set maximum read/write block
3. Needed to split argument string because reached lua maximum string length
4. Refactored help for `-t` option to increase readability, because already reached the limit explained above
Tested with two exactly same unbranded UMC's I own.
> Add option to set and get maximum read/write block number using hf_mf_ultimatecard script

- client/src/cmdhfmfu.c
- There is no read tearing command in the NTAG datasheet
> 'hf mfu incr' to increment counters of UL-EV1 family; Also fix reading of NTAG counters in 'hf mfu info'

- client/resources/aid_desfire.json
- Updated Vendor to its legal name (Masabi Ltd).
- Added a standardised description to identify the AID as being issued by Masabi Ltd for its Justride platform.
Thank you.
-R&Y.
> R&Y: Updated DEN MyRide AID in aid_desfire.json

- CHANGELOG.md
- client/src/mifare/desfirecore.c
- client/src/mifare/desfiresecurechan.c
I noticed D40 secure channel auth was broken. The original D40 silicon can only perform encryption operations so any data encryption PCD side must be done with the DES decrypt primitive. MAC calculation still needs to be done with the DES encrypt primitive though.
I added a couple of comments which should help the next person touching the code too.
Due to a weird quirk of DES that I only learnt just now, DES encryption with a key of all zeros is identical to DES decryption with  key of all zeros so the issue doesn't exhibit if you're testing with a factory defaulted card using zero'd keys, but it's easy enough to change the keys to test.
Previous broken behaviour shown below, note this is against a DESFire EV2 card, so can use EV1 auth to verify the keys are correct, while the D40 secure …
> fis MF3ICD40 (D40) secure channel crypto

- CHANGELOG.md
- doc/ext_flash_notes.md
- doc/md/Use_of_Proxmark/0_Compilation-Instructions.md
- include/pmflash.h
This extends reserved area in SPI flash memory (RDV4.x, some PM3 Easy devices) from 2047 keys to 4095 keys.
Also updates related documentation.
Tested to work correctly on Proxmark3 RDV4.01
> SPI flash area for Mifare keys extended from 2047 to 4095 keys

- CHANGELOG.md
- armsrc/appmain.c
Fixing bug I created by #2683 
In the original PR I forgot to erase extended area before keys were written.
The bias was created by testing my solution on a blank flash area, and during testing I never changed number of keys nor dictionary contents.
> Fix: SPI flash area for Mifare keys extended from 2047 to 4095 keys - not all sectors are erased

- client/dictionaries/mfc_default_keys.dic
i imagine these were missed due to different capitalization, if there is any automated checking it may be worth making it case insensitive when looking for duplicates
> Remove duplicate keys

- client/deps/hardnested/hardnested_bf_core.c
It seems like a condition was mistakenly duplicated while applying the patch for https://github.com/RfidResearchGroup/proxmark3/issues/2410. This PR removes it.
> Remove condition duplicated in PR #2530

- client/src/cmdhf15.c
- doc/commands.json
Fix a couple of small typos with the file name format for the `hf 15 view` command. This proposed formatting matches the file name format that is produced by dumps.
> Fix `hf 15 view` command examples

- CHANGELOG.md
- client/src/cmdlfem410x.c
This changes default gap for simulating em410x tags to zero, as many readers except a looped, uninterrupted stream of data, as many original tags present.
This also extends built-in help to mention this behavior.
This change addresses discussion under #2197
> lf em 410x sim - default gap value of 0, extend help

- CHANGELOG.md
- armsrc/appmain.c
- armsrc/lfops.c
- armsrc/mifarecmd.c
- client/src/cmdflashmem.c
- client/src/mifare/mifarehost.c
- common_arm/flashmem.c
- common_arm/flashmem.h
- doc/ext_flash_notes.md
- include/pmflash.h
This change moves flash-stored key dictionaries (Mifare, iClass and T55XX) from statically allocated area at the end of FLASH memory to a file located under SPIFFS file system.
This also implements automatic writing of the keys to SPIFFS using legacy methods.
Things to note:
- Currently there seem to be no implementation/use of iClass keys stored in flash, so this change only transfers all the keys to SPIFFS file
- In the future it will be a good idea to consider extension of SPIFFS into the last page of FLASH, as currently most of the page is left blank.
- The change was tested using Proxmark3 RDV4.01 and some Mifare Classic 1k cards and some T5577 tags.
- Cross-testing by other users would be more than welcome.
> Move keys library to spiffs

- CHANGELOG.md
- client/src/cmdhfmf.c
- doc/cheatsheet.md
This is because hf mf autopwn is the most used command and this can be used as "taking notes", to prevent causing a not sortable file list after long time use. 
usage:
`hf mf autopwn -o front_door`
`hf mf autopwn -o "front_door"`
> Add custom suffix for hf mf autopwn to -o argument

- client/pyscripts/fm11rf08s_full.py
Revise 'RF08S_full' script to NOT attempt to recover a card it does not support (v1.4)
I tried to add support for other cards to it, but the code just isn't up to it.... Different block counts, variable sector sizes, bespoke code for certain blocks ...it would probably be prudent to abstract the KDF & decode functionality too.
I plan to develop a more structured approach that will present a more adaptable solution to the problem.
I now have a modest selection of card/chips/tags, so I need to start reading datasheets and work out what other quirks are hiding in the bushes - eg. I never anticipated variable sector sizes!
> Revise "full" recovery script

- client/src/cmdhfseos.c
- client/src/cmdhfseos.h
Added generic SEOS Support with the following commands;
- `hf seos info` (slightly improved from the original)
- `hf seos pacs` (return the SIO value from the default ADF and default tag)
- `hf seos adf ` (send a get data request to an ADF with a custom tag list)
- `hf seos gdf` (make a request for a GDF based upon a command found in their docs)
- `hf seos managekeys` (manage your own keys used for SEOS commands)
You still need keys to use this commandset, this does not have any keys and is theoretical at this stage until someone tests it with the keys.
> Added SEOS Support

- .github/workflows/codeql-analysis.yml
- .github/workflows/rebase.yml
To fully validate a fix, it is necessary for a fork to manually initiate CodeQL.
(there's a hack by doing a draft PR to one's fork's main branch, but ...)
This simply allows the action to be manually initiated (`workflow_dispatch`).
EDIT: Added condition so the CHANGELOG.md reminder is only added for the official depot.
> Allow manual initiation of CodeQL

- .github/workflows/codeql-analysis.yml
- armsrc/spiffs.h
- armsrc/spiffs_check.c
- armsrc/spiffs_hydrogen.c
- armsrc/spiffs_nucleus.c
- armsrc/thinfilm.c
- client/src/cmdhf14a.c
- client/src/cmdhfmf.c
- client/src/cmdlfem410x.c
- client/src/cmdlfem4x50.c
Many of the CodeQL bugs of type "Comparison between A of TypeA and B of wider type TypeB" were caused by having arithmetic within a `for()` loop's comparison clause.  Not only were the operations redundant, but they could cause unintended consequences (e.g., integer promotion rules).  Relatively simple to fix (use larger of two sizes for loop variable, compare unsigned vs. unsigned, etc.).
The other reason for many of these was that spiffs, in the definition of `struct spiffs_t`, defined field `block_count` of type `uint32_t`, but defined field `free_cursor_block_ix` to be of type `spiffs_block_ix`.  In PM3, `spiffs_block_ix` is defined as `uint16_t`.  Thus, a variable of type `spiffs_block_ix` cannot directly loop against `block_count` (potential infinite loops).
Inline "conversation"s …
> CodeQL -- Actual fixes

- client/src/cmdhf14a.c
`size_t` uses the `%zu` (or `%zx`) specifier.
> Fix printf() mismatch

- armsrc/BigBuf.c
- armsrc/Standalone/hf_bog.c
- armsrc/hitag2.c
- armsrc/hitagS.c
- armsrc/iso14443a.c
- armsrc/iso14443b.c
- armsrc/iso15693.c
- armsrc/lfops.c
- armsrc/mifarecmd.c
- armsrc/mifaresniff_disabled.c
* BigBuf.c: use s_ prefix for statics
* BigBuf_Clear_ext already calls clear_trace, so remove extra calls
* add some sanity checking of allocator args
* dont compare PDC_RNCR to false
> fix bigbuf allocators (tracing + malloc) overwriting each other

- client/luascripts/t55_chk_date.lua
A simple script for searching the password for T5577. The script creates a
dictionary starting from the entered starting year to the entered ending year.
There are two search methods - DDMMYYYY or YYYYMMDD. Checking the entire year
takes about 1 minutes and 50 seconds. Date from 1900 to 2100. The script may be
useful if the password is for example date of birth.
> Script for searching the password for T5577

- client/luascripts/t55_chk.lua
Author: jareckib - created 02.02.2025
version v1.00
A simple script for searching the password for T5577. The script creates a
dictionary starting from the entered starting year to the entered ending year.
There are two search methods - DDMMYYYY or YYYYMMDD. Checking the entire year
takes about 1 minute and 50 seconds. Date from 1900 to 2100. The script may be
useful if the password is, for example, a date of birth.
Usage:
script run t55_chk [-s start_year] [-e end_year] [-d | -y]
Options:
-h                    Show this help message
-s                    Starting year (required)
-e                    Ending year (default: current year)
-d                    Search method: DDMMYYYY
-y                    Search method: YYYYMMDD
Examples:
script run t55_chk -s 1999 -d             - start …
> t55_chk_lua

- client/src/cmdlfhid.c
- client/src/wiegand_formats.c
- client/src/wiegand_formats.h
In  `lf hid brute` command, there's a checking on the range of facility code and card number to determine when it should stop. The original code (`card_hi.FacilityCode < 0xFF` and `card_hi.CardNumber < 0xFFFF`) does not account for different card formats.
Fix it by pulling the corresponding card format limit from FormatTable.
> Fix facility code and card number checking in LF HID Brute

- CHANGELOG.md
- doc/magic_cards_notes.md
iKey has released https://ikey.ru/mf4 tags for sale.
These are a custom magic IC, as such a new section for it was added in the magic cards documentation.
If a functionality check is needed - I can send screenshots/other media.
> Document MF4 tags

- client/src/wiegand_formats.c
- client/src/wiegand_formats.h
Per suggestions from @iceman1001 ->[PR](https://github.com/RfidResearchGroup/proxmark3/pull/2741)
1. Update the following range checking of all pack functions
```
static bool Pack_Tecom27(wiegand_card_t *card, wiegand_message_t *packed, bool preamble) {
...
if (card->FacilityCode > 0x7FF) return false; // Can't encode FC.
if (card->CardNumber > 0xFFFF) return false; // Can't encode CN.
if (card->IssueLevel > 0) return false; // Not used in this format
if (card->OEM > 0) return false; // Not used in this format
...
```
with
```
static bool Pack_Tecom27(int format_idx, wiegand_card_t *card, wiegand_message_t *packed, bool preamble) {
...
if (!validate_card_limit(format_idx, card)) return false;
...
```
2. No changes to unpack functions (considering code readability + not necessary for all), …
> Update range checkings in all pack functions for LF HID

- armsrc/lfops.c
- client/src/cmdhficlass.c
- client/src/cmdhfmf.c
- client/src/cmdlfhid.c
- client/src/cmdwiegand.c
- client/src/wiegand_formats.c
- client/src/wiegand_formats.h
- client/src/wiegand_formatutils.c
Original issue: it's hard to detect 26-36 bits (with sentinel), 37 bits (no sentinel), and 38 bits. Also, a 26 bits format can be interpreted as 38 bits as well. The current master cannot display 37 bits format correctly. Per [issue #1773](https://github.com/RfidResearchGroup/proxmark3/issues/1773) and [issue #2727](https://github.com/RfidResearchGroup/proxmark3/issues/2727) (this is fixed already).
Issue reproduced: H10304 37 bits format, fc: 1234, cn: 56789, raw: 104d21bbaa
```
pm3 --> lf hid reader
[+] [HCP32   ] HID Check Point 32-bit             CN: 10109815
[+] [HPP32   ] HID Hewlett-Packard 32-bit       FC: 2468  CN: 116303872
[+] [Kastle  ] Kastle 32-bit                    FC: 144  CN: 56789  Issue: 6  parity ( fail )
[+] [Kantech ] Indala/Kantech KFS 32-bit        FC: 144  CN: …
```
> Fix Incorrect Wiegand Format Displayed

- client/resources/aid_desfire.json
This PR adds AID values used by UniFi Access DESFire-based credentials, in particular:
- Physical credentials:
* FCD
* VID
* ACC
- Mobile credentials:
* UIE 
* UIS   
In addition to that, a missing entry for newer Clipper AID, used by mobile Wallets, was also added.
> Add new AID entries to `aid_desfire.json`

- client/src/cmdhfmfdes.c
* Add known Apple Wallet DESFire hardware version info to known variants in `getCardType` function to prevent `CmdHF14ADesInfo` from bailing out on it.
* Fix `getProductType` and `getProductTypeStr`, which incorrectly interpreted documentation referenced above the function, accessing ProductInfo at "byte 2" via `[2]` instead of `[1]`.
> Fixes to DESFire product type recognition

- doc/md/Installation_Instructions/macOS-Homebrew-Installation-Instructions.md
> add helpful note for macos users failing linking

- armsrc/Standalone/lf_hidbrute.c
- armsrc/Standalone/lf_hidfcbrute.c
- armsrc/Standalone/lf_prox2brute.c
- armsrc/lfops.c
- armsrc/lfops.h
1. Per issue at https://github.com/RfidResearchGroup/proxmark3/issues/1791 with regard to the Incorrect encoding for C1k48s with HID preamble. For this issue, @tweathers-sec submitted a [PR](https://github.com/RfidResearchGroup/proxmark3/pull/2407) fixing the HID header of C1k48s of add_HID_header() function in wiegand_formatutils.c.
**However**, since the long format identifier "9E" is added again in "CopyHIDtoT55x7" and "CmdHIDsimTAGEx" function in armsrc/lfops.c, the problem persists. Example:
```
pm3 --> lf hid clone -w C1k48s --fc 12345 --cn 12345
[=] Preparing to clone HID tag
[+] [C1k48s  ] HID Corporate 1000 48-bit std    FC: 12345  CN: 12345  parity ( ok )
[+] Done!
[?] Hint: try `lf hid reader` to verify
[usb] pm3 --> lf hid reader
[+] [C1k48s  ] HID Corporate 1000 48-bit std …
```
> Fix incorrect encoding for HID with long format on sim and clone

- client/src/cmdwiegand.c
- client/src/wiegand_formats.c
- client/src/wiegand_formatutils.c
This pull request:
1. Fixes bitlen miscalculation issue
* The sentinel bit is removed in get_length_from_header function
* Fix decoding wiegand format with sentinel bit included
2. Refactors implementation using the decode_wiegand function for improved clarity
> Correct Bitlen Calculation and Refactor Wiegand Decoding

- client/src/cmdhfseos.c
I noticed the default values in the source didn't match to the default values in the help text for these two commands
https://github.com/RfidResearchGroup/proxmark3/blob/master/client/src/cmdhfseos.c#L1363-L1370
https://github.com/RfidResearchGroup/proxmark3/blob/master/client/src/cmdhfseos.c#L1416-L1427
> Correct oid_hex for hf seos adf and hf seos pacs

- client/luascripts/lf_t55xx_multiwriter.lua
This simple script stores 1, 2 or 3 different EM4102 on a single T5577.
There is an option to enter the number engraved on the fob in decimal form.
The script can therefore be useful if the original EM4102 doesn't work but 
has an engraved ID number. By entering such an ID as a single EM4102, we 
can create a working copy of our damaged fob.
A tag T5577 created in this way works with the following USB readers:
- ACM08Y
- ACM26C
- Sycreader R60D
- Elatech Multitech TWN4
> lf_t55xx_multiwriter

- CHANGELOG.md
- armsrc/mifarecmd.c
- client/src/cmdhfmf.c
Instead of randy's special, now there's a jump special: `hf mf autopwn --mem` 😁 
I also tweaked a bit the logic because using SPI flash dictionary was discarding KDF keys as well as the 64 hardcoded ones.
So now, it merges both in memory. And I applied the same logic to `hf mf fchk`
> Add option to use SPI flash dictionary for autopwn

- client/resources/aid_desfire.json
- `0854DF`: Gantner locker credentials.
- `F473A0`: Securitron DESFire EV2 credentials.
- `000001`: Updated MAD to original Spanish name.
- `010000`: Updated MAD back to Alternative Endian designation.
Thank you.
-R&Y.
> R&Y: Added PACS AIDs & Updated MAD TTP AID

- client/resources/aid_desfire.json
- SOF Sofia City Card's AID (reversed the endian).
Apologies for the last-minute PR.
-R&Y.
> R&Y: Updated SOF Sofia City Card AID in `aid_desfire.json`

- doc/magic_cards_notes.md
> Improve magic tags notes

- client/src/cmdhfmfdes.c
`hf mfdes bruteaid` was mixing byte order in the arguments:
Before fix:
```
[usb] pm3 --> hf mfdes bruteaid --start 0000F0 --end 000100
[!!] 🚨 Start should be lower than end. start: f00000 end: 000100
```
After fix:
```
[usb] pm3 --> hf mfdes bruteaid --start 0000F0 --end 000100
[=] Bruteforce from 0000f0 to 000100
[=] Enumerating through all AIDs manually, this will take a while!
🕙 Progress: 100 %, current AID: 000100
[+] Done!
[usb] pm3 --> trace list -t des
[+] Recorded activity ( 811 bytes )
[=] start = start of start frame. end = end of frame. src = source of transfer.
[=] ISO14443A - all times are in carrier periods (1/13.56MHz)
Start |        End | Src | Data (! denotes parity error)                                           | CRC | Annotation …
```
> hf mfdes bruteaid: fix byte order

- armsrc/Standalone/hf_mattyrun.c
- armsrc/Standalone/hf_mattyrun.h
Greetings,
I did some fieldwork experiments and I noticed there was no reliable and practical way to clone Mifare classic cards in a stand alone mode. Mattyrun comes close to this. It works fine when connected to the computer, but on standalone mode I wasn't able to access the memory again and dumping the contents. Apart from that, if you finally managed to clone a card by copying it from someone, it would be highly unpractical if you lose the contents because of your battery runs flat.
The new model contains spiffs, which is a useful way of storing the contents, which I implemented in this PR. I tested it, and it works fine for the MFC cards I encountered. I tested the cards on 5 different locations.
Before we can merge this, I need to get answers on a few questions:
- What happens if …
> Standalone mattyrun spiffs

- client/src/cmdhfntag424.c
havent seen a tag with such large space, but this looks wrong
> fix offset transferred in ntag424_read_data

- client/pyscripts/fm11rf08s_full.py
Hi!
I use `fm11rf08s_full` script on a  Chinese version Windows with Proxspace. I got an exception said `gbk` can't encode log character.
I made a simple fix by set encoding type `utf-8` in this script. It works on my computer.
Log:
```
...
[=] =====================
[=]  Access Control List
[=] =====================
[=]
[=]    _______________________________________________________
[=]   |        |                Sector Trailers               |
[=]   |        |----------------------------------------------|
[=]   | Sector |____Key_A_____||_Access_Bits__||____Key_B_____|
[=]   |        | read ¦ write || read ¦ write || read ¦ write |
Traceback (most recent call last):
File "fm11rf08s_full.py", line 1080, in <module>
main()
File "fm11rf08s_full.py", line 171, in main
dumpAcl(data)
File …
```
> fix fm11rf08s_full log encoding type error

- armsrc/iso14443a.c
- armsrc/iso14443a.h
- client/src/cmdhf14a.c
- client/src/cmdhf14a.h
- doc/commands.json
- include/pm3_cmd.h
Additions:
* Move `mag` argument to `hf 14a config` option, allowing to enable/disable magsafe support for all places where HF14A polling is performed, instead of needing to add support on per-command basis;
* ~~Add `m` and `p` shorthands for `mag` and `pla` arguments in `hf 14a config`, allowing to set those options via shorthands like `-mon`, `-moff`, `-poff`~~;
* Mark `frame` argument in `ReaderTransmit*` functions as const to make it useable with const array references;
* Add more aliases for disabling `mag`/`pla` config options (`disable`/`off`/`skip`).
Removals:
* Remove `ecp` argument from all commands where it was present, as this functionality was replaced by more powerful `pla` in `hf 14a config`.
* Remove `mag` argument from all commands where it was present.
> Move `mag`safe polling argument to `hf 14a config`

- armsrc/Standalone/hf_cardhopper.c
- armsrc/usart.c
- armsrc/usart.h
make usart write buffer const
sub out magic numbers with defines
fix edge case handling 255/256 byte frames (including crc) add sanity checks to avoid buffer overrun on some "should never happen" edge cases don't wait for rats reply from card before listening to next reader frame cap fsci to 8 (256 bytes) as that's the most the proxmark3 codebase currently handles eliminate 1k of ram usage by tweaking how emulation responses are sent
> cardhopper fixes

- client/dictionaries/mfc_default_keys.dic
- client/resources/aid_desfire.json
- Added SDS 11 A/B (Gen 2) keys to `mfc_default_keys.dic` *with thanks to @DrekkCuga*.
- Added LAS RTC TAP & GO AID (`7A007A`) to `aid_desfire.json` *with thanks to Discord\jakkpotts*.
-R&Y.
> R&Y: Added SDS 11 A/B MFC Keys & LAS RTC TAP & GO AID

- Makefile.platform.sample
- common_arm/Makefile.hal
- include/usart_defs.h
With this change, only modifications in `Makefile.platform` are sufficient to get JDY-23 module running and connect with client using [Jakeler/ble-serial](https://github.com/Jakeler/ble-serial).
AT commands differs, but it is possible to configure it solely using `usart txrx` command.
Module manual: https://github.com/xiaolaba/AT3010-JDY-23/blob/master/JDY-23_Notes_xara.pdf
> Add option to override default USART baud rate in platform settings

- client/pyscripts/fm11rf08s_full.py
When dumping data with `fm11rf08s_full.py` it can happen that data is wrongly recognized as unicode which leads to errors like the following 
> UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc0' in position 62: surrogates not allowed
this fix ignores UnicodeEncodeError and properly prints a `.` for data that cant be represented in ASCII
> Ignore UnicodeDecodeError in lprint

- CHANGELOG.md
- client/luascripts/hf_mfu_ultra.lua
- doc/magic_cards_notes.md
I needed to write a previously saved dump to several   [ULTRA](https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/magic_cards_notes.md#ultra-ru) /[UL-5](https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/magic_cards_notes.md#ul-5) tags. Unfortunately the `hf mfu restore` command fails to properly restore dumps to these tags.  
To solve this, I created a script that:
1. Restores dumps to [ULTRA](https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/magic_cards_notes.md#ultra-ru) and [UL-5](https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/magic_cards_notes.md#ul-5) tags.
2. Clears previously written data from  [ULTRA](https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/magic_cards_notes.md#ultra-ru)  tags.
Please, look at it.
> Add script enables restoring dump to ULTRA/UL-5 tags and clear previously written ULTRA tags

- client/src/cmdhficlass.c
Fixed issue https://github.com/RfidResearchGroup/proxmark3/issues/2845
> Fix bug with iclass legbrute index value being ignored

- CHANGELOG.md
- client/src/cmdhficlass.c
Updated iclass trbl function for tearoff attacks:
1- Better comparison of read values vs expected values
2- Stop on "partial values tearoff", show tearoff results when the block isn't zero, but is also different from the original block (even tho is not yet with the same values of the expected block)
3- Improvement to verbose mode
> Updated iclass trbl effectiveness to detect partial tearoffs

- client/src/cmdhficlass.c
Removed a huge chunk of colorful visual spam for when the tearoff isn't happening
> Updated iclass tear colors

- client/src/cmdhficlass.c
If the card flips to nonsecure mode during the tearoff of block 1, this read command will be stuck. So we can disable auth completely when trying to read block 1 as that block doesn't require authentication anyway for reading operations.
> Fixed authentication read for iclass tear

- client/src/cmdhficlass.c
Updated hf iclass tear to not run if the authentication fuses are blown. Or it will just get stuck at the beginning and not start anyway. At least this informs the users why this is happening.
> Updated hf iclass tear to not run if the authentication fuses are blown

- client/src/cmdhficlass.c
Updated hf iclass tear to break endless read loop when the card can't be read anymore during the tear operation. Set a 10 attempts limit.
> Updated hf iclass tear to break endless read loop

- CHANGELOG.md
- client/src/cmdhf14b.c
- client/src/cmdhf14b.h
- client/src/cmdhficlass.c
Updated hf iclass info to use silicone identification based on CSN rather than hf 14b responsiveness
This reverted https://github.com/RfidResearchGroup/proxmark3/commit/4f85def6b07ad9cefe78d9bd11b18f14fad5dcb7
> Updated hf iclass info for silicon check

- client/src/cmdhfmf.c
- client/src/pm3line_vocabulary.h
- doc/commands.json
- doc/commands.md
This was cumbersome, it's a bit less so now :)
`hf mf bambukeys` will generate bambu lab filament tag keys using the existing KDF implementation from a provided UID or from one read from a tag, and can generate the necessary hf-mf-UID-key.bin file for a subsequent dump operation.
Like so:
```
hf mf bambukeys -r -d
hf mf dump
```
> Add "hf mf bambukeys" command to generate Bambu Lab keys

- CHANGELOG.md
- armsrc/iclass.c
- client/src/cmdhficlass.c
1- Renamed legreclookup to legbrute to be in line with the command name 2- Updated estimate values with speed increase gains 3- Improved some if statements readability in iclass.c and added start_time = eof_time + DELAY_ICLASS_VICC_TO_VCD_READER; to increase speed by ~8% (1.86 loops per second to 2.01 loops per second = ~560 more loops per hour).
Tried disabling some arm communications/comments but the speed increase was negligible (~1 sec / 1000 updates).
> Modified iclass recover and tear operations

- CHANGELOG.md
- armsrc/iclass.c
- client/src/cmdhficlass.c
Improved the speed of hficlass legrec from 7200 keys / hrs to 17800 keys / hr by removing the need to drop the field and re-select, re-authenticate with the card at every loop.
Re-select and re-authenticate will still happen if there's a read error and a loop needs to be repeated.
> Improved hf iclass legrec speed by 147%

- CHANGELOG.md
- client/src/cmdhficlass.c
Implemented key nibble based multithreading support for hf iclass legbrute. It takes the whole iclass keyspace based on the first 4 bits of the key value (from 0x0 to 0xF) and divides it across the number of available threads.
E.g. on a 8 threads implementation:
- thread 1 will test keys starting with 0x0 onwards
- thread 2 will test keys starting with 0x2 onwards
- thread 3 will test keys starting with 0x4 onwards
- thread 4 will test keys starting with 0x6 onwards
- thread 5 will test keys starting with 0x8 onwards
- thread 6 will test keys starting with 0xA onwards
- thread 7 will test keys starting with 0xC onwards
- thread 8 will test keys starting with 0XE onwards
> Implemented working multithreading support in hf iclass legbrute

- armsrc/iclass.c
- armsrc/iclass.h
- client/src/cmdhficlass.c
- include/iclass_cmd.h
Added an option for hf iclass legrec to further increase speeds by using a shorter delay of 1500 vs the default of 3390. This seems to be stable on new silicon especially now that we're keeping the field always on. It may be more risky for the --fast operation.
> Updated hf iclass legrec to optionally use shorter delays

- armsrc/iclass.c
- client/src/cmdhficlass.c
Updates to the functionality of iclass sim -t 6 to specifically target the last SIO block and to do it automatically. It now checks the AIA to determine if the card is SR or SE and adjust the block to jam based on the SIO length declared in block 6 (if SE) or fixed length if SR.
> Updated hf iclass sim -t 6

- CHANGELOG.md
- client/src/mifare/mad.c
When using the command `hf mf mad` to display a version 2 Mifare Application Directory (MAD), the Card Publisher Sector (CPS) is displayed incorrectly.
The CPS is highlighted in magenta, and the correct sector is highlighted for MAD V1, but for MAD V2 the wrong sector is highlighted or none at all.
I've noticed the [MADv2 code indexes the sectors relative to the start of the Mifare 4K sectors](https://github.com/RfidResearchGroup/proxmark3/blob/3a8c3174a80222e0780e84cc69b2afac12b3c4c6/client/src/mifare/mad.c#L407) and then [compares the CPS](https://github.com/RfidResearchGroup/proxmark3/blob/3a8c3174a80222e0780e84cc69b2afac12b3c4c6/client/src/mifare/mad.c#L411) which I think is an absolute sector index from sector 0.
This results in the wrong sector being highlighted.
As far as I can …
> fix mad v2 cps offset

- CHANGELOG.md
- armsrc/iclass.c
- client/src/cmdhficlass.c
- include/iclass_cmd.h
Implemented an iclass sim function that prevents simulated card responses after updating block 3. Block 3 gets updated with the XOR key as if it was in personalization mode.
> Implemented hf iclass sim -t 7

- client/src/cmdlfem4x50.c
Client was expecting a struct starting with an object count but ARM directly sends the array. The struct is only used on this line in the whole repository, so reverting client is the easiest way to solve the issue.
> Rollback em4x50_read() to remove a segv

- CHANGELOG.md
- armsrc/em4x70.c
- client/src/cmdlfem4x70.c
- include/em4x70.h
Fixes #2376
Tags always required the parity bit.
This just finishes the removal of the deprecated option.
> EM4x70 -- Remove deprecated `--par` option

- CHANGELOG.md
- armsrc/lfadc.c
resolve #2897
**WIP until the change is tested with different HITAG fobs/cards**
> LF HITAG: Adjust timing for LF ADC measurements to increase stability when the tag is in public mode/TTF mode

- client/src/cmdhficlass.c
Added ability to pass data to sam directly in snmp format and for the client to calculate the packet headers accordingly.
Renamed ack_mask to ok_mask as that is a generic mask for successful commands, the same bytes are used for multiple types of successful responses.
> Renaming and snmp data format option for sam comms

- client/src/wiegand_formats.c
- As S12906 pack function suggests, the issue level field takes 2 bits, thus ranging from 0 to 3. The card number takes 24 bits, ranging from 0 to 0xffffff. Reference from [1](https://acre.my.site.com/knowledgearticles/s/article/x107), [2](https://www.everythingid.com.au/hid-card-formats-i-15?srsltid=AfmBOor2UAGlvB7R6Zmj7B7rtL-LExfBjh7I3ZEyoLLbg7Pk7UbC1za-) also confirms the CN should be ranging from 0 to 0xffffff. https://github.com/RfidResearchGroup/proxmark3/blob/61a993de826335db2d92d1f60c3ef4ae64439b73/client/src/wiegand_formats.c#L684-L685
- That shows an inconsistent with the limits defined in the format table. Specifically, the IL/CN limits in the table was reversed, accidentally.
https://github.com/RfidResearchGroup/proxmark3/blob/61a993de826335db2d92d1f60c3ef4ae64439b73/client/src …
> fix card limits for S12906 format

- CHANGELOG.md
- client/src/cmdhfmfdes.c
I got my hands on [iShield Key 2 Pro Mifare](https://www.swissbit.com/en/products/security-products/ishield-key/). This authentication token supports MIFARE DESFire EV3 (info from NXP's TagInfo is _DESFire EV3C implementation on P71D600_). 
It has different version info than typical DESFire, so here it is.
PS: Info from pm3 client before this change:
```
[=] HW Version.. 04810043011A05
[=] SW Version.. 04814603001A05
[=] Version data identification failed. Report to Iceman!
```
> Add recognition of Swissbit iShield Key Mifare as MFD EV3

- client/luascripts/paxton_clone.lua
Related to: #2919 
This does OS detection to modify the logfile handling. The current version assumes Windows only using `dir`, this is not compatible with Linux.
The original dir command has been translated to an equivalent Linux command. This was done with the help of AI, to quikcly translate the Windows only parameters to Linux.
@jareckib This shouldn't affect Windows, but I have the reverse problem of not having an proxmark environment on Windows to ensure the detection continues to use the dir command as the original script.
> paxton_clone.lua: Detect operating system for logfile handling on Linux environments

- CHANGELOG.md
- client/src/cmdhffelica.c
- client/src/cmdhffelica.h
- include/iso18.h
This command was not implemented. This PR works for standard FeliCa tags. I have tested with a few Japan transit ICs, all of which are standard FeliCa. 
Here's an example output I got from one of the tags:
```
[usb] pm3 --> hf felica reader
[+] IDm: 011204120D220613
[usb] pm3 --> hf felica scsvcode
[=] Using last known IDm... 0C0A011204120D2206130000
[?] Area and service code are printed in big endian.
[?] Don't forget to convert to little endian when using hf felica rdbl.
[=] ┌───────────────────────────────────────────────
[=] ├── AREA_0000
[=] ├── AREA_0001
[=] │   ├── svc_0048
[=] │   ├── svc_004A
[=] │   ├── svc_0088
[=] │   ├── svc_008B
[=] │   ├── AREA_0003
[=] │   │   ├── svc_00C8
[=] │   │   ├── svc_00CA
[=] │   │   ├── svc_00CC
[=] │   │   ├── svc_00CE
[=] │   │   ├── svc_00D0 …
```
> `hf felica scsvcode` implementation: dump all area and service code

- CHANGELOG.md
- client/src/cmdlfindala.c
This fixes #2939
The checksum logic just needs a slight tweak.
I've validated this by writing using a few FC and CN of known valid cards and comparing the bits.
> Fix getIndalaBits checksum logic

- CHANGELOG.md
- client/src/cmdhffelica.c
Example output:
```
[usb] pm3 --> hf felica reader
[+] IDm: 011204120D220613
[usb] pm3 --> hf felica dump
[=] Using last known IDm... 0C0A011204120D2206130000
[=] Using last known IDm... 1006011204120D220613010000018000
[=] Service 0048 | Private | Random | Read/Write |
[=] Service 004A | Private | Random | Read Only  |
[=] Service 0088 | Private | Random | Read/Write |
[=] Service 008B | Public  | Random | Read Only  |
[=]  block | data  
[=] -------+----------------------------------------
[=]   00   | 00 00 00 00 00 00 00 00 20 00 00 02 00 00 00 16   
[=] Service 00C8 | Private | Random | Read/Write |
[=] Service 00CA | Private | Random | Read Only  |
[=] Service 00CC | Private | Random | Read/Write |
[=] Service 00CE | Private | Random | Read Only  |
[=] Service 00D0 | Private | Purse …
```
> `hf felica dump` for Services Readable without Auth

- client/src/cmdhfmfdes.c
This PR adds zero-initialization to all uses of `DesfireContext_t` in order to prevent issues, such as with automatic DF Name selection, which happened for users if DFNameLen was initialized to non-zero value (which happens on some pre-C23 compilers).
> Add zero initizlier for DesfireContext_t to prevent UB

- CHANGELOG.md
- client/pyscripts/mf_backdoor_dump.py
Apparently the number of whitespaces in the parsed output changed over time. This fix should be able to handle all variations of it.
> Improve output checks in mf_backdoor_dump.py

- CHANGELOG.md
- client/src/cmdhfmfdes.c
for non-standard settings, use credit/debit instead of clear command.
fixes #2773
> fixed clear command logic. will works with some default settings. 

- client/src/cmdhflegic.c
When printing the BCD encoded Card ID, data is being XOR'd twice: once with a for-loop, and a second time for printing, cancelling the operation and displaying garbage
> Fix data being xored twice

- client/resources/aid_desfire.json
Adds the StagecoachSmart card ([yes, it's really called that](https://www.stagecoachbus.com/promos-and-offers/national/stagecoachsmart)) to the DESFire AIDs list.
No changelog entry due to lack of significance.
> Add StagecoachSmart card to AID list
