CHANGELOG.md, install.sh, proxmark3.sh, update.sh
The update.sh is not my code, just had the idea. Authored by joanbono
install.sh is working tested under OS X High Sierra. I'll do a PR for iceman fork too.
=> Updated update.sh - by joanbono from iceman1001/proxmark3

proxmark3.sh
Quick fix - skipped over it too quickly!
=> fix missing text in proxmark.sh

client/cmdlfhid.c
As per http://www.proxmark.org/forum/viewtopic.php?id=5967 submitting code to fix the handling of 32 bit Kastle format cards.
Made this chart to represent the format, barkweb gets it slightly wrong:
Tried to follow your code style as closely as possible, please let me know if you have any other feedback.
=> feature: Handle Kastle format 32 bit cards

armsrc/lfops.c
Added missing braces. Code now compiles. Should help issues #31 & #30
=> Fix syntax

client/Makefile, client/cliparser/README.md, client/cliparser/argtable3.c, client/cliparser/argtable3.h, client/cliparser/cliparser.c, client/cliparser/cliparser.h, client/cliparser/getopt.h, client/cmdhf14a.c, client/cmdhf14a.h, client/cmdhfmf.c, client/cmdhfmf.h, client/reveng/cli.c
here :
1. move argtable from pm3 repo
2. adapt revevg to argtable
3. add https://github.com/merlokk/proxmark3/commit/7dadcc959fb7009b6e8bbde4a644aa2f7f1b7a98
@iceman1001 look please into code. maybe it needs to change something
=> Auth14443-4

client/Makefile, client/cliparser/cliparser.c, client/cliparser/cliparser.h, client/cmdhf.c, client/cmdhf.h, client/cmdhf14a.c, client/cmdhfmf.c, client/cmdhfmfp.c, client/cmdhfmfp.h, client/mifare4.c, client/mifare4.h, common/polarssl/libpcrypto.c, common/polarssl/libpcrypto.h
from
https://github.com/RfidResearchGroup/proxmark3/blob/master/client/scripts/mifareplus.lua
```
pm3 --> hf mfp rdbl 1 -n3
hf mfp rdbl 1 -n3
[=] Authentication OK
[=] data[001]: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 FF
[=] data[002]: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[=] data[003]: ------------------- trailer -------------------
[=] data[004]: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```
=> Mfp read plain

client/scripts/legic.lua
Initial PR to update `legic.lua` to work with the new commands. Feedback appreciated!
Hacked this up last night since some of the PM commands don't exist anymore, and the PM client has some extra checks in `legic write` now.
=> Update Legic.lua script

client/jansson/dump.c, client/jansson/error.c, client/jansson/hashtable.h, client/jansson/hashtable_seed.c, client/jansson/jansson.h, client/jansson/jansson_private.h, client/jansson/load.c, client/jansson/pack_unpack.c, client/jansson/strbuffer.h, client/jansson/value.c
=> jansson update. 2.11 to 2.12

client/loclass/fileutils.c
=> fix memory error

appveyor.yml, client/cmdhf.c, client/cmdhf.h, client/cmdmain.c, client/cmdmain.h, client/cmdsmartcard.c, client/cmdsmartcard.h, client/emv/cmdemv.c, client/emv/cmdemv.h, client/emv/emvcore.c, client/emv/emvcore.h, client/fido/fidocore.c
`emv scan` not works with sc at all. It needs to rebuild some parts.
`emv exec` works, but for me only up to GPO
the rest commands works (at least put data to interface and receive data)
=> Emv commands works with smartcard interface

client/cmdsmartcard.c, client/cmdsmartcard.h
added TA1 decoding
and
calculating bit rates and maximum frequency
=> added TA1 decoding

client/cmdsmartcard.c, common/i2c.c, common/i2c.h, include/mifare.h
=> T0 works with new sc firmware

armsrc/epa.c, armsrc/iso14443a.c, armsrc/iso14443a.h, client/cmdhf14a.c, client/fido/fidocore.c, include/mifare.h
1. get max frame size from ATS
2. check max frame size and use ISO chaining if size of command bigger than framing const in ATS
3. command `hf 14a chaining`  for enable/disable this feature. it enabled by default
=> 14a apdu send framing

armsrc/iso14443a.c
=> Fix 14a loop

client/cmdhfmf.c
- Modify MAXBLOCK size: 4k => 256
- Typo
=> Update MAXBLOCK - MF 4K

client/cmdhfmf.c
- Use Variable for MIFARE_XXX_MAXSECTOR
- Modify type uint16_t for NumOfBlocks => 256
=> Use Variable for MIFARE_XXX_MAXSECTOR

uart/uart_posix.c
See https://github.com/Proxmark/proxmark3/pull/787
=> Fix for USB uart slowness

client/proxmark3.c
we don't like long history full of repeated commands :)
=> cmds history: don't push to history if last command is replayed

armsrc/lfsampling.c, client/cmddata.c, client/cmdlfem4x.c, client/cmdlft55xx.c, client/comms.c, common/lfdemod.c, common/lfdemod.h
Hi @iceman1001 
Please review it first.
I tried to implement what we discussed.
=> Replace isNoise by computeSignalProperties and removeSignalOffset

armsrc/mifaresim.c
- Add comment about emulation problem <=> printing debug message
- Change log level
=> [Hf mf sim] Add comments

armsrc/iso14443a.c, armsrc/iso14443a.h, armsrc/mifaresim.c
Authentication for Android devices
=> 'hf mf sim' nested authentication

armsrc/iso14443a.c, armsrc/iso14443a.h, armsrc/mifaresim.c, armsrc/mifaresim.h
Deleted unused methods, fix bugs
=> 'hf mf sim' + 'hf 14a sim' now back to stable

appveyor.yml
=> fix fake com port

appveyor.yml
=> add dlls to release

CHANGELOG.md, armsrc/appmain.c, armsrc/mifaresim.c, armsrc/mifareutil.h, client/cmdhflist.c, client/cmdhfmf.c
Refactoring of select tag case. Add precompiled responses for full-byte anti-collision on cascade levels 1/2/3
=> 'hf mf sim' full-byte anti-collision frame support

armsrc/iso14443a.c
Added 'Init' method to prepare precompiled responses used in SimulateIso14443aTag()
=> 'hf 14a sim' more flexible init responses method

armsrc/BigBuf.c, armsrc/Standalone/hf_colin.c, armsrc/appmain.c, armsrc/flashmem.c, armsrc/fpgaloader.c, armsrc/lfops.c, armsrc/lfsampling.c, armsrc/mifareutil.h, armsrc/util.h, client/comms.c, client/emv/emvjson.h, client/fido/cose.h, client/flash.c, client/flasher.c, client/proxmark3.c, client/ui.c, client/ui.h, client/util.h, common/commonutil.h, common/i2c.c
* if on Windows, no color, as usual
* if on Linux, color only on real term
* no color when > foo
* no color in the logfile
@iceman1001 please test it on mingw to make sure I didn't break anything.
=> Smart color handling

armsrc/Standalone/hf_young.c
Missing Rename USB -> PM3 to avoid misleading interpretations 27f7057
=> Missing Rename USB -> PM3

client/cmdtrace.c
Adding option 'x' to show trace output for 14a in hexdump format.
This output can be imported into Wireshark using the 'Import from Hex Dump' option.
Encapsulation type should be set to 'ISO 14443' and Max Frame Length to 256.
Used documentation: https://www.kaiser.cx/pcap-iso14443.html
=> Cmdtrace: Show trace ouput in hexdump format

doc/md/Installation_Instructions/Mac-OS-X-Homebrew-Installation-Instructions.md
Reviewed install instructions for macOS and updated where necessary.
=> Doc: Update macOS install instructions

CHANGELOG.md
=> Changelog standalone Makefile.hal & Makefile.platform

doc/md/Use_of_Proxmark/0_Compilation-Instructions.md
Added info about compiling for other boards as discussed on #217
=> Added documentation: Compiling for other boards

armsrc/hitag2.c
=> Fix clock deadlock in hitag sniff

client/emv/cmdemv.c
=> Fix EMV bug

client/proxguiqt.h, client/proxmark3.c
=> Fix Clang warnings

client/Makefile, client/jansson/Makefile, client/tinycbor/Makefile, common/Makefile.common, common/mbedtls/Makefile, liblua/Makefile
=> Fix compilation under MacOSX

doc/md/Installation_Instructions/Linux-Installation-Instructions.md
=> Add the needed qt package on ArchLinux

.travis.yml
=> Fix build for linux on travis

armsrc/Standalone/hf_bog.c
Unless I did not understand the flow, it should do the trick.
As expected, reduces Greatly the complexity.
=> HF_BOG fixes for spiffs

armsrc/Standalone/hf_colin.c
This greatly DRY the code and is 1/2 Pass for having Schemes dynamicly read from SPIFFS as json.
=> HF_COLIN : Makes Known Schemes in Struct form

armsrc/Standalone/Makefile.inc, armsrc/Standalone/hf_colin.c, armsrc/frozen.c, armsrc/frozen.h, armsrc/nprintf.c, armsrc/nprintf.h, armsrc/string.c, armsrc/string.h
BEWARE : add device-side json parsing and overlapping string/standard libc functions.
Edit : usable and quite working. 
It works, but it's messy and heavy.
Needs ton of cleaning but I needed to be sure to be able to merge before any breaking change from master.
Next step is to read ARRAY of Known schemes in Config file dynamically then Clean all the mess.
=> HF_COLIN 2/3 : Now able to read Known  key schemes from SPIFFS JSON Config File

armsrc/hitag2.c
Fixes an issue introduced in #233, closes #239.
Now consistent with how crypto auth works.
=> Fix password write offset by 1

.vscode/tasks.json
Handy build and flash shortcuts if you are working in VSCode:
`F1 > Tasks: Run Task`
Build runs multi-threaded, too.
=> Add VSCode tasks

armsrc/hitag2.c
Formats and documents some hitag2 code, hopefully makes the logic easier to understand.
=> Format and docs

client/cmdlfhitag.c
Got bitten by this, let's make it clear for other users.
=> Better warn user of hardcoded hitag info

doc/termux_notes.md
No more ncurses hacking, no more Makefile modifications!
=> Update Android Termux guide

doc/cheatsheet.md
Updating the cheatsheet with more commands
=> Updated Cheatsheet

doc/trace_wireshark_notes.md
Adding some notes how to bring trace output into Wireshark.
=> Doc: Add notes about trace to Wireshark export

client/cmdhfmf.c, client/dictionaries/mfc_default_keys.dic
As said before, I couldn't verify if this is working correct, so someone should please try it first.
(Well I made a little mistake with the pull requests / branches, now they are together... But the dictionary additions are small.)
@doegox and @iceman1001 nice work with the autopwn, now it looks really sexy ;)
=> Added the autopwn read b key feature

client/cmdhfmf.c, client/cmdhfmf.h
I hope you like the new style :)
It helps to keep track of what does what (this is probably very helpful for beginners).
=> Restyled of the autopwn command output

appveyor.yml
=> appveyour next fix

appveyor.yml, client/emv/test/cryptotest.c
i think need to wait after `make install` will be done and then fix ll CI
=> Appveyour fix paths

client/cmdlft55xx.c
=> Remove double spaces from output

armsrc/appmain.c, armsrc/felica.c, armsrc/felica.h, client/cmdhffelica.c, client/cmdhffelica.h
=> Add reader and raw command for FeliCa standard cards

CHANGELOG.md, armsrc/felica.c, armsrc/felica.h, client/cmdhffelica.c, client/cmdhffelica.h, include/mifare.h
Add two new commands:
- request response
- read without encryption
=> Felica support: add commands request response and read without encryption

armsrc/appmain.c, armsrc/felica.h, client/cmdhffelica.c, client/cmdhffelica.h, client/proxmark3.c, include/mifare.h
Add new command which allows to write data to the not encrypted memory.
=> Felica support: add write without encryption command

doc/md/Installation_Instructions/Linux-Installation-Instructions.md
=> make warning about ModemManager louder

CHANGELOG.md, client/luascripts/luxeodump.lua
CRC RevEng works if it is used correctly ;)
The Lua implementation of CRC16 / ARC is useless.
(+ update CHANGELOG.md)
=> switch from lua CRC16/ARC to CRC RevEng

client/cmdhf15.c, client/cmdhflist.c, common/iso15693tools.h, include/protocols.h
=> Added support for some ISO15693 custom NXP commands

client/cmdhffelica.c
Sorry, I used the wrong key sizes there...hope it's correct now
=> Fix key length in auth1 command.

client/cmdhffelica.c, include/mifare.h
Fix output of auth1
Add auth1 decryption test - experimental
Add auth2 command - experimental
=> Felica support auth1 and auth2

armsrc/appmain.c, client/cmdlfpac.c
added card ID to bit buffer code. actual nrz sim still wip...
=> chg: lf pac sim *wip*

client/Makefile, client/fileutils.c, doc/md/Installation_Instructions/Linux-Installation-Instructions.md, doc/md/Installation_Instructions/Mac-OS-X-Homebrew-Installation-Instructions.md, doc/md/Installation_Instructions/Windows-Installation-Instructions.md, doc/termux_notes.md
see if it's ok for you @iceman1001
=> Remove libsndfile dep and code our own savewav

armsrc/felica.c, client/cmdhffelica.c
Fixes the CRC and length for FeliCa Light cards
=> Fix FeliCa Light Dump

client/cmdhflist.c, client/cmdhflto.c, client/cmdhflto.h
Tested Commands: 
hf lto info
hf lto rdbl 
hf lto rdbl h
hf lto rdbl s 0 e 254
hf lto rdbl s 0 e 0
hf lto list
=> Support LTO-CM read block and add CM-Type info into "hf lto info" command.

appveyor.yml
https://github.com/Gator96100/ProxSpace/issues/28
=> add proxspace workaround

CHANGELOG.md
Documents changes from issues #560 and #564, and pull requests #561,
#563, and #565.
=> Mention shebang changes and python script porting in CHANGELOG.md

client/cmdlfhid.c
Fixes issue https://github.com/RfidResearchGroup/proxmark3/issues/556#issue-563655400
Adds datahi and datalo variables for incrementing card IDs up and down.
=> Fix lf hid brute

client/cmdlfkeri.c
Adjust for the correct internal ID bit alignment.
=> Keri Internal ID demod alignment. Issue #577

client/mifare/mifarehost.c
also some wording and consistency
=> fix: (static)nested time and keys/sec

CHANGELOG.md, client/luascripts/hf_bruteforce.lua, doc/cheatsheet.md
=> Add Mifare Ultralight bruteforce support to hf_bruteforce lua script

CHANGELOG.md, armsrc/lfops.c, client/cmdhf14a.c, client/cmdhf14b.c, client/cmdhfmfu.c, client/cmdlfhid.c
Added colour to several commands:
`lf hid`
`hf 14a`
`hf mfu`
=> Add colour to command output

client/emojis.h, client/emojis_scrap_github.py, client/ui.c
please test @iceman1001 thanks!
=> Prevent emoji on ProxSpace

client/resources/aidlist.json
Now includes the AIDs that are used in the key fob and phone.
Removed some AIDs that can't be selected.
=> Updates to the Tesla AIDs

README.md, doc/trace_notes.md
First draft of some informations regarding trace command.
=> Doc: Update trace notes

client/luascripts/Legic_clone.lua
Refactored to work with current command set and MIM256 and MIM1024 tags
=> Legic_clone.lua: Refactor to work with current command set

client/Makefile, client/emv/emvjson.c, client/emv/emvjson.h, client/fileutils.c, client/fileutils.h, client/proxmark3.c, client/settings.c, client/settings.h
Base for using a settings file.
=> Settings Base

armsrc/mifaredesfire.c, client/cmdhfmfdes.c
This patch fixes the desfire aes authentification and adds aid selection before authentification as well.
=> Fix mifare desfire aes authentification

client/cmdhfmfdes.c
Fix bug for file id handling in hf mf des enum :)
=> Fix bug for file id handling in hf mf des enum :)

CHANGELOG.md, armsrc/mifaredesfire.c, armsrc/mifareutil.c, client/cmdhfmfdes.c
Mifare Desfire got some love and can now create standard files :)
hf mfdes formatpicc was broken and is fixed.
=> hf mfdes createstdfile command and formatpicc fixes

client/CMakeLists.txt
This fixes the CMakeLists.txt for QT5 GUI support.
=> Fix QT5 GUI CMake

client/src/cmdhfmfu.c
=> Updated help and default values

client/luascripts/hf_writer.lua
1. I have made the auto key check. Now you can check your code for errors. Why I have en error after 40 block I only guess.
2. In function checkmagic() I would like to see the RAW command send function. As you undersend I did't find it in appmain.c
3. You could not do the both mode for NIX and WIN as I already asked you, then it's works only to Windows. In generaly this script for me. That's why.
It is intermediate update from me. You are welcom to polish a code.
=> A lot of improvements

client/Makefile
renaming PKG_CONFIG_PATH to PKG_CONFIG_ENV was too greedy
=> Makefile: fix PKG_CONFIG_ENV

client/android/CMakeLists.txt, client/android/jni_tools.c, client/android/jni_tools.h, client/android/pm3_main.c
1. All resources comment tran to english.
2. Use "android_lib" branch to manage.
Thank you for your guidance. If there is anything wrong, please advise.
: )
=> Translation some comments from Chinese to English.

client/src/cmdhw.c, tools/mf_nonce_brute/mf_nonce_brute.c
=> Fix 32-bit time_t compilation error on WIN64

client/src/mifare/mad.c
=> Decode MAD Info Byte and show info about sector it points to

CHANGELOG.md, client/src/mifare/mad.c
Improvement of #766, better formatting, updated Changelog.
@iceman1001 tried to print the sector number in magenta and then highlight the line like that. The conditional formatting is a bit not nice but wasn't sure how else to do that. TBH I'm not too much of a C person 😨 Feel free to edit, I'll be happy to pick up preferences in code style.
=> 766 card publisher enhancement

CHANGELOG.md, client/src/cmdhfmf.c, client/src/mifare/mad.c, client/src/mifare/mad.h
Added Mifare MAD Card Holder Information Decoder, looks like this:
Here are some sample data, most of it is the example from the spec, I added some more and made it overflow to another sector with a gap in-between to test it properly:
```
e4f4857fea980200648e64115d504405
b70103e1000004000000000000000000
04000000000000000000000000000000
a0a1a2a3a4a5796788c1d3f7d3f7d3f7
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
ffffffffffffff078069ffffffffffff
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
ffffffffffffff078069ffffffffffff
0a53616d706c656d616e00475068696c
697000826d00d054656c2b312f313233
342f3536373800DA52616E646F6D204C
ffffffffffff78778869ffffffffffff
00000000000000000000000000000000 …
```
=> Mifare MAD Card Holder Information

client/src/mifare/mad.c
Got some Mifare Classic 4k, tested MADv2, including a few fixes below. Also some textual stuff to make it uniform with MADv1. This what it looks like (this was cardholder info spread between MADv1 and MADv2 to test it really reads it as one, not sure if it should, but it does, lol):
=> Mifare MADv2 fixes

armsrc/BigBuf.c, armsrc/BigBuf.h, armsrc/appmain.c, armsrc/mifarecmd.c, client/src/cmddata.c, client/src/cmddata.h, client/src/cmdlft55xx.c, common_arm/ldscript.common, include/pm3_cmd.h
The work on the arm side is done.
We need an API call or some other way to forward the available space to the client.
=> [WIP] Make BigBuf take dynamically the available space with a fixed (4K) stack

client/src/comms.c
Change it to whatever you want :-)
=> Happy colors for messages coming from pm3

armsrc/em4x50.c
Performance of "lf search" should now be comparable to the former version (if tag is not an EM4x50).
BTW: I've seen your improvements, thanks. So far I've two comments:
1. What should the output of "lf em 4x50_read" look like? I'm missing any information regarding the "standard read mode", which may be essential for copying a tag. In many cases the "standard read mode" equals transmitting the serial number, but that's not mandatory.
2. Sometimes there are wrong results (=serial) in "lf em 4x50_read". When using "lf search" the result is correct. I'll have a look at it.
=> speed up "lf search" process (EM4x50)

common/crapto1/crapto1.c, common/crapto1/crypto1.c
=> Build with clang on aarch64 / Termux on Android

tools/pm3_amii_bin2eml.pl
As per discussion in #832, updates bin2eml script to generate new header format, calculate auth key, etc
=> update bin2eml script from https://github.com/samyk/samytools/

client/luascripts/mfc_gen3_writer.lua
=> Return the Mfc gen3 writer to Mater

armsrc/mifarecmd.c
=> Fix: magic gen 3 card response check

appveyor.yml
Updated appveyor CI to use the intended way of launching ProxSpace. 
Tested with ProxSpace v3.5 and v3.6.
=> Fixed appveyor CI

client/src/cmdhfst.c
https://www.st.com/resource/en/datasheet/st25ta64k.pdf
=> add ST25TA64K chip model

CHANGELOG.md, client/src/cmdlft55xx.c
Updated from buffer to use "1" and sample levels to use "s"
=> T55xx sniff

client/deps/cliparser/cliparser.c, client/deps/cliparser/cliparser.h, client/src/cmddata.c
checked cmdhf.c and cmddata.c and tweaked cliparser.c
=> cliparser cleaning

client/deps/cliparser/cliparser.c, client/src/cmdhf14a.c, client/src/cmdhffido.c, client/src/cmdhficlass.c, client/src/cmdhfmf.c
cmdhf14a.c, cmdhfido.c, cmdhficlass.c, cmdhfmf.c
menu help updates.
cliparser.c : tweak for readability with long examples.
=> cliparser cleanup 2

client/src/cmdhfmfdes.c, client/src/cmdhfmfp.c, client/src/cmdhfmfu.c, client/src/cmdlfindala.c, client/src/cmdlfmotorola.c
updated cmdhfmfdes.c,  cmdhfmfp.c, cmdhfhfu.c, cmdlfindala.c and cmdlfmotorola.c
Last of the initial standardization for cliparser for existing commands using it.
=> cliparser - round 3

client/src/cmdhfst.c
This commit changes CLI parsing for all `hf st` commands to use cliparser
Thanks @mwalker33 for the awesome cliparser doc!
=> hf st commands - now use cliparser

armsrc/Standalone/hf_iceclass.c, client/src/cmdhficlass.c, doc/cheatsheet.md, doc/commands.md
Hopefully partial conversions like this are okay.  Not sure how much time I'll have this week to work on this.
=> hf iclass view, permute - now use cliparser

client/src/cmdhfmfu.c
I've added the capability to test for an arbitrary Ultralight C key.
=> Added customizable 3DES key to hf mfu cauth

client/src/cmdhflegic.c
Show usage when parameter h is used or none parameter
=> cmdhflegic: Make sure to show help text

client/dictionaries/t55xx_default_pwds.dic
Removing duplicating passwords:
aabbccdd
bbccddee
ccddeeff
=> Removing duplicating passwords

client/src/cmdhfst.c
After doing the NFC nail sticker mod I noticed some of the ST25 commands would leave the field on when reaching an error condition.
=> ST25TA drop field & cliparser buffer fixes

client/src/cmdhf14a.c
Partially fulfils https://github.com/RfidResearchGroup/proxmark3/issues/1012 (does not utilise GetVersion)
I modified the `detect_nxp_card` function to utilise the information in AN10834 and reduce false positives. Some changes:
1. Identification of MIFARE Classic 2K
2. Identification of SmartMX
3. Identification of MIFARE DESFire Light
4. Identification of 256B DESFire EV1s
5. Identification of MIFARE Hospitality
6. More specificity and accuracy with MIFARE Plus identification
More accuracy is also obtained by using `select_status` to determine whether or not ATS is supported. Further, checks are designed to be specific: there are instances with the current version where more possible matches are reported than necessary. For example, the `sak & 0x08` check is a subset of `sak & 0x09`, …
=> Improve MIFARE type identification

client/src/cmdhfmfdes.c
The `hf mfdes chk` command incorrectly used the file settings length for key type, instead of the  key settings length.
=> Improve MIFARE Desfire key checking and fix specifying single Application ID

armsrc/Standalone/hf_iceclass.c, client/src/cmdhficlass.c, doc/cheatsheet.md, doc/loclass_notes.md, tools/pm3_tests.sh
Some more on my cliparser quest
=> hf iclass eload, loclass - now use cliparser

armsrc/iclass.c, client/src/cmdhf14a.c, client/src/cmdhficlass.c, client/src/cmdhfmfdes.c, client/src/cmdlfem4x05.c, client/src/cmdlft55xx.c, client/src/cmdmain.c, client/src/crypto/asn1dump.c, client/src/emv/emv_tags.c, client/src/fido/fidocore.c, client/src/util.c
Also first attempt at make style, but I looked through each of them and rejected anything that was more than just white space.
=> Iclass cliparser esave, eview - now use cliparser

CHANGELOG.md, README.md
Updated readme.md to link to the guide.
Added line to changelog.md
=> T55xx guide update

client/src/cmdhficlass.c, client/src/loclass/elite_crack.c, doc/cheatsheet.md, doc/loclass_notes.md
This wraps up the `hf iclass` cliparserization.
=> hf iclass chk, managekeys, calcnewkey, lookup, sim - now use cliparser

Makefile, doc/cliparser_todo.md
This commit adds `make cliparser` which will generate `doc/cliparser_todo.md` which contains the commands that still need to be converted to use cliparser
=> Generate and add cliparser TODO

Makefile, doc/cliparser_todo.txt, doc/commands.md
Also new commands.md with some of the recent changes
=> fix false positives in cliparser_todo

client/src/cmdhfmfp.c, doc/cliparser_todo.txt
Remaining `hf mfp` command now using cliparser
=> hf mfp info - now use cliparser

client/luascripts/mfc_hammerlite.lua, client/luascripts/ntag_hammertime.lua
This PR adds ntag_hammertime and mfc_hammerlite as we discussed on Discord.
mfc_hammerlite will likely need tiny changes as changes are done to `hf mf wrbl` and `hf mf rdbl` regarding cliparser.
=> scripts: Add mfc_hammerlite and ntag_hammertime

client/src/cmdhfthinfilm.c, doc/cliparser_todo.txt
Thinfilm commands now use cliparser
=> hf thinfilm - now use cliparser

client/src/cmdhftopaz.c, doc/cliparser_todo.txt
Topaz commands now use cliparser
=> hf topaz - now use cliparser

armsrc/appmain.c, armsrc/em4x70.c, armsrc/em4x70.h, client/src/cmdlfem4x70.c, client/src/cmdlfem4x70.h, include/em4x70.h, include/pm3_cmd.h
=> EM4x70 write support

armsrc/appmain.c, armsrc/em4x70.c, armsrc/em4x70.h, client/src/cmdlfem4x70.c, client/src/cmdlfem4x70.h, include/em4x70.h, include/pm3_cmd.h
Last of the primitive commands this tag supports.
=> EM4x70 Authentication Support

client/src/cmdlfem4x70.c
Updates the client tag info printing to include addresses and names for each word.
I plan to update the array indexing to be a bit cleaner, but I am still deciding on how best to store the data. I may move it out of the one 32-byte array and put each readable area into its own array for simplicity.
=> em4x70: Improve client print out of tag information

armsrc/em4x70.c
I am basing this commit on tests using my PM3 easy and PM3RDV4.
I have found that reading/writing is much more reliable with a fixed level for the high/low values. With these updated settings I can read/write on the PM3 easy by resting the tag on the coil, or lifting it up about 1CM. With the previous auto-thresholds I had to carefully hold the tag maybe half a centimeter off the coil in a very specific location.
I plan to test using the RDV4 and the new updated antennas, as well as the larger LF antenna kit for it once I receive them. Until then, these are the best values I have found to use for making reading/writing the most reliable.
=> em4x70: Use fixed threshold for high/low

client/src/cmdhfemrtd.c
Didn't expect to have to send this in so soon, but apparently there were some crashes on some versions of ubuntu, whoops. [I had only tested on my arch setup where it worked just fine](https://elixi.re/i/worksonmymachine.png).
This PR resolves those, and does some of the recommended cleanup of the code. More will happen over future PRs.
This one was confirmed working on WSL1, Proxspace, Ubuntu and Arch.
=> eMRTD: Bugfixes & basic cleanup

armsrc/em4x70.c
Only use Ticks in functions involving time, do the multiplication in the defines for this.
Removed some magic timing values.
=> em4x70: Clean up conversion of RF periods to ticks

armsrc/em4x70.c
Simplify check_ack function
Rename EM4170_setup_read to em4x70_setup_read
=> Em4x70 cleanup

client/src/cmdhfemrtd.c
This PR fixes the regression introduced by https://github.com/RfidResearchGroup/proxmark3/commit/b3c7dd64c64c6e58e67547672a51b5296d244aec
`emrtd_do_auth` already returns true when BAC isn't needed, that check was previously there to account for auth failures (wrong MRZ) and cases where eMRTDs weren't detected. The change done in that commit to look for `(BAC && !auth_result)` simply leads this check to always be bypassed.
This PR aims to restore that behavior while separating connect and auth logic into two functions and checking accordingly, in order to make it clear to the user that nothing was detected.
---
With pictures, when an eMRTD isn't present:
Before https://github.com/RfidResearchGroup/proxmark3/commit/b3c7dd64c64c6e58e67547672a51b5296d244aec:
After …
=> emrtd: Improve emrtd presence check logic

client/src/cmdhfemrtd.c
This PR:
- Dumps EF_CardAccess when doing hf emrtd dump
- Automatically changes document number to uppercase and checks for length of DOB/Expiry to ensure that stuff that has no chance of working will not be sent to the eMRTD
More information at #1117.
=> eMRTD additions

armsrc/Standalone/hf_iceclass.c
Add a mode to the HF_ICECLASS standalone mode.
This mode:
1. Reads 1 iClass tag (in the same fashion as the read & dump mode) to iceclass-temp.bin in mem.
2. Sims that iceclass-temp.bin file until the mode has been exited.
This mode allows the reading/dumping/simming of a iClass tag in one mode.
=> add dump_sim_mode to Standalone HF_ICECLASS

client/luascripts/hf_legic.lua, client/luascripts/hf_legic_clone.lua, client/src/cmdhf.c, client/src/cmdhflegic.c, client/src/cmdhflegic.h, doc/cliparser_todo.txt
Beginnings of LEGIC cliparserization... also added continuous mode for `hf legic reader`.
NOTE: LEGIC Lua scripts have been updated but not tested.
=> hf legic crc, rdbl, wrbl, sim, info, reader - now use cliparser

client/luascripts/hf_legic.lua, client/luascripts/hf_legic_clone.lua, client/src/cmdhflegic.c, doc/cliparser_todo.txt
This should complete the LEGIC cliparser
=> hf legic wipe, dump, restore, eload, esave - now use cliparser

client/src/cmdhfemrtd.c
TL;DR, as I specified [here](https://wf.lavatech.top/ave-but-random/emrtd-data-quirks#EF_SOD), some implementations include `05 00`h at the end of the algorithm descriptor, some don't.
This code ignores `05 00`h from all, which makes the code work more universally, including on samples 15, 17, 21, 22, 23.
=> emrtd: Account for hash algo quirks

armsrc/iso14443a.c, client/src/cmdhf14a.c, client/src/cmdhf14a.h, doc/cliparser_todo.txt, doc/magic_cards_notes.md
Also fixed a textual bug device side with regards to BCC config 1.
=> hf 14a config - now use cliparser

README.md
Also x86 is no longer supported
=> Updated precompiled links

client/android/CMakeLists.txt, client/android/pm3_main.c
=> android target client compability

.gitignore
Ignore mf_nonce_brute binary if it exists
=> fix gitignore mf_nonce_brute

client/src/cmdparser.c
Added star command in honor of @Iceman1001 hard work on this project
=> Added honor to Iceman1001

tools/hitag2crack/crack5opencl/ht2crack5opencl.c, tools/hitag2crack/crack5opencl/opencl.c, tools/hitag2crack/crack5opencl/opencl.h, tools/hitag2crack/crack5opencl/queue.c, tools/hitag2crack/crack5opencl/queue.h, tools/hitag2crack/crack5opencl/threads.c, tools/hitag2crack/crack5opencl/threads.h
Changelog:
- move thread scheduler logic in threads.c
- move opencl engine in opencl.c
- minor fixes
=> crack5opencl - move logic from main to threads.c and opencl.c

client/src/cmdhfmfdes.c, doc/commands.md
Added actual MF DESfire enumeration with the new command `hf mfdes bruteaid`. It takes a while though :)
Wishes for future:
=> Added actual MF DESfire enumeration

armsrc/Standalone/lf_em4100emul.c, armsrc/Standalone/lf_em4100rswb.c, armsrc/Standalone/lf_em4100rwc.c, armsrc/iclass.c, armsrc/mifareutil.c, client/deps/hardnested/hardnested_bf_core.c, client/src/cmdhf14a.c, client/src/cmdhf14b.c, client/src/cmdhw.c, client/src/cmdlf.c, client/src/cmdlfem410x.c, client/src/cmdlfindala.c, client/src/cmdlft55xx.c, client/src/cmdtrace.c, client/src/util.c, client/src/util.h, client/src/wiegand_formats.c, client/src/wiegand_formatutils.c, common/generator.c, common/iso15693tools.c, doc/commands.md, tools/hitag2crack/crack5opencl/opencl.c
=> make style on master

pm3
Allow the pm3 script to find proxmarks with old firmware.
=> Added the original VID and PID values

pm3
=> Escape needed for WSL

client/src/cmdlfgallagher.c
Add ability to clone Gallagher cards by specifying their region code, facility code, card number & issue level
=> Improve support for Gallagher cloning

client/src/cmdlfgallagher.c
Extract `region_code`/`facility_code`/`card_number`/`issue_level` validation to `isValidGallagherParams` function
Add `--rc/fc/cn/il` parameters to `lf gallagher sim`
Draft pull request as I don't have access to a reader (or another proxmark) for a couple of days, so hasn't been tested on real hardware. Correct data is printed on line 428 so I expect it to work.
=> Support specifying region/facility/card/issue numbers to Gallagher simulation

client/gen_pm3mfsim_script.sh, client/luascripts/hf_mf_autopwn.lua, client/luascripts/hf_mf_tnp3_dump.lua, client/luascripts/hf_mf_tnp3_sim.lua, client/src/cmdhfmf.c, client/src/proxmark3.c, doc/cheatsheet.md, doc/cliparser_todo.txt
Here is the beginning of the hf mf cliparserization.
=> hf mf - cliparser

client/src/cmdhfemrtd.c, client/src/cmdhfemrtd.h
Parses EF_CardAccess and displays the algorithm information.
=> emrtd: Add PACE algo detection

client/src/cmdlft55xx.c
=> lf t55: Fix a typo

client/src/cmdhfemrtd.c
Whoops, forgot to add this to offline too.
=> emrtd: Add EF_CardAccess parsing to offline info

CHANGELOG.md
=> changelog: Add hf emrtd info changes

appveyor.yml
Added missing `python3-pip` package for WSL.
=> Appveyor WSL fix

.github/workflows/windows.yml
=> Github actions for Windows

.gitignore, CHANGELOG.md, client/luascripts/ntag_getsig.lua
=> ntag_getsig: Introduce ntag_getsig

.github/workflows/windows.yml, appveyor.yml
I did move the file that is used to detect the ProxSpace version
=> Fixes for ProxSpace v3.9

README.md
This RP is to make sure the CI still works.
=> Update README.md for Proxspace v3.9

CHANGELOG.md, armsrc/Standalone/Makefile.hal, armsrc/Standalone/Makefile.inc, armsrc/Standalone/hf_tmudford.c, armsrc/appmain.c, armsrc/iso15693.c, armsrc/iso15693.h, doc/md/Use_of_Proxmark/4_Advanced-compilation-parameters.md, include/iso15.h
Added a standalone mode that scans for an emulates ISO15693 cards.
=> Added standalone mode for ISO15693 cards.

armsrc/em4x50.c
PM3 Easy stopped when using em4x50_brute -> fixed
=> watchdog in 4x50 brute function

doc/termux_notes.md
hi,
i added some infos about the reader, the bluetooth addon and the firmware, also some lines for troubleshooting.
=> C0decave requirements docu changes btaddon

client/src/cmdhf14a.c
This PR adds support for detecting and retrieving NDEF data from type 4 tags.
=> Add hf 14a ndef command for type 4 tags

.github/workflows/macos.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml
This PR will make Github Actions to not run on changes at non-sourcecode folders.
=> ci: exclude changes to non-source folders

doc/termux_notes.md
Add `proxmark3-git` package and quick explanations
=> Update Termux instructions for packages

client/resources/aidlist.json
add cipurse aid to command `hf search`
=> add cipurse aid

client/luascripts/hf_14a_protectimus_nfc.lua
Add support for the RFID-based TOTP hardware token Protectimus SLIM NFC via a Lua script
=> add Lua script for RFID-based TOTP token Protectimus SLIM NFC

client/src/cmdhf.c, client/src/cmdhf14a.c, client/src/cmdhf14a.h
fixed cipurse `hf search` behavior and add some aid search to link to commands
=> fixed `hf search` behavior bug from discord

client/src/cmdhfmf.c
=> fixed typo.

CHANGELOG.md, armsrc/Standalone/Makefile.hal, armsrc/Standalone/Makefile.inc, armsrc/Standalone/lf_nexid.c
Here is a Standalone mode for the nexwatch tags :)
=> Standalone update for lf nexwatch

client/luascripts/hf_15_magic.lua
There was a change in `hf 15 raw` and this script was not updated to support that change
=> Change in hf 15 raw broke support hf_15_magic.lua

client/src/cmdhficlass.c
Fixes a variable pointer range issue and changes the client to handle cards with an impropper application limit.
I received some unpersonalized iClass cards that came with the config block set as `FF...` setting AA1 limit to 255. This caused a crash when attempting to dump the card. The crash seems to have been caused by the memcpy attempting to copy past the allocated variables size (starting at block 6 only 250 blocks would be left). I suspect this would cause issues if AA1 was ever > 250.
Also see https://discord.com/channels/738045391416852520/738046308929110076/856658801645977610
=> iClass Updates - AA1 Size

armsrc/Standalone/Makefile.hal, armsrc/Standalone/Makefile.inc, armsrc/Standalone/lf_hidfcbrute.c, armsrc/Standalone/lf_hidfcbrute.h
This requires a known card number, but often works as 1 is a default.
My first stand-alone module, so let me know if there are any pointers etc :)
=> Add a standalone FacilityCode bruteforcer for HID

client/src/cmdhficlass.c
Follow up to improve https://github.com/RfidResearchGroup/proxmark3/pull/1393
=> `hf iclass encode` support >32 bit formats

client/src/cmdhfmfdes.c
=> Desfire: select MF via iso and select EF by ISO ID via ISO

client/src/cmdhfmfdes.c
=> add change keys command samples

CHANGELOG.md, armsrc/Standalone/lf_icehid.c, armsrc/lfops.c, client/src/cmddata.c, client/src/cmdlfem410x.c, client/src/cmdlfem410x.h, common/lfdemod.c
Not so easy to get a smooth integration of Electra support.
Please have a look before merging.
=> Electra branch

client/src/cmdhfmfdes.c, client/src/mifare/desfirecore.c, client/src/mifare/desfirecrypto.c, client/src/mifare/desfirecrypto.h, client/src/mifare/desfiresecurechan.c
=> Desfire setconfig d40/ev1/ev2

client/src/cmdhfmfdes.c, client/src/mifare/desfirecore.c, client/src/mifare/desfiresecurechan.c
=> desfire changekey ev2

client/src/proxmark3.c
Improve user experience
Before:
After:
=> Improve user experience

client/src/cmdhfmfu.c
=> Add support for Shanghai Feiju NTAG213

client/src/cmdhfmfdes.c, client/src/mifare/desfirecore.c, client/src/mifare/desfirecore.h, client/src/mifare/desfiresecurechan.c
=> Desfire iso commands

client/src/cmdhffelica.c
I run into new Suica card with IC Type that is not in the list.
=> Add Suica card IC Type

client/src/cmdhf14a.c
=> hf 14a reader fix

client/src/cmdhfmfdes.c, client/src/mifare/desfirecore.c
=> Iso id byte order fix

armsrc/Standalone/hf_mfcsim.c
#1438 
use `BigBuf_free_keep_EM()` instead of `BigBuf_free()`
=> fix uid 0000000

client/src/cmdhfmfdes.c
=> Hex cli check

client/src/cmdhfmfdes.c, client/src/mifare/desfirecore.c, client/src/mifare/desfirecore.h, client/src/mifare/desfirecrypto.c, client/src/mifare/desfirecrypto.h, client/src/mifare/desfiresecurechan.c, client/src/mifare/desfiretest.c
=> Desfire transactions support

client/src/cmdhfmfdes.c, doc/desfire.md
=> Desfire doc

armsrc/Standalone/hf_mfcsim.c
Add multi cards support 
Use LED to indicate card slot
=> hf_mfcsim refactored

client/dictionaries/mfc_default_keys.dic
The sectors contain Name, Birthdate, Org no, Org name. etc
=> Added keys from norwegian building site cards

client/src/cmdhfmfdes.c, client/src/mifare/desfirecore.c, client/src/mifare/desfirecore.h, client/src/mifare/desfirecrypto.c, client/src/mifare/desfirecrypto.h, client/src/mifare/desfiresecurechan.c, client/src/mifare/lrpcrypto.c
=> iso id fix and add entering iso id to some commands

client/src/mifare/desfirecore.c
=> increase buffer len

client/src/cmdhfmf.c
=> Fixed typo in the key table function

CHANGELOG.md, tools/hitag2crack/crack5opencl/queue.c, tools/hitag2crack/crack5opencl/threads.c
=> fix crack5opencl queue/threads.c

armsrc/felica.c
apparent typo, listenmode should be set to false in order to send the
prepared response
=> armsrc/felica: fix handling POLL with Request Code 1

CHANGELOG.md, armsrc/Standalone/lf_em4100rswb.c, armsrc/Standalone/lf_em4100rwc.c, armsrc/Standalone/lf_hidbrute.c, armsrc/Standalone/lf_icehid.c, armsrc/Standalone/lf_nexid.c, armsrc/Standalone/lf_proxbrute.c, armsrc/Standalone/lf_samyrun.c, armsrc/Standalone/lf_tharexde.c, armsrc/appmain.c, armsrc/em4x50.c, armsrc/em4x50.h, armsrc/em4x70.c, armsrc/em4x70.h, armsrc/hitag2.c, armsrc/hitag2.h, armsrc/hitagS.c, armsrc/hitagS.h, armsrc/lfadc.c, armsrc/lfadc.h, armsrc/lfops.c, armsrc/lfops.h, armsrc/lfsampling.c, armsrc/lfsampling.h, armsrc/pcf7931.c, armsrc/pcf7931.h
As discussed in #1529 I have added ledcontrol argument to all LF operations.
=> Added ledcontrol to LF operations

armsrc/felica.c
Make sure we respond in a valid time slot.
We were responding too early, the first time slot (which is always allowed) starts after 512 * 64 / fc.
Also, respond in incremental time slots. We could have used a fixed time slot (#0 is always allowed), but by using incremental time slots we have a better chance the reader will get our response in the expected time frame.
(when our timing is wrong, we have a risk of responding too early when using the first slot, and too late when using the last slot. Slots in the middle of the allowed range have the best chance)
=> armsrc/felica: add polling response time slot support to felica_sim_lite

armsrc/Standalone/dankarmulti.c
As mentioned, a short description of how this works.
=> Added explanation of how dankarmulti works

client/src/cmdhfmf.c, client/src/cmdhfmfp.c
=> fixed some spelling

client/deps/liblua/luaconf.h, client/src/util_darwin.m
More tweaks for Swift/iOS support of libpm3
The lualib one comes from http://lua-users.org/lists/lua-l/2017-09/msg00242.html
=> preprocessor macros for iOS

CHANGELOG.md, doc/magic_cards_notes.md, hf_mf_ultimatecard.lua
Added hf_mf_ultimatecard.lua for interacting with the UMC
=> Ultimate magic card (Gen4)

client/deps/liblua/luaconf.h
From Discord: https://discord.com/channels/738045391416852520/790252611361964093/937430129863446621
=> remove system define that messes up termux

client/src/cmdhf14a.c
Found during troubleshooting #1583 (unfortunately this is not reason of the bug 😞 )
=> Fix wrong log message value

CHANGELOG.md, client/src/cmdhfmfu.c
Signed-off-by: İlteriş Eroğlu <ilteris@asenkron.com.tr>
=> add silicon info logic to hf mfu info (only for nxp chips)

CHANGELOG.md, client/luascripts/hf_mf_efmt.lua, client/luascripts/hf_mf_em_util.lua
Added a new script that writes default or user defined Keys and Access bits to the emulator memory blocks.
=> New luascript file to format Sector Trailers on the MiFare emulator

.github/workflows/codeql-analysis.yml
=> Adopt CodeQL to proxmark3

CHANGELOG.md, armsrc/iso15693.c
=> fix slixdisable pass id

armsrc/Standalone/Makefile.hal, armsrc/Standalone/hf_14bsniff.c
Useful when the PM3 hardware needs to be power cycled
=> Add flashmem support for HF_14BSNIFF standalone mode

armsrc/Standalone/Makefile.hal, armsrc/Standalone/hf_14asniff.c
Changes are similar to this PR #1620
=> Make HF_14ASNIFF standalone mode compatible with old PM3 (without flashmem)

client/src/ui/overlays.ui
This tip will be shown behind the "Apply" and "Restore" button
=> Show a tip in the plot window

armsrc/felica.c
Fixed a wrong CRC generated by the FELICA_APPEND_CRC flag.
=> Fix felica_sendraw

armsrc/appmain.c, armsrc/mifarecmd.c, armsrc/mifarecmd.h, armsrc/mifareutil.c, armsrc/mifareutil.h, client/src/cmdhfmf.c, include/pm3_cmd.h
Added increment value, decrement value via the supplied commands and set value via the normal write command.  Also added "get" to read a value block and decode/display.
Initial implementation for review and feedback.
=> Mifare Classic Value operations

armsrc/mifarecmd.c, client/src/mifare/mifarehost.c
Look what I found...
Wow, is fast decrypt staticnested :)
Hahahahaha, this is a very big advance.
=> StaticNested fast decrypt(backdoor 2nt.).

doc/md/Installation_Instructions/Windows-Installation-Instructions.md
=> Update Windows-Installation-Instructions.md (fix grammar)

CHANGELOG.md, client/src/flash.c, client/src/flash.h, client/src/proxmark3.c
Hello,
I need this feature, to be able to implement hardware testing for PM3.
I will be using UART over TCP to expose only one PM3 to container and that might be complicated to setup with how flashing works by default
=> Reboot to bootloader

client/dictionaries/ht2_default.dic
Hopefully the correct password
=> Add Paxton hitag2 password

client/pyscripts/amiibo_change_uid.py
As per https://github.com/RfidResearchGroup/proxmark3/pull/1735#issuecomment-1200112432
=> add comment indicating pyamiibo should be installed

client/src/fileutils.c
Fix eload from json files failing (ie, hf mf eload -f file.json) the dump is the full size.
Also fixed an accidental client double free when loading dumps.
=> Fix eload from json files failing

CHANGELOG.md, client/luascripts/hf_mf_sim_hid.lua
Added a script that will allow for simulation of HID Mifare credentials
Currently only with H10301 support
=> hf_mf_hid_sim.lua

CHANGELOG.md, armsrc/appmain.c, armsrc/iso15693.c, armsrc/iso15693.h, client/src/cmdhf15.c, include/pm3_cmd.h
I added some functionality to the ISO15693 emulation. Please consider this for inclusion.
=> ISO15693 emulation

CHANGELOG.md, client/src/cmdhfmfu.c
Patch to stop buffer overflow on ndef read from card
Typo fix in change log.
=> mfu ndef error

CHANGELOG.md, armsrc/Standalone/hf_tmudford.c, armsrc/iso15693.c, armsrc/iso15693.h, client/src/cmdhf15.c
I added the write block and write multiple block commands to the `hf 15 sim` emulation and implemented `hf 15 eview` and `hf 15 esave`.
I merged in master to resolve one conflict where both sides did the same thing (fix #1771).
Please consider for inclusion.
=> Iso15693 improvements

client/src/cmdhf14b.c
=> Fix dump of SRT512 tag

client/dictionaries/mfc_default_keys.dic
Adds the shared key between all the cards in the Transport system of Montevideo, Uruguay
=> Adds Uruguay transport system key

client/src/cmddata.c
=> Fix read oob in data diff

client/dictionaries/mfc_default_keys.dic
Adds some context for both Argentina and Uruguay transport system keys
=> More context for keys - SUBE + STM

CHANGELOG.md, client/src/cmdhfmf.c
Adds `hf mf gsave` for Gen4 GTU cards in mifare classic mode.
=> Add hf mf gsave

CHANGELOG.md, client/luascripts/hf_i2c_plus_2k_utils.lua
New script for modifying user memory on sectors 0 and 1 on the NTAG I2C PLUS 2k. Can be used to read blocks, write blocks, write a file to a sector or dump a sector to disk.
=> Added luascript for the NTAG I2C PLUS 2k

CHANGELOG.md, client/src/cmdscript.c
Should fix issue #1832
At least it still compiles and works against Python 3.10 :)
=> Moved to non-deprecated API to init Python intepreter

doc/md/Use_of_Proxmark/4_Advanced-compilation-parameters.md
Signed-off-by: cynix <cynix@cynix.org>
=> Add estimated FW size saving for SKIP_ZX8211

client/src/cmdscript.c
To resolve issue #1843 and allow compilation of all binaries on systems with old python version.
=> Conditional build of cmdscript to allow compilation with old python versions (<3.10.x)

client/src/cmdscript.c
Explained it during #1844 but it wasn't fixed before merging
=> Avoid memory leaks with Python <3.10

CHANGELOG.md, client/src/cmdpiv.c
The command allows to select the signature algorithm as well as the key slot to be used for signing.
Only tested on ECC-P256 (I don't have RSA samples at hand)
=> Add command `piv authsign`

client/src/cmdlfparadox.c
Add FC/CN to clone for paradox
=> Add fc/cn to Paradox clone

client/src/cmdscript.c
=> Fix python initialization to have SWIG work

client/src/cmdhftesla.c
Fixed bugs:
- typo in a comment
- one certificate was missing on the fob
- fob and phone app were not or mis-identified
=> Fix minor bugs in `hf tesla info`

client/src/cmdscript.c
also fixed a bunch of wrong comments.
=> Allow current directory to import python libraries

client/src/graph.c
Comment marked this as a TODO.
So, I did it.
=> Prevent buffer overflow in `AppendGraph()`

client/src/cmdhf15.c
If UID is passed as argument, e.g. "-u E011223344556677", the sanity check
`if ((scan + unaddressed + uidlen) > 1`  will always fail, because **uidlen** is set as the length of the UID in `util.c::param_gethex_to_eol`.
=> HF15: Write / Read  when is UID is passed as argument

CHANGELOG.md, client/CMakeLists.txt, client/Makefile, client/src/uart/uart_win32.c
Tested on commit 0f70df5de
<details>
<summary>Pictures</summary>
USB:
TCP:
(Hardware is connected to my host machine, client is running on the VM)
</details>
=> Add TCP connection support on Windows

doc/magic_cards_notes.md
Added "Activate direct write to block 0" to gen 4 gtu index. Edited the "dump configuration" section
=> Small corrections

armsrc/mifareutil.c
Nested attack should work again
=> Fix lost arguments

.github/workflows/uniq.yaml, client/src/cmdhfmf.c
If any of the .dic files have repeated keys this workflow will fail.
It could be configured as a check for the Pull Requests
=> Workflow to check for uniq keys

client/src/cmdhficlass.c, doc/commands.json
and specifying it for non-binary
=> Add text explaining that the format is H10301 for binary

client/resources/aidlist.json, client/src/cmdhflist.c
- Add annotation for a new ECP type
- Expand aidlist.json
=> Update aidlist, add new ECP annotation

client/resources/ecplist.json
=> Update ECP database

client/src/cmdhfmf.c
small MAD processing fix. NDEF record was not read completely
=> fix reading NDEF from Mifare Classic

client/Makefile
https://github.com/RfidResearchGroup/proxmark3/issues/2062
=> define proxguiqt.cpp depends to avoid parallel/shuffle build failure

client/src/emv/cmdemv.c
=> emv: display the transaction time as HH:MM:SS

armsrc/BigBuf.c, armsrc/BigBuf.h, armsrc/appmain.c, armsrc/cmd.c, armsrc/cmd.h, armsrc/dbprint.c, armsrc/dbprint.h, armsrc/em4x50.c, armsrc/em4x50.h, armsrc/em4x70.c, armsrc/em4x70.h, armsrc/epa.c, armsrc/epa.h, armsrc/felica.c, armsrc/felica.h, armsrc/fpgaloader.h, armsrc/hfops.c, armsrc/hfops.h, armsrc/hitag2.c, armsrc/hitag2.h, armsrc/hitag2_crypto.c, armsrc/spiffs.c, armsrc/spiffs.h, armsrc/usart.c
This is (should be) a zero-code PR.
Focused on the device side, this is ~20% through the arm files (essentially alphabetically, plus early spiffs treatment).
Next PR will start with `hitag2.h`.
=> Enable `const` in more places

client/src/cmdanalyse.c
This change includes a simple fix to allow for the proxmark3 client to be compiled on the Android platform using Termux. See #2076 for more info.
=> Fixes issue 2076

client/Makefile
This PR fixes macports configuration in the client Makefile.
=> Fix macports Makefile configuration.

tools/cryptorf/Makefile
My Raspberry Pi Zero with latest Raspberry Pi OS thanks this after commit b17a733
=> Fix linking in explicit libatomic devices

CHANGELOG.md, client/CMakeLists.txt, client/Makefile, client/experimental_lib/CMakeLists.txt, client/src/uart/ringbuffer.c, client/src/uart/ringbuffer.h, client/src/uart/uart_posix.c
I added a ring buffer to handle the UDP data
=> UDP support on Linux

.github/workflows/codeql-analysis.yml
=> Speed up CodeQL CI

CHANGELOG.md, client/src/comms.c, client/src/uart/uart_posix.c, client/src/uart/uart_win32.c
Tested with the commands below and all of them work
<details><summary>Commands</summary>
```
./pm3 -c "hw version" -p tcp:127.0.0.1
./pm3 -c "hw version" -p tcp:localhost
./pm3 -c "hw version" -p tcp:::1
./pm3 -c "hw version" -p tcp:fe80::93aa:5d6:ba82:b123%enp0s1
./pm3 -c "hw version" -p tcp:127.0.0.1:1777
./pm3 -c "hw version" -p tcp:localhost:1777
./pm3 -c "hw version" -p tcp:[127.0.0.1] # unexpected but works
./pm3 -c "hw version" -p tcp:[localhost] # unexpected but works
./pm3 -c "hw version" -p tcp:[::1] # unexpected but works
./pm3 -c "hw version" -p tcp:[fe80::93aa:5d6:ba82:b123%enp0s1] # unexpected but works
./pm3 -c "hw version" -p tcp:[127.0.0.1]:1777 # unexpected but works
./pm3 -c "hw version" -p tcp:[localhost]:1777 # unexpected but works
./pm3 -c "hw version" -p …
```
=> Add IPv6 support 

CHANGELOG.md, client/src/uart/uart_win32.c
The required timeout could be shorter now.
=> Add UDP support on Windows

common/cardhelper.c
Tested with the only SAM I have (Grace).
=> Fix potential stack overflow while making it easier to support more ATRs

CHANGELOG.md, client/src/uart/uart.h, client/src/uart/uart_posix.c, client/src/uart/uart_win32.c
For some USB serial to UDP bridge apps, the outbound port should be specified.
=> Added bind option for network connections

doc/termux_notes.md
And fixed some outdated links in the index
=> Add note for USB to UDP bridge app

CHANGELOG.md, doc/magic_cards_notes.md
The problem with PR 2003 is that all blame for some reason went to me.
I don't keep track of how PRs work, but I'd rather not try my luck with merging #2003 and then making the document essentially explode.
There's now this.
It's ready to be merged.
TLDR: added some country custom chips to cover for the rest of the userbase that could possibly be there.
=> The fix to the completely fixed magic notes

client/src/proxgui.h, client/src/proxguiqt.cpp, client/src/proxguiqt.h, client/src/ui.c
It's convenient to navigate with a slider
https://github.com/RfidResearchGroup/proxmark3/assets/62299611/17415ddd-104e-47df-82ee-75e8a558ca9c
=> Add a slider in the plot window for navigation

doc/md/Installation_Instructions/Troubleshooting.md
Ran into this issue during my installation process on pm3 easy. I hadn't seen the fix in the troubleshooting guide, but found others with this issue in the Github issues (#765) as well as the Discord, so I thought to add it into the troubleshooting guide to save user's some time searching.
=> Added common dependency troubleshooting

CHANGELOG.md, doc/magic_cards_notes.md
Add description for GTU modes for new version UMC
=> Add some info about UMC

client/src/wiegand_formats.c
Implements the basics of the Avigilon 56 bit format https://accessit.acre-co.com/kb/article/531-avigilon-56-bit-card-format/
=> Implement Avigilon 56bit format

CHANGELOG.md
=> Add some CHANGELOG items

CHANGELOG.md, armsrc/Standalone/hf_unisniff.c, doc/md/Use_of_Proxmark/4_Advanced-compilation-parameters.md
Also updated CHANGELOG.md & doc/md/Use_of_Proxmark/4_Advanced-compilation-parameters.md to reflect new mode
=> hf_unisniff: rename 'ASK' to 'USER' to avoid confusion

CHANGELOG.md, client/src/cmdhw.c, client/src/flash.c, client/src/flash.h, client/src/proxmark3.c
Add `hw bootloader` command to reboot to the bootloader
=> Add hw bootloader

CHANGELOG.md, client/src/cmdhfwaveshare.c, client/src/imgutils.c, client/src/imgutils.h
As requested in the previous PR, this adds automatic scaling and cropping of images in Waveshare.
=> Add image cropping and scaling

client/deps/hardnested/hardnested_bruteforce.c, client/src/cmdhf14a.c, client/src/cmdhf15.c, client/src/cmdhfcryptorf.c, client/src/cmdhfemrtd.c, client/src/cmdlf.c, client/src/cmdlft55xx.c, client/src/cmdsmartcard.c, client/src/scripting.c, client/src/uart/uart_win32.c, client/src/ui.c
Just client side for now, have to muck with the armsrc Makefile to run it against the client code too
=> Fix some missing frees, null dereferences and missing initialisation picked up by clang-analyzer

CHANGELOG.md, client/src/cmdhf.c, client/src/cmdlf.c, client/src/ui.c, client/src/ui.h
and fixed a bug in `print_progress()`
=> Show statistical data after tuning

client/src/fileutils.c
/!\ I don't have any old JSON dump file with me, so I did not test much... Sorry for that /!\
=> iso15: provide support to load old JSON dump format into iso15_tag_t

doc/md/Installation_Instructions/Windows-Installation-Instructions.md, doc/md/Installation_Instructions/Windows-WSL2-Installation-Instructions.md
Significant changes with release of USBIPD v4.0.0.
Plus I had to rebuild anyways, so may as well log some of the changes, for others using WSL2 for this.
=> update wsl2 instructions for USBIPD v4.0.0

doc/jtag_notes.md, tools/jtag_openocd/interface-cmsis-dap.cfg, tools/jtag_openocd/openocd_configuration.sample
Add config file for CMSIS-DAP
Highlight the note for unlocking the JTAG ports
=> Misc work about flashing firmware by JTAG

client/pyscripts/intertic.py
Adding Strasbourg, Le Have and now split OrganizationalAuthority & Contract_Provider
=> Intertic client Python script update

client/src/cmdhfmfdes.c
=> Fix MIFARE DESfire DeleteApp command

client/src/proxguiqt.cpp
- Added hotkeys to move the yellow/purple cursor around
- Added hotkeys to manually increment/decrement a value from a plot point 
- This is currently the point where the yellow cursor is at
So, after fighting with the plot graph for _way too long_, I decided to quickly throw this together to make my life easier. Hopefully others have a use for it as well.
=> Plot improvements

client/luascripts/lf_ioprox_bulkclone.lua
=> Update lf_ioprox_bulkclone.lua Spelling

CHANGELOG.md, client/resources/aid_desfire.json
I am a total noob still and I have no idea what the AIDs do.
=> Added Presto Transit Card to aid_desfire.json

.github/workflows/macos.yml, .github/workflows/ubuntu.yml, tools/pm3_tests.sh
* Uses official Github action `actions/setup-python` to install python.
This avoids the hacks that are otherwise required on MacOS.
* Fix the broken hitag self-test
=> Fix Github Action builds

doc/magic_cards_notes.md
Update to include brief outline of USCUID-UL chips
Removed hidden block reading and writing from UFUID chips, as these do not have hidden blocks.
=> Update to include USCUID-UL

client/luascripts/hf_legic_clone.lua
=> fix: hf_legic_clone.lua script

client/luascripts/lf_electra.lua
Script created by: https://github.com/jareckib 
Original topic, and why this exist can be found under: https://forum.dangerousthings.com/t/lua-script-for-proxmark3/19260
Original repo: https://github.com/vasilpetrov/lf_electra
=> Lua script for cloning new ELECTRA tags or EM410x to T5577 tag

client/dictionaries/mfc_default_keys.dic
Update mfc_default_keys.dic to add key for hotel in Greece
=> Add key for hotel in Greece

tools/mfc/card_only/staticnested_0nt.c
Fixes keyCount_mutex[0] and keyCounts[0] not being properly initialised
Fixes progress reporting not properly clearing the line
Switch malloc(a*b) style calls to calloc(a, b)
=> Fix staticnested_0nt on mingw/proxspace

CHANGELOG.md, armsrc/hitagS.c, client/src/cmdlfhitag.c, include/hitag.h
I don't have a Hitag card reader, so we need more testing on the Simulation part
=> fix: Hitag S read/write in plain mode

doc/md/Installation_Instructions/Troubleshooting.md, doc/md/Installation_Instructions/usb-enumeration-and-flash.md
Created as a strawman response to iceman's
suggestion that this would be useful in the repo.
Feel free to move it elsewhere / edit, as you prefer.
=> USB enumeration / serial number writeup / docs

client/src/cmdlfem410x.c
I hastily pushed the last commit without checking... Here it is _actually_ fixed.
=> Actually fix ELECTRA parsing

armsrc/iclass.c
Improved error logging to better understand what's happening
=> Update iclass.c legacy recover error logging

armsrc/Makefile, armsrc/appmain.c, armsrc/start.c, common_arm/Makefile.hal
refactor: Renamed WITH_NO_COMPRESSION to WITH_COMPRESSION for consistent style
=> refactor: Renamed WITH_NO_COMPRESSION to WITH_COMPRESSION

client/luascripts/hf_ntag_bruteforce.lua
=> chore: update hf_ntag_bruteforce.lua

armsrc/util.c, armsrc/util.h, client/src/cmdhficlass.c, include/iclass_cmd.h
1- Streamlined legbrute to remove then need for CSN and validate variables accuracy as per Iceman's suggestions. 
2- Updated legrec (client side only) for the future arm side PR 
3- Fixed variable overflow on the arm side for hex conversions
=> Updates to iclass legrec and legbrute

client/resources/aid_desfire.json
Added UMO Mobility transport AIDs.
Added European Student Card student AIDs.
AIDs obtained from various Discord Communities with the help of their Members.
Randy.
=> R&Y: Added UMO and MONECARTE AIDs to aid_desfire.json

client/src/loclass/ikeys.c
Finished the pre-image generation algorithm to take in account edge scenarios based on special values of z0..z7 that return the same modulo values even tho they have different original values. This allows the generation of more than 8 pre-images when reversing hash0, showing the full set of valid pre-images per each diversified key.
=> Completed hf iclass unhash pre-image generation

CHANGELOG.md, client/src/cmdhficlass.c
Improved config card generation to support using a different key than the default k0 for the card's key
=> Updated iclass config card generation

client/src/cmdhficlass.c
Added more detailed instructions for next steps after unhashing
=> hf iclass unhash improvements

CHANGELOG.md, common_arm/flashmem.c, common_arm/flashmem.h
Tested on RDV4, (piswords) Easy, Modded (piswords) Eeasy :
=> show SPI flash JEDEC data

CHANGELOG.md, client/pyscripts/spi_flash_decode.py
=> add a helper script to decode SPI flash JEDEC data

client/resources/aid_desfire.json
**Updated PDX hop fastpass**
- *Updated name and description to use its correct name/stylisation.*
- *Many thanks to bettse for their assistance.*
**Added HID AIDs**
- *Based on information obtained within the Discord Server, with many thanks.*
- *SIO EV3 HID Factory AID added.*
- *SIO EV3 Field Encoder AID added.*
**Updated PACS AIDs**
- *Updated several names and descriptions to improve `hf mfdes lsapp --no-auth` command output consistency.*
-randy.
=> R&Y: Updated PDX hop fastpass and Added HID AIDs to aid_desfire.json

client/pyscripts/fm11rf08s_recovery.py
Both of these annoyed me way too much so we're here now
=> fm11rf08s_recovery.py: option to keep generated dictionaries after processing; save dump and key to the path shown in `prefs show`

armsrc/hitagS.c
probably a regression from timer changes in 911766b
=> hitagS sim: fix timing of receive

common/commonutil.c, common/commonutil.h
@n0emis Would you mind verifying if this PR resolves the issue? https://github.com/RfidResearchGroup/proxmark3/pull/2591
=> fix: concatbits erase out-of-bound

client/resources/aid_desfire.json
- Various Student AIDs added from various Servers with the help of their respective Members.
- Missing information will be added where possible as a future commit.
-R&Y.
=> R&Y: Added Various Student AIDs to aid_desfire.json

client/src/cmdpiv.c
I had these commits in my local client and forgot to push them :)
=> Some fixes on PIV

client/src/cmdhf14b.c
Also replaced hard-coded buffer sizes with the correct macro.
=> Fix potential overflow in readblock

client/luascripts/hf_legic.lua
I haven't tried all the code yet (mainly because I was initially lacking blank Legic that I could mess with)
Should at least fix issue #2500
=> Start fixing legic script to work with lu5.4

common_arm/flashmem.c, common_arm/flashmem.h
fallback to 4 pages when SPI IC is unknown
some code styling
remove some unused code
=> fix failed spi flash detection

client/resources/aid_desfire.json
**F47300 *PACS* `Inner Range Pty Ltd`**
- Vendor updated to include full legal entity name
- Name updated to use correct product stylisation
**F33480 *Student* `Besucherausweis`**
- Updated Name to use more suitable English translation
- 484000 *Transport* `GDL SITEUR Mi Movilidad`
- DD00DD *Transport* `DEN RTD MyRide`
Thank you.
=> Updated Inner Range AID and Added PT AIDs

client/resources/aid_desfire.json
- Added MOBOTIX AID.
- Updated JFK OMNY AID to add BMW Digital Key as an alternative AID use.
Thank you,
=> Added PACS AID and Updated PT AID

CHANGELOG.md
insert my changes in the Chanchelog.md
=> insert hf_legic.lua script changes

client/resources/aid_desfire.json
- Added `GRB Tap-N-Go` `F21201` and `F21202` AIDs to aid_desfire.json.
Thank you.
-R&Y.
=> R&Y: Added GRB Tap-N-Go to aid_desfire.json

CHANGELOG.md, common_arm/flashmem.h
added some "extrapolated" but logical matches by Manufacturer/Device ID only
some reordering
=> added JEDEC information for SPI flash W25Q64JV

client/src/cmdhficlass.c
Added unhash instructions after legbrute
=> Added unhash instructions after legbrute

client/dictionaries/mfc_default_keys.dic
these cards are stored value and manipulating the data is useful
=> add static laundry card keys

fpga/xc2s50-5-tq144.ucf
Add Proxmark3 Ultimate  FPGA   xc2s50-5-tq144.ucf  files
=> Add Proxmark3 Ultimate  FPGA   xc2s50-5-tq144.ucf  files

client/resources/aid_desfire.json
Added with thanks to TheDingo8MyBaby:
- BDL Go CT AID
- CMH COTA Smartcard AID
-R&Y.
=> R&Y: Added BDL Go CT and CMH COTA Smartcard AIDs to aid_desfire.json

client/src/cmdhflist.c, client/src/cmdhflist.h, client/src/cmdtrace.c, doc/commands.json, include/protocols.h
Adding annotations for the FMCOS 2.0 CPU Card that is used/sold in China.
=> Add annotations for FMCOS2.0 CPU Card

client/resources/aid_desfire.json
Added to `aid_desfire.json`
- DAY RTA Tapp Card AID *with thanks to Discord/`@TheDingo8MyBaby`*
- Additional BKK BEM Stored Value Card AIDs *noting that this transit agency uses little-endian*.
-R&Y.
=> R&Y: Added DAY RTA Tapp Card and Additional BKK BEM SVC AIDs to `aid_desfire.json`

client/resources/aid_desfire.json
- Club AIR Amsterdam
- IST Istanbulkart (Unknown App)
- WRO URBANCARD (Holder/EP/Term Apps)
- ICT Gallagher AIDs
- Transact Campus ID
- Removed accented letters that did not parse correctly on output
- ORD Ventra
- ITSO AIDs
- MAD Public Transport Card (Removed `(Alternative Endian)` designation)
- GitHub: @mxcdoam
- GitHub: @Sunderw3k
-R&Y.
=> R&Y: Added Payment/Transport AIDs and Updated AIDs in `aid_desfire.json`

client/t55_chk.lua
Generated dictionary fixed
february - 28 or 29
=> t55_chk.lua

client/src/cmdhfemrtd.c
Some passport (eg. Chinese passport) save facial image in DG2 using JPEG2000 code stream, which magic is `FF 4F FF 51`.
https://en.wikipedia.org/wiki/JPEG_2000
https://github.com/RfidResearchGroup/proxmark3/issues/1117#issuecomment-2556661621
=> update cmdhfemrtd.c to support JPEG2000 code stream photo

client/resources/aid_desfire.json
- **Added** YWG peggo card to `F21201`.
-R&Y.
=> Added YWG peggo card to `aid_desfire.json`

client/luascripts/paxton_clone.lua
v1.20
Added verification - " Verification successful. Data was written correctly."
=> paxton_clone v1.20

armsrc/em4x70.c
=> Em4x70 -- Fix protocol error (Time from LIW detection until transmit first RM bit)

armsrc/em4x70.c
not sure how these lines didn't get included, so hotfix required.
=> Missing lines from my last commit

doc/magic_cards_notes.md
Added some new info, related to UL-Y tag
=> Added docs about UL-Y variations + NTAG215-cfg of that tag

client/src/cmdhftesla.c
This improves the `hf tesla info` command:
- Compatibility with more javacard variants
- Read the full certificate properly, not just the first 256 bytes
- Optionally parse the certificate (ASN.1)
- Don't bail at each error and try to read what it can
- Better form factor parsing
- Read all four public keys, not the first three
=> Improve Tesla NFC card reader command

client/src/cmdhficlass.c
Fixed spacing, time unit, and fixed a bug preventing from properly using the credit key.
=> iclass tearoff attack fixes

client/src/cmdhficlass.c
Updated iclass tearoff function to support custom delay increments
=> Updated trbl to support custom increments

client/src/cmdhficlass.c
Fixed a bug preventing tearoff stages from being detected correctly, increased verbosity of read data and granularity of displayed information
=> hf iclass trbl bugfixes and improvements

client/src/cmdhficlass.c
Implemented a functionality for hf iclass trbl to specify how many times to loop at specific delays.
=> Updated hf iclass trbl to support looping

client/src/cmdhficlass.c
Fixed tearoff staying armed in case of interruption
=> hf iclass trbl bugfixes

client/src/cmdhficlass.c
Added unsecure page mode support
=> updated hf iclass trbl to support unsecure page mode

client/src/cmdhfmf.c
Added when a Saflok card is detected, it decrypts and parses the data, outputting it to the screen.
Previous security researchers did this work, and I merely adapted it from the Flipper Zero code to the Proxmark3 code.
Their info is below:
// Decryption and parsing from: https://gitee.com/wangshuoyue/unsaflok 
// Decryption algorithm and parsing published by Shuoyue Wang 
// Parsing also inspired by Lennert Wouters and Ian Carroll's DEFCON 32 talk 
// https://defcon.org/html/defcon-32/dc-32-speakers.html 
// FZ parser by @Torron, with help from @xtruan, @zacharyweiss, @evilmog and kara (@Arkwin)
=> Saflok Parsing

armsrc/iclass.c
Updated hf iclass legrec:
1- Fixed communication timing inconsistencies by moving away from iclass_writeblock_ext to iclass_writeblock_sp which supports start_time and end_time
2- Reduced number of debug messages being printed
Overall this reduces slightly the speed of the process, but it should make it more stable as the timings are now all correctly being accounted for.
=> Updated hf iclass legrec

client/src/cmdhficlass.c
1- Automated tearoff for epurse without needing to pass the block data and key details (manual mode still available)
2- Improved read loop of original values (to reduce instances in which the block appears zeroed out)
3- Added a "fault tolerance" system to increase the threshold of read errors for old silicon cards before being shown to the user
4- Removed auth requirement to read blocks below 3
=> Updated hf iclass tearoff

client/src/loclass/ikeys.c
Updated code to fix loclass --test function now that iclass_key.bin is no longer in the repository as the master key has been added in the code.
=> Fixed loclass --test

CHANGELOG.md, armsrc/iclass.c, client/src/cmdhficlass.c, include/iclass_cmd.h
hf iclass sim -t 3 variation that glitches specific block responses during read/write operations based on the value of the last byte of block 31.
=> Implemented a hf iclass sim variation

client/src/cmdhficlass.c
Updated config cards section readability
=> Updated iclass config cards readability

README.md
Update Operating Systems list, WSL2 is now the most modern WSL and works well on Windows 10/11.
=> Update README.md - WSL operating systems reference

client/src/cmdhficlass.c
Improved sam response processing on client side, it detects when the response contains an error and highlights the error number, detects when the response is an snmp messages and does the asn.1 decoding of the snmp message.
=> Improved sam response parsing

armsrc/sam_common.c, client/src/cmdhficlass.c
Updated sam firmware version to be in decimal digits
=> Sam firmware output in decimal and unhash to detect AES key format

armsrc/sam_picopass.c
Added detection for Secure Channel Flag in Sam's response.
=> Added sc flag detection in sam response

armsrc/mifarecmd.c
address remaining issue from PR #2923, related to issue #2922
=> Fix: Follow-up fix for PR #2923 (issue #2922)

armsrc/iclass.c
Fixing https://github.com/Antiklesys/proxmark3/commit/24d80f51a9fd88d8125220dc60000e4ac09a9457 where an AND was switched to an OR
=> Fixing style fix

client/resources/aid_desfire.json
=> R&Y: Added `GEG Connect` to `aid_desfire.json`

client/deps/mqtt/win32_sockets.h, client/src/cmdmqtt.c
- proper pthread cancellation (segfault).
- closesocket instead of close & using SOCKET type instead of int (gdb warning).
=> fixes to mqtt (win sockets)

client/src/cmdhffelica.c
Related issue:
[bug] hf felica litedump returns data regardless of Read After Authentication(#2936)
=> Fix `hf felica litedump`

CHANGELOG.md, client/CMakeLists.txt, client/Makefile, client/src/cmdhf.c, client/src/cmdhfmf.c, client/src/cmdhfmf.h, client/src/cmdhfsaflok.c, client/src/cmdhfsaflok.h
added hf saflok commands to:
Read and decode mfc saflok cards
Provision new saflok cards
Encode new saflok data blocks
Modify saflok data blocks
interrogate variable keys from saflok cards
I Still need to add support for log parsing and ULC support and clean up the code a bit but this is what I have so far
=> added hf saflok command

armsrc/iso15693.c
fix incorrect tag response processing. The tag's responses were duplicated in the command channel
fix #2920
=> fix broken iso15693.c:SendRawCommand15693 (double answers)
